### ISSUE TITLE
PRD: [JB] Test command

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#100]
### Description:
As a user, I want Cody to generate unit tests for code that I've selected.

### Objectives:
Provide an easily discoverable, pre-packaged prompt that allows Cody to generate unit tests for code that a user has selected.

```[tasklist]
### Acceptance Criteria:
- [ ] https://github.com/sourcegraph/jetbrains/issues/406
- [ ] https://github.com/sourcegraph/jetbrains/issues/407
- [ ] https://github.com/sourcegraph/jetbrains/issues/408
```

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/sourcegraph/jetbrains/issues/118
- [ ] https://github.com/sourcegraph/jetbrains/issues/279
- [ ] https://github.com/sourcegraph/jetbrains/issues/280
- [ ] https://github.com/sourcegraph/cody/pull/2719
```

### Related Docs:

[PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit#heading=h.2wolyguph1ml)

**Comment by kalanchan** [comment]
done as of `6.0.0`
