### ISSUE TITLE
PRD: [JB] Smell command

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#102]
### Description:
As a user, I want Cody to provide suggestions for how I can improve the quality of the code that I've selected.

### Objectives:
Provide an easily discoverable, pre-packaged prompt that allows Cody to help users improve the quality of their code.

```[tasklist]
### Acceptance Criteria:
- [ ] https://github.com/sourcegraph/jetbrains/issues/413
- [ ] https://github.com/sourcegraph/jetbrains/issues/414
- [ ] https://github.com/sourcegraph/jetbrains/issues/415
```

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/sourcegraph/jetbrains/issues/118
- [ ] Move smell recipe to the new chat-based API
- [ ] https://github.com/sourcegraph/cody/pull/2719
```

### Related Docs:

[PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit#heading=h.2wolyguph1ml)

**Comment by kalanchan** [comment]
done as of `6.0.0`
