### ISSUE TITLE
PRD: [JB] Users can provide feedback on Cody's helpfulness

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#104]
### Description:

As a member of the Sourcegraph team, I want to understand the quality of Cody's responses. Users should be able to submit a thumbs up/thumbs down reaction to any chat or command response that Cody provides. P2: If the user submits a "thumbs down," they should have an option to categorize the reason for the negative response (categorizations TODO).

### Objectives:

Learn more about when Cody is helpful/unhelpful to users.

```[tasklist]
### Acceptance Criteria:
- [ ] https://github.com/sourcegraph/jetbrains/issues/397
- [ ] https://github.com/sourcegraph/jetbrains/issues/398
- [ ] https://github.com/sourcegraph/jetbrains/issues/399
- [ ] https://github.com/sourcegraph/jetbrains/issues/400
- [ ] https://github.com/sourcegraph/jetbrains/issues/401
```

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
```

### Related Docs:

[PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit)

**Comment by kalanchan** [comment]
Missing telemetry data from JetBrains

**Comment by exigow** [comment]
IMHO ticket https://github.com/sourcegraph/jetbrains/issues/135 addresses a similar topic and is more important to do.

**Comment by taylorsperry** [comment]
I'm closing this until we have a better strategy for how to action on thumbs up/down feedback
