### ISSUE TITLE
JetBrains: Code Context is missing in response.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1041]
### Installation Information

Plugin version: `5.3.4304-nightly`
IDE version:` IC-233.14475.28`

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains IntelliJ IDEA editor
2. User is already logged in to Cody with Free/Pro/Enterprise account
3. Open any file, go to Commands and select "Explain Code"
4. Verify the response

### Observed behavior:
Code context is missing from the response.

### Expected behavior

Code context should be there along with line number.

### Additional context

**Screenshot:**

<img width="495" alt="Screenshot 2024-03-11 at 9 57 03 PM" src="https://github.com/sourcegraph/jetbrains/assets/158482423/7b087406-9ab0-43ed-a6bf-a596647863aa">

**Comment by pkukielka** [comment]
Fixed by https://github.com/sourcegraph/jetbrains/pull/1079
