### ISSUE TITLE
PRD: [JB] Users can understand and manage Enhanced Context for chat

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#105]
### Description:

As a user, I want to understand what's available as "enhanced context" for chat and be able to manage it for my open project. 

#### Enabling Enhanced Context 
As a any kind of user (Cody Free, Cody Pro, Enterprise), I should be able to turn enhanced context on or off. When enhanced context is off, I am simply chatting with the LLM without any context. I see that when I ask Cody a question in chat, Cody doesn't read any of my files for use as context.

#### Search indexing for Cody Free or Cody Pro users
As a Cody Free or Cody Pro user, I want to be able to enable enhanced context and see that Cody is either in the process of or has completed generating enhanced context for my open project. When I chat with Cody with enhanced context enabled, Cody should use search context of my project when generating a response. 

#### Embeddings generation for Cody Free or Cody Pro users
~As a Cody Free or Cody Pro user working on a project that has not been indexed on Sourcegraph.com, I want to be able to optionally generate embeddings for my open project. I want to understand that my code will be sent to Sourcegraph and OpenAI in order to generate embeddings, and I want to agree to it before Cody sends my code anywhere. Once I have opted to generate embeddings for my project, I want to see the progress of those embeddings and I want Cody to use those embeddings as context when I prompt Cody in chat with enhanced context enabled.~ 

~As a Cody Free or Cody Pro user working on a project that _has_ been indexed by Sourcegraph.com, I want to see that embeddings are inherited from Sourcegraph.com and are available to Cody as chat context when enhanced context is enabled.~ We will not be supporting local embeddings for GA. [[thread](https://sourcegraph.slack.com/archives/C0C324C91/p1704842314678319?thread_ts=1704479315.299139&cid=C0C324C91)] 

#### Search and embeddings for enterprise users
As an enterprise customer who has enabled enhanced context, I want to see the status of the search indexing of my current project ~and the status of embeddings for the project. If my admin has generated embeddings for my project, I should see that embeddings will be included as part of Cody's enhanced context; if my admin has _not_ generated embeddings for my project, I see that Cody will not generate embeddings or use embeddings as context in my chats. I am not able to generate embeddings on my own as an enterprise user.~ We will not be supporting embeddings for enterprise users for GA [[thread](https://sourcegraph.slack.com/archives/C05LHMA4GRE/p1701295093293779)]. 

### Objectives:

Whether a user is a free community user or an enterprise user, they should understand what is available to Cody as context. We know that understanding context is a major pain point among our users (and it's also one of Cody's primary differentiators), so it's critical that we make this clear and easy for users to manage.

```[tasklist]
### Acceptance Criteria:
- [ ] https://github.com/sourcegraph/jetbrains/issues/378
- [ ] https://github.com/sourcegraph/jetbrains/issues/379
- [ ] https://github.com/sourcegraph/jetbrains/issues/380
- [ ] https://github.com/sourcegraph/jetbrains/issues/381
- [ ] https://github.com/sourcegraph/jetbrains/issues/382
- [ ] https://github.com/sourcegraph/jetbrains/issues/383
```

### Design Tasks:

```[tasklist]
### Design Tasks
- [ ] Mimic enhanced context selector in VS Code

```
[Figma](https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=1028-31608&mode=design&t=qXxuqaU1scEoglbM-0)
<img width="262" alt="Screenshot 2023-12-21 at 2 06 12 PM" src="https://github.com/sourcegraph/jetbrains/assets/43555476/92639499-8b2c-409f-a835-feb982674131">

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/sourcegraph/jetbrains/issues/256
- [ ] https://github.com/sourcegraph/jetbrains/issues/257
- [ ] https://github.com/sourcegraph/jetbrains/issues/258
- [ ] https://github.com/sourcegraph/jetbrains/issues/259
```

### Related Docs:

[PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit)

**Comment by dominiccooney** [comment]
FYI @pkukielka my WIP of the VSCode side of multi-repo search is in the dpc/wip/multi-repo-enterprise-context branch.

I notice this issue, which covers seeing the status for enterprise search indexes, was removed from Feb 15/24 Launch @kalanchan. In VSCode, the enhanced context widget is how you add extra repositories to search. What's the plan for adding repos to multi-repo search in JetBrains for Feb?

**Comment by kalanchan** [comment]
done as of `6.0.0`
