### ISSUE TITLE
PRD: [JB] Users can configure Cody's current chat context

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#106]
### Description:

**See https://github.com/sourcegraph/cody/issues/1675 for related, ongoing discussion with the VSC team**

As a user, I want to be able to easily manage what Cody uses as context for a given chat prompt. I want to understand that Cody won't use any of my code as context by default, and will only use my code as context when explicitly configured.

P0: As a user, I want to easily add a single repo to Cody's current chat context.
P0: As a user, I want to easily add multiple repos to Cody's current chat context.
P1: As a user, I want to easily configure Cody's current chat context at a more granular level, eg, by folder, file, symbol, or line.

### Objectives:

Enable users to configure Cody's current chat context across multiple levels of granularity.

```[tasklist]
### Acceptance Criteria:
- [ ] https://github.com/sourcegraph/jetbrains/issues/391
- [ ] https://github.com/sourcegraph/jetbrains/issues/392
- [ ] https://github.com/sourcegraph/jetbrains/issues/393
- [ ] https://github.com/sourcegraph/jetbrains/issues/394
- [ ] https://github.com/sourcegraph/jetbrains/issues/395
- [ ] https://github.com/sourcegraph/jetbrains/issues/396
- [ ] https://github.com/sourcegraph/jetbrains/issues/1036
```

### Design Tasks:

```[tasklist]
### Design Tasks
- [x] "@" file command
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/sourcegraph/jetbrains/issues/242
```

### Related Docs:

[PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit)

**Comment by olafurpg** [comment]
Marking this as post Feb GA, but we could maybe squeeze in `@FILE` without resolving the other items. This would close an important gap against VS Code.

**Comment by mkondratek** [comment]
The issue focused on `@FILE`: https://github.com/sourcegraph/jetbrains/issues/242

**Comment by olafurpg** [comment]
@taylorsperry what do you think about marking this as a P1? Alternatively, narrow down the scope only for file and (maybe) repo as P0.

**Comment by taylorsperry** [comment]
In the acceptance criteria above, I've given a GA prefix to everything that I think is a P0 (I know that multi-repo selection is a must-have from the enterprise side). I've added GA prefixes to other issues as well, which should help narrow the scope overall. We can look at them together and see if we need to continue narrowing.

**Comment by kalanchan** [comment]
done as of 6.0.0!
