### ISSUE TITLE
Bug: Toolbar "Hide" button is not working when "Commands" tab is open

### ISSUE THREAD

**Issue by exigow** [sourcegraph/jetbrains#108]
### Installation Information:

* Plugin version: 5.2.4819
* IntelliJ IDEA 2023.1.4 (Community Edition) Build #IC-231.9225.16, built on July 13, 2023

### Steps to reproduce:

1. Navigate to Cody toolbar -> Commands
2. Click on "Hide"

![toolbarnotresponding](https://github.com/sourcegraph/jetbrains/assets/5013708/134aafaa-462c-4761-be37-d9f8fca43d95)

### Expected Behaviour:

The toolbar should minimize after clicking the "Hide" icon.

**Comment by mkondratek** [comment]
Fixed by https://github.com/sourcegraph/jetbrains/pull/175.
