### ISSUE TITLE
JetBrains: Unable to Upgrade Cody plugin from Upgrade notification.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1083]
### Installation Information

Plugin version: `5.4.1-nightly --> 5.4.5-nightly`
IDE: `PC-233.13763.11`
 

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin v5.4.1-nightly installed in your JetBrains PyCharm editor
2. Make sure you have set the Auto-updates enabled and on nightly channel
3. Close the IDE and relaunch it
4. Verify a notification pops up to upgrade Cody plugin
5. Hit the Upgrade plugin button and you will be redirected to Installed plugin page

### Observed behavior:
No Upgrade button is available for Cody plugin

### Expected behavior

Upgrade button should be there as a newer v5.4.5-nightly build is available.

### Additional context

**Video link:**

https://drive.google.com/file/d/16MdGU_pZUlnR0Mbz0x1G01SWavyfDluh/view?usp=drive_link

**Comment by kalanchan** [comment]
Might be a jetbrains platform issue?

**Comment by mkondratek** [comment]
It is possible to implement it correctly (however, it may require some ~hacking~ reflection). I estimate it as a 2-days task (for me).

**Comment by dominiccooney** [comment]
@mkondratek can you elaborate briefly? Isn't it JetBrains publishing these update notifications… and presumably it understands the version constraints?

**Comment by mkondratek** [comment]
There are two things.

1️⃣ Our upgrade notification properly appears when the upgrade is available but the plugin settings does not show the upgrade option.
2️⃣ JetBrains seems to have some mechanism to check and suggest updates but it works too rarely for us and that's why we have a custom notification.
