### ISSUE TITLE
JetBrains: File name appended in Command when checking in the Chat history.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1089]
### Installation Information

Plugin version: `5.4.5-nightly`
IDE version: `IC-233.14475.28`

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains PyCharm editor
2. User is already logged in to Cody using Free/Pro/Enterprise account
3. Open any sourcecode file
4. Go to Cody and run any command i.e. Generate Test
5. Click on "Chat History" and check the recent chat from above step

### Observed behavior:

File name is appended in the Cody command for that chat

### Expected behavior

File name should not be appended and the earlier behavior was correct.

### Additional context

Screenshot:

![File_name_appended_In_Commands](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/b5083c76-3058-4b7c-9aa0-bfb916270834/abc04846-65d2-4b10-9e1a-e2208818ec45?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy9iNTA4M2M3Ni0zMDU4LTRiN2MtOWFhMC1iZmI5MTYyNzA4MzQvYWJjMDQ4NDYtNjVkMi00YjEwLTllMWEtZTIyMDg4MThlYzQ1IiwiaWF0IjoxNzE3NDQ5ODM4LCJleHAiOjMzMjg4MDA5ODM4fQ.9xO5glcOd1um9slfmay6_-iBRLaLwsB4INPkShZ3bHU)

**Comment by mkondratek** [comment]
I don't think it's a bug. The prompt strings are defined in the code in Cody repo. They may change. In this case "the selected code" has been replaced by the proper file path. I believe that makes prompt more precise and give better results.

See the related code: 
https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/commands/execute/explain.ts?L48%3A5-54%3A6

The chat title is just a first ~40 character of the prompt.

@philipp-spiess, you are the one improving the prompts recently. Can you confirm that the prompt changes are ok?

**Comment by philipp-spiess** [comment]
@mkondratek The changes you linked to were from 1 day ago but the issue was reported a month ago. Not sure if this is related. 🤔

**Comment by mkondratek** [comment]
You are right. These changes are from 1 day ago but the replace on 'the selected code' was even before that. So basically that is an improvement made in meantime some a while ago. Not a bug.
