### ISSUE TITLE
Update Cody extension name for SEO

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#1099]
See https://docs.google.com/document/d/1Dd6IegY0l7g2x2xBPFKFuEtKw6U0F6uYGAJKTK6AwUQ/edit#heading=h.ubvxmq40v7u1

**Comment by vdavid** [comment]
Clues:
- You can edit most things [here](https://plugins.jetbrains.com/plugin/9682-sourcegraph-cody--code-search/edit) 
- And the description lives [here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/jetbrains/-/blob/README.md).

**Comment by iskyOS** [comment]
FYI, I have opened a PR to update the extension name here: https://github.com/sourcegraph/jetbrains/pull/1184
@taylorsperry
