### ISSUE TITLE
Inline Edits: Show Diff

### ISSUE THREAD

**Issue by steveyegge** [sourcegraph/jetbrains#1108]
### Installation Info:

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 11, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 10
Non-Bundled Plugins:
    com.sourcegraph.jetbrains (6.0-localbuild)

Kotlin: 221-1.6.20-release-285-IJ5080.210

### Description:

The VS Code extension shows a Code Lens, "Show Diff", in the "Accept/Retry/Undo/Diff" lens group after inserting a doc string or code edit sequence. This brings up a native diff viewer widget showing (just) the changes made by the AI for this particular fixup task.

We need this in JetBrains too. The Code Lens is already implemented. The diff widget or functionality is not documented in the JetBrains Plugin Development Guide, so it will take a little digging to figure out how to do it. I estimate it at a few days of work.

This issue is a placeholder for filling out all the actual detail when we do the Inline Edits PRD.

### Design Tasks:

```[tasklist]
### Design Tasks
- [ ] Add a draft title or issue reference here
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] Implement the show-diff widget
- [ ] Notifications/telemetry
```

### Related Docs:

- [PRD: Your-Title]()

**Comment by kalanchan** [comment]
@mkondratek does this also enable the "undo" feature, or is that separate work

edit: nevermind, my undo was buggy, it works now

**Comment by mkondratek** [comment]
@kalanchan, "undo" is separate work and I noticed it still requires some improvements
