### ISSUE TITLE
Inline Edits: Implement Hotkeys

### ISSUE THREAD

**Issue by steveyegge** [sourcegraph/jetbrains#1110]
### Installlation info:

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 11, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 10
Non-Bundled Plugins:
    com.sourcegraph.jetbrains (6.0-localbuild)

Kotlin: 221-1.6.20-release-285-IJ5080.210

### Description:

The hotkeys are displayed in the code lenses, but are not currently operational.

Need to set up the appropriate key listeners to invoke the lenses as actions, as if you had clicked them with the mouse.

### Design Tasks:

```[tasklist]
### Design Tasks
- [ ] Add a draft title or issue reference here
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] Add a draft title or issue reference here
```

### Related Docs:

- [PRD: Your-Title]()

**Comment by danielmarquespt** [comment]
@mkondratek I did a bit of research and I think we can go forward with:

Enter edit mode => ctrl + shift + enter 
Retry => ctrl + shift + enter

Accept edit => ctrl + shift + +
Show Diff => ctrl + shift + '

Undo edit => ctrl + shift + backspace

As far as I know, these are safe.

Also, these should be listed and configurable here as 

```
Edit Code: Open Edit Mode
Edit Code: Retry Edit
Edit Code: Accept Edit
Edit Code: Show Dif
Edit Code: Undo Edit

```

![Image](https://github.com/sourcegraph/jetbrains/assets/7814431/10556682-cc8b-4edc-9f83-ef8838341810)

**Comment by kalanchan** [comment]
done in 6.0.0!
