### ISSUE TITLE
bug: Inline Edits: Having a selection active confuses the Document Code action

### ISSUE THREAD

**Issue by steveyegge** [sourcegraph/jetbrains#1111]
### Installation Information

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 11, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 10
Non-Bundled Plugins:
    com.sourcegraph.jetbrains (6.0-localbuild)

Kotlin: 221-1.6.20-release-285-IJ5080.210
### Describe the bug

* Select, say, the center 10 lines of a 20-line method
* Right-click in those selected 10 lines to bring up the Context menu
* from the Cody submenu, choose Document Code

The code lens will usually be placed in the wrong spot -- not at the top of the method, but somewhere in the middle.

### Expected behavior

The code lens and doc comment should always be placed correctly at the top of the function, independent of the selection.

**Comment by kalanchan** [comment]
done as of `6.0.0`
