### ISSUE TITLE
JetBrains Inline Edits: Indent/format the rewritten code

### ISSUE THREAD

**Issue by steveyegge** [sourcegraph/jetbrains#1112]
### Description:

The rewritten code (from an Edit Code request) is not properly indented.  The VS Code extension does format it for you.

I have a hunch this might be a recently-introduced bug in the FixupController and/or Agent protocol.

### Design Tasks:

```[tasklist]
### Design Tasks
- [ ] Add a draft title or issue reference here
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] Add a draft title or issue reference here
```

### Related Docs:

- [PRD: Your-Title]()

**Comment by steveyegge** [comment]
The behavior is more random-seeming than I initially thought. Sometimes I do get the code returned as formatted/indented properly, but if there is a selection active, then the formatting is sometimes wrong on the first line.

In general this feature needs to be thoroughly tested.

**Comment by kalanchan** [comment]
https://github.com/sourcegraph/jetbrains/pull/1454

**Comment by odisseus** [comment]
If we still want to format the inline edits, we should apply the formatter only after the stream of edits has ended.
