### ISSUE TITLE
Inline Edits -- support file create/rename/delete operations (Generate Test V2)

### ISSUE THREAD

**Issue by steveyegge** [sourcegraph/jetbrains#1119]
### Description:

Currently the JB extension only supports `workspace/edit` operations from the Agent (i.e. code rewrites) that are in the currently open/edited file.

The protocol supports multi-file operations -- create, rename, and delete. We need to extend `FixupService` to handle these cases as well. We also need to handle the situation where an edit occurs in a different Document/Editor than the one that initiated the fixup task, and switch documents.

### Objectives:

Make sure the LLM can generate new files, delete files, and rename files as part of workspace edits. This enables the Test V2 command

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/sourcegraph/jetbrains/pull/1384
```

### Related Docs:

- [PRD: Your-Title]()

**Comment by steveyegge** [comment]
Installation info:

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 11, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 10
Non-Bundled Plugins:
    com.sourcegraph.jetbrains (6.0-localbuild)

Kotlin: 221-1.6.20-release-285-IJ5080.210

**Comment by taylorsperry** [comment]
Multi-file CRUD operations are only used by the `Test` command in VSC today, so I don't think we need to worry about supporting multi-file updates invoked by the edit command right now. [Context](https://sourcegraph.slack.com/archives/C05AGQYD528/p1712247136260849).

**Comment by kalanchan** [comment]
done in 6.0.0!
