### ISSUE TITLE
bug: Inline Edits -- fix broken concurrent fixups

### ISSUE THREAD

**Issue by steveyegge** [sourcegraph/jetbrains#1120]
### Installation Information

The VS Code extension and protocol both support multiple simultaneous fixups (inline edits) happening within a single document. 

The JB code was originally written to support only one at a time (like Cursor does), and needs a bit more restructuring in order to handle concurrent edits. The main problem is the Document listener(s), which are hardwired right now to a single lens group at a time. We need to fix `FixupSession` and `LensWidgetGroup` to have Document-level listener lists and handle the multiplexing of `workspace/edit` commands properly.

### Describe the bug

- Start a long-running edit command in a file
- While it's running, scroll to another location in the file and start another inline edit

This sequence of operations will usually result in wrong behavior.

### Expected behavior

Expect that concurrent fixups should all complete normally, without interfering with one another. They should also be independently cancelable.

**Comment by steveyegge** [comment]
Installation info:

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 11, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 10
Non-Bundled Plugins:
    com.sourcegraph.jetbrains (6.0-localbuild)

Kotlin: 221-1.6.20-release-285-IJ5080.210

**Comment by steveyegge** [comment]
We've decided to push concurrent edits to post-GA, which means the solution for now will be to simply tell the user that we're still busy with another one. We may be able to use the bubble notification mechanism, but Design should be involved.

**Comment by dominiccooney** [comment]
Concurrent edits are basically working now.

There's an issue with concurrent Smart Apply across files in JetBrains not removing old lenses in [JetBrains: "Accept" and "Reject" buttons become non-clickable when user generate files from "Cody Apply" · Issue #2197 · sourcegraph/jetbrains (github.com)](https://github.com/sourcegraph/jetbrains/issues/2197) but that's specific to Apply AFAIK.
