### ISSUE TITLE
PRD: Cody Client Version Telemetry

### ISSUE THREAD

**Issue by aramaraju** [sourcegraph/jetbrains#1124]
### Description:

As the capabilities of the clients change, it is imperative for admins and Sourcegraph Support/Eng teams to have quick access to what exact Cody client versions are being used. Today, we have the following issues:
1. We only have access to the agent version, which makes it harder for anyone who is not on the JB dev team or Kalan to know  which client version it maps to
2. There have been significant improvements with stability and telemetry that are available in the recent version of the JBs client. However, the account teams are unable to share which user is running a less-than-ideal version of the clients 

In the future, we are expecting to have some form of EoL or 'recommended' version of JB clients for customers to follow. This visibility could also help inform the admin identify any users who are running unrecommended/unsupported versions

### Objectives:

Provide a readily accessible way to access the Client version per customer for account and product teams

### Acceptance Criteria:

- Add a dashboard to the Looker customer dashboard with information on the Client version distribution
- Be able to map the Client version to a user, with the help of the customer

### Design Tasks:

```[tasklist]
### Design Tasks
- [ ] Add a draft title or issue reference here
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] Add a draft title or issue reference here
```

### Related Docs:

- [PRD: Your-Title]()

**Comment by taylorsperry** [comment]
Some [old context](https://sourcegraph.slack.com/archives/C059N5FRYG3/p1705327167887639) on this topic.
