### ISSUE TITLE
bug: pressing UpArrow in multiline message has surprising behavior

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/jetbrains#1134]
### Cody Version

5.4.6-nightly

### IDE Information

```
IntelliJ IDEA 2023.2.4 (Ultimate Edition)
Build #IU-232.10203.10, built on October 24, 2023
Licensed to Sourcegraph / Olaf Geirsson
Subscription is active until May 12, 2024.
Runtime version: 17.0.8.1+7-b1000.32 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6.4
GC: G1 Young Generation, G1 Old Generation
Memory: 16000M
Cores: 10
Metal Rendering is ON
Registry:
    ide.browser.jcef.debug.port=9222
    ide.experimental.ui=true
    scala.erase.compiler.process.jdk.once=false
    eslint.additional.file.extensions=svelte

Non-Bundled Plugins:
    MatlabSupport (0.8.5)
    org.rust.lang (0.4.201.5424-232)
    IdeaVIM (2.7.5)
    com.github.shiraji.ccch (1.0.1)
    com.facebook.ktfmt_idea_plugin (1.1.0.47)
    google-java-format (1.21.0.0)
    com.jetbrains.intellij.code.search.polaris (0.232.1.119)
    org.jetbrains.kotlin (232-1.9.23-release-779-IJ10072.27)
    com.intellij.ml.llm (232.9826)
    com.virtuslab.git-machete (4.2.0)
    com.intellij.lang.jsgraphql (4.0.2)
    dev.blachut.svelte.lang (232.9921.36)
    org.intellij.scala (2023.2.29)
    com.sourcegraph.jetbrains (5.4.6-nightly)

Kotlin: 232-1.9.23-release-779-IJ10072.27
```

### Describe the bug

* Start chat
* Send "Hello"
* Type new multiline message `a\n\nb`
* Press up arrow
* Actual behavior: chat input moves in history to previous "Hello" message

### Expected behavior

I expected the cursor to move up one line in the chat input

**Comment by olafurpg** [comment]
I'm regularly hitting on this bug making it quite annoying to use the chat in JB. I would rather disable the custom up/down arrows than have this buggy behavior. I'm not sure why/when this regressed because I'm pretty sure I tested this thoroughly when we launched it

**Comment by danielmarquespt** [comment]
Related slack thread: https://sourcegraph.slack.com/archives/C05AGQYD528/p1711718880832439

**Comment by olafurpg** [comment]
The regression happened in this PR here @pkukielka https://sourcegraph.com/github.com/sourcegraph/jetbrains/-/commit/88a21694097716fbe53b84e76b3124cb3454af76

Specifically, the `isInHistoryMode` variable was responsible to only enabling this behavior when the text input was empty. This variable got removed in that commit 

https://sourcegraph.com/github.com/sourcegraph/jetbrains/-/commit/88a21694097716fbe53b84e76b3124cb3454af76#diff-91c99de25d8f01dab68bee8fa28fb6f1L80
