### ISSUE TITLE
bug: sending a message to a new chat very quickly results in a duplicated human message

### ISSUE THREAD

**Issue by mkondratek** [sourcegraph/jetbrains#1140]
### Cody Version

f2c43c7207bdb5c0bf9e32e25fc961d990074f98

### IDE Information

**It's a dev run.**

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 10
Non-Bundled Plugins:
    com.sourcegraph.jetbrains (6.0-localbuild)

Kotlin: 221-1.6.20-release-285-IJ5080.210

### Describe the bug

<img width="468" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/19799111/bf49c0e1-91fb-40c9-86c2-ee49ad3d091d">

### Expected behavior

The first human message appears only once. 

### Additional context

The scenario:
1. Switch account
2. Quickly write a message to the chat and send it (in particular, before the llms load)

**Comment by dominiccooney** [comment]
I often get duplicated messages like this, even in the middle of chats:

```
IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Licensed to Sourcegraph / Dominic Cooney
Subscription is active until February 28, 2025.
Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
Kotlin analyzer version: 2.0.0-ij241-276
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.jetbrains.space (241.14494.150)
  google-java-format (1.21.0.0)
  DevKit (241.14494.247)
  io.intellij-sdk-thread-access (2.2.1)
  com.jetbrains.packagesearch.intellij-plugin (241.0.8)
  com.sourcegraph.jetbrains (5.5.5)
Kotlin: 241.14494.240-IJ
```

![Screenshot 2024-04-23 at 20 03 03](https://github.com/sourcegraph/jetbrains/assets/55120/e9dab826-df56-483d-ab88-38cfd785bffc)

![Screenshot 2024-04-23 at 20 04 37](https://github.com/sourcegraph/jetbrains/assets/55120/2b63ac37-d49f-4b56-bf19-2c778230f170)
