### ISSUE TITLE
bug: Inline Edits - replace LensSpinner widget with AnimatedIcon

### ISSUE THREAD

**Issue by steveyegge** [sourcegraph/jetbrains#1142]
### Cody Version

origin/main

### IDE Information

IntelliJ IDEA 2023.3.3 (Ultimate Edition)
Build #IU-233.14015.106, built on January 24, 2024
Licensed to Steve Yegge
Subscription is active until June 24, 2024.
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 10
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  editor.minimap.enabled=true
  markdown.open.vcs.log.link=true
Non-Bundled Plugins:
  com.drinchev.projectlabel (1.3.1)
  com.facebook.ktfmt_idea_plugin (1.1.0.47)
  google-java-format (1.20.0.0)
  DevKit (233.14015.152)
  com.intellij.ml.llm (233.14015.147)
  com.intellij.bigdatatools.core (233.14015.106)
  com.intellij.bigdatatools.binary.files (233.11799.267)
  com.intellij.bigdatatools.rfs (233.14015.106)
  com.intellij.bigdatatools.metastore.core (233.13135.65)
  com.intellij.bigdatatools.flink (233.13135.103)
  com.sourcegraph.jetbrains (5.4.358-nightly)
  com.intellij.bigdatatools.kafka (233.13135.103)
  com.intellij.bigdatatools.spark (233.13135.103)
  com.intellij.bigdatatools.zeppelin (233.13135.65)
  com.intellij.bigdatatools (233.13135.65)
Kotlin: 233.14015.106-IJ

### Describe the bug

The LensSpinner class can most likely be gutted and reimplemented more simply with AnimatedIcon.

### Expected behavior

The user-visible behavior of the spinner widget in the inline code lenses should not change.

**Comment by kalanchan** [comment]
All complete as part of `6.0.0`
