### ISSUE TITLE
Figure out why we aren't picking up remotes for Enterprise users

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#1147]
An enterprise customer had not connected any remote repos (separate topic) but we would expect Cody to autodetect the current project and be able to answer chat questions about that project. This is the behavior in VSC, but doesn't seem to be the case in JB. Why? ([thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1710886472889089))

**Comment by taylorsperry** [comment]
@pkukielka The user I was talking to [shared logs](https://sourcegraph.slack.com/archives/C01U497GASZ/p1711048007898969?thread_ts=1711047171.200559&cid=C01U497GASZ) for debugging purposes.

**Comment by pkukielka** [comment]
IJ also autodetect current repo based on it's git remote and try to add it's remote context.
In this specific case issue seems to be lack of trusted certs.
It is partially [fixed by Chris for MacOs](https://github.com/sourcegraph/cody/pull/3164), we need to follow-up on windows.

**Comment by pkukielka** [comment]
Chris added also win and linux certs support:
https://github.com/sourcegraph/cody/pull/3752
