### ISSUE TITLE
Remove the "index" button in Cody chat *for Enterprise users*

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#1148]
The "index button" in the chat bar doesn't do anything for Enterprise users (since Enterprise doesn't use symf and JB doesn't support NLS). It's confusing and we should remove it.

![Image](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/1d898c8d-2b74-4ca6-9c52-f755d19f7079/f91d5ab4-578e-497d-830a-1d4e6faabd2e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy8xZDg5OGM4ZC0yYjc0LTRjYTYtOWM1Mi1mNzU1ZDE5ZjcwNzkvZjkxZDVhYjQtNTc4ZS00OTdkLTgzMGEtMWQ0ZTZmYWFiZDJlIiwiaWF0IjoxNzE0NDc5ODUyLCJleHAiOjMzMjg1MDM5ODUyfQ.Cy0jmnBMWB43ChLoXusJrTfMTn0zvvliL0O45XNZ9k0)

**Comment by dominiccooney** [comment]
This is fixed in #1308:

![Image](https://github.com/sourcegraph/jetbrains/assets/55120/a3c795ef-2f9c-41ed-8e82-94b7a0cad814)

Note, after #1479 the look will be more compact and detailed.
