### ISSUE TITLE
feedback: Ollama support

### ISSUE THREAD

**Issue by adrienbrault** [sourcegraph/jetbrains#1159]
### Installation Information

N/A

### Share your feedback

https://sourcegraph.com/blog/local-code-completion-with-ollama-and-cody

I would like to use Ollama with Cody for Jetbrains IDEs

**Comment by coltonmccormack** [comment]
Agreed. The only reason I checked out this plugin was due to that article and it doesn't even work on their Jetbrains plugin.

**Comment by ipty** [comment]
I watched some videos about cody but all settings regarding the change of provider settings (to use ollama) are for VS Code.
Is there something i missed or is it still not implemented in the Jetbrains plugin version?

**Comment by dominiccooney** [comment]
There's nothing you're missing. We need to add a way to set the same settings in JetBrains, this simply isn't possible yet. This branch shows a hacky way to get it up: [sourcegraph/jetbrains at dpc/ollama-config (github.com)](https://github.com/sourcegraph/jetbrains/tree/dpc/ollama-config) however I want to make it possible to set these and future settings without having to recompile the plugin, AND have easier ollama setup without having to edit JSON maps anyway.

**Comment by jdorfman** [comment]
@adrienbrault @coltonmccormack @ipty 

Experimental Ollama support is now available: https://sourcegraph.com/blog/cody-jetbrains-6-0-14-release
