### ISSUE TITLE
PRD: Affordances for chat context window limitations

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#1168]
### Description:

The context window for chats is limited, which means that for longer, ongoing chats, Cody can begin to "forget" context and provide poor responses. We can nudge users to limit the number of input tokens ("save space in the context window") by:
1. Encouraging them to start a new chat 
2. Allowing them to "edit" a previous prompt (which replaces the first prompt with the new one)

See the VSC UX ([Loom](https://www.loom.com/share/a6456107fabc4db6aa54154ff436f9ad?sid=1c9b63f6-a13a-4ce6-9352-52e8b1d39d00)): 
- Buttons (with a keyboard shortcut) encourage users to "Start New Chat" or "Edit Last Message"
- The placeholder text describes a subsequent prompt as a "Follow-Up Message"
- There's a "pencil" icon in the chat prompt that allows the user to replace the prompt with a new one
- When a user hits the arrow up key, it triggers an "Edit" of the previous prompt

<img width="635" alt="Screenshot 2024-03-24 at 11 55 18 AM" src="https://github.com/sourcegraph/jetbrains/assets/43555476/3e5cf53e-43a4-4750-8321-9ff54b523908">

### Objectives:

Provide UX that encourages users to limit the number of input tokens in chat so that Cody is more likely to use relevant context when providing a response. 

### Design Tasks:

```[tasklist]
### Design Tasks
- [x] Add a draft title or issue reference here
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] Add a draft title or issue reference here
```

### Related Docs:

- [PRD: Cody JetBrains](https://docs.google.com/document/d/1xPCMN-iQgV0MG4gxhK7eDlYXv8lrgLzhtMZp1NDl_K0/edit#heading=h.zgi67dag77i9)

**Comment by danielmarquespt** [comment]
Design here:

https://www.figma.com/file/m9Yvgv6W3aPRLfXnxgwnEz/JetBrains?type=design&node-id=1176%3A16299&mode=design&t=2iActCm2QoTXY1hi-1

Includes the call out for the shortcuts like VSCode does, and an warning once the context window becomes too small for the whole conversation
