### ISSUE TITLE
feedback: How to use inline edits

### ISSUE THREAD

**Issue by haringsrob** [sourcegraph/jetbrains#1179]
### Installation Information

Inline edits is a feature I look forward to most. It looks like it got recently merged: https://github.com/sourcegraph/jetbrains/pull/440

I am on 5.5.0-nightly

### Share your feedback

I would love to be able to use inline edits.

**Comment by mkondratek** [comment]
Hello @haringsrob 👋 we are happy you track our progress 😃 inline edit work is still in progress - the mentioned PR initialised that work. we are doing our best to provide the most featureful and stable experience 👨‍🔧 Inline Edits should be available within a month
