### ISSUE TITLE
bug: Cody persists chats with no messages

### ISSUE THREAD

**Issue by mkondratek** [sourcegraph/jetbrains#1181]
### Cody Version

5.5.0

### IDE Information

IntelliJ IDEA 2023.3.2 (Ultimate Edition)
Build #IU-233.13135.103, built on December 20, 202
Runtime version: 17.0.9+7-b1087.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 10
Metal Rendering is ON
Registry:
ide.browser.jcef.debug.port=9222
Non-Bundled Plugins:
DevKit (233.13135.104)
com.virtuslab.git-machete (4.2.0)
com.sourcegraph.jetbrains (5.5.0-nightly)
Kotlin: 233.13135.103-IJ

### Describe the bug

`cody_history.xml` contains entries like this:

```
        <chat>
          <accountId value="VXNlcjoxNDIxLOL=" />
          <enhancedContext>
            <enhancedContext>
              <remoteRepositories>
                <list>
                  <remoteRepository>
                    <codebaseName value="github.com/sourcegraph/jetbrains" />
                    <remoteUrl value="github.com/sourcegraph/jetbrains" />
                  </remoteRepository>
                  <remoteRepository>
                    <codebaseName value="github.com/sourcegraph/cody" />
                    <remoteUrl value="https://github.com/sourcegraph/cody" />
                  </remoteRepository>
                  <remoteRepository>
                    <codebaseName value="github.com/sourcegraph/sourcegraph" />
                    <remoteUrl value="github.com/sourcegraph/sourcegraph" />
                  </remoteRepository>
                  <remoteRepository>
                    <codebaseName value="github.com/sourcegraph/docs" />
                    <remoteUrl value="github.com/sourcegraph/docs" />
                  </remoteRepository>
                  <remoteRepository>
                    <codebaseName value="github.com/sourcegraph/about" />
                    <remoteUrl value="github.com/sourcegraph/about" />
                  </remoteRepository>
                </list>
              </remoteRepositories>
            </enhancedContext>
          </enhancedContext>
          <internalId value="3394923c-9518-408c-a3c3-cdc1c7c79c40" />
          <llm>
            <llm>
              <model value="anthropic/claude-2.0" />
              <provider value="Anthropic" />
              <title value="Claude 2.0" />
            </llm>
          </llm>
        </chat>
```

### Expected behavior

Chats with no messages are ignored.

### Additional context

The problem can have two causes (at least):
- llm - we are persisting it at the change 
- enhanced context - we are persisting it at the change 

Maybe we can persist it later - when a message is sent (?).

We can solve it by adding a migration that will remove all chats with empty messages.

**Comment by odisseus** [comment]
Currently (after #1304), the chat with no messages could potentially look like this:
```
<chat>
  <internalId value="123-456-890" />
  <llm>
    <llm>
      <model value="baz" />
      <provider value="foo" />
      <title value="bar" />
    </llm>
  </llm>
  <updatedAt value="2024-01-31T01:06:18.524621" />
  <enhancedContext>
    ...
  </enhancedContext>
</chat>
```

Should we drop this entry if the other fields (such as the enhanced context) are not empty? Can such situation actually arise?

**Comment by mkondratek** [comment]
> Can such situation actually arise?

I guess we can wait some time and review our `cody_history.xml`.

**Comment by odisseus** [comment]
I don't think we can close this ticket. The problem clearly exists, although its impact is rather low.
