### ISSUE TITLE
Multi-repo validation code shouldn't require `/` characters

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#1194]
Prospect kicking off a trial this week isn't able to use multi-repo because their repos don't include `/` characters. This issue won't be relevant once we ship https://github.com/sourcegraph/jetbrains/issues/982, but we need to fix this for them in the meantime. [Thread for context](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1711477931175429).

**Comment by dominiccooney** [comment]
Note, the auto-detecting heuristics won't work in these cases either because of the way `convertGitCloneURLToCodebaseName` works. It will expect `/` and in some cases append `/`. Not applicable to the specific case in the thread because the source repo is not a git repo.
