### ISSUE TITLE
PRD: [Cody Ignore] Admins can specify which repositories Cody can use as context

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#1196]
### Description:

As an enterprise admin, I want to be able to control which repositories in my codebase can be shared by Cody to a third-party LLM provider. 

P0: I want to be able to add a list of repositories that can be _included_ as Cody's context in my site config
P0: I want to be able to add a list of repositories that will be _excluded_ as Cody's context in my site config

### Objectives:

Enable enterprise admins to create include/exclude rules that specify which repos on the enterprise instance Cody can use as context. 

### Acceptance Criteria:

- The site config supports lists of repositories to be included/excluded from Cody's context following RE2 syntax
- If either include or exclude rules are defined, Cody applies these rules to determine which repositories can be used as context in requests to third-party LLMs
- If neither exclude nor include rules are specified, Cody may use content from any repository on the instance in its requests to third-party LLMs
- If both exclude and include rules are specified, the include rules restrict Cody to use content only from the repositories that match specified patterns. Repositories not matching any include patterns will be excluded. 
- Non-admin users cannot override configurations set by the admin.

### Design Tasks:

```[tasklist]
### Design Tasks
- [ ] Add a draft title or issue reference here
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] Add a draft title or issue reference here
```

### Related Docs:

- [Cody Ignore and Cody Allow GA PRD](https://docs.google.com/document/d/10tD8n-5py4XWQD9c7doJB7zIuxa7lwiOkpo2d5NLlnA/edit)
- [RFC 910: Cody Ignore GA Implementation](https://docs.google.com/document/d/1PMeJHvY0ia2nMewFvs4vrFcmDbRDw9kSyljil-K8Pt8/edit)

**Comment by dominiccooney** [comment]
@taylorsperry I'm going to close this because there's no JetBrains specific code for this. I assume @taras-yemets has an issue in the sourcegraph repo for the backend work?

We need an engineering issue like this for interpreting the policy locally, but that should be in sourcegraph/cody.
