### ISSUE TITLE
JetBrains: @-file tagging suggestions doesn't get disappear after deleting "@" symbol

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1205]
### Cody Version

5.5.0

### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  idea.plugin.protoeditor (233.13135.65)
  DevKit (233.14015.152)
  gherkin (233.11799.165)
  cucumber-java (233.11799.196)
  PythonCore (233.14015.106)
  com.sourcegraph.jetbrains (5.5.0)
Kotlin: 233.14015.106-IJ

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your VS Code editor
2. Login to Cody with Free/Pro/Enterprise user
3. Open Cody chat window
4. Type "@" and search for some files from your project
5. Delete the "@" synbol

### Observed behavior:
File suggestions doesn't get dismissed after deleting "@" symbol

### Expected behavior

@-file tagging suggestions should get dismissed when user delete "@" symbol

### Additional context

**Video link:**

https://drive.google.com/file/d/1j78a1keHN97JYWRm0dIKSTVtzc5zNKJJ/view?usp=drive_link

**Comment by taylorsperry** [comment]
Good catch, thanks, @jay-fibi! I can repro this. It looks like if you just type`@` the issue occurs and you have to click the chat input to make the list of files disappear. But if you type anything after the `@` (e.g. `@..`) the behavior is as expected.
