### ISSUE TITLE
PRD: [Cody Ignore] Enterprise users cannot use ignored repos as context for autocomplete

### ISSUE THREAD

**Issue by aramaraju** [sourcegraph/jetbrains#1208]
### Description:

When an enterprise admin has configured Cody to allow/ignore repos:

- Cody should not offer any autocomplete suggestions on any code from those repos
- The code from those repos cannot be used as context for generating autocomplete suggestions in other files
- Users need to have the appropriate visibility that autocomplete suggestions are turned off for such files

As a user on an enterprise instance that has Cody allow/ignore repos configured...
P0: I cannot use Cody's autocomplete on any of the code that has been excluded by my admin 
P1: I am able to quickly discern when Cody autocomplete is not available when I am editing any excluded code  
P2: I see guidance in the UX for how to request that my admin include an excluded repo

### Objectives:

The user is not able to use Cody's autocomplete on any code from the excluded repos and content from these repos is not shared with the LLM

### Acceptance Criteria:

- Users cannot see any Cody autocomplete suggestions on any code that is excluded
- User should not be able to perform autocomplete using the in-line autocomplete action, where the icon should be either disabled or the operation should fail with an error
- User should not be able to perform autocomplete using any keyboard shortcuts
- Code in any excluded repo cannot be used as context for autocomplete suggestions on other files
- The UI informs the user that Cody autocomplete is not available through the IDE toolbar because they are working on an excluded file
- P1: Any new or unsaved files created in the excluded repos must also honor the behavior mentioned above

### Design Tasks:

```[tasklist]
### Design Tasks
- [ ] Add a draft title or issue reference here
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/sourcegraph/cody/issues/3641
- [ ] If #1054 adds a shortcut specifically for Cody autocomplete, add Cody Ignore checks + error UX to that action
- [ ] #1253
- [ ] Update TESTING.md with a Cody Ignore scenario for Autocomplete
- [ ] Update docs to clarify that Cody will only respect ignore for autocomplete (not chats or commands yet)
```

### Related Docs:

- [Cody Ignore and Cody Allow GA PRD](https://docs.google.com/document/d/10tD8n-5py4XWQD9c7doJB7zIuxa7lwiOkpo2d5NLlnA/edit)
- [RFC 910: Cody Ignore GA Implementation](https://docs.google.com/document/d/1PMeJHvY0ia2nMewFvs4vrFcmDbRDw9kSyljil-K8Pt8/edit)
- [VSCode Ticket](https://github.com/sourcegraph/cody/issues/3604)

**Comment by aramaraju** [comment]
@kalanchan @taylorsperry @dominiccooney would love your review on this. Please let me know if there are other questions that I could help answer

**Comment by dominiccooney** [comment]
@aramaraju thanks, this is helpful. Not sure what the screenshot is communicating. IDEs have multiple autocomplete providers, so when Cody autocomplete is not enabled, those other providers will still appear.

**Comment by aramaraju** [comment]
The screenshot show the Cody Autocomplete option I added to the toolbar, but yes the other autcomplete providers shouldn't be affected. I removed the screenshot to avoid this confusion.

**Comment by dominiccooney** [comment]
Reviewed the extension autocomplete code and believe, if we fix isCodyIgnoredFile, then autocomplete will be suppressed for ignored files. There's no "extra" work there.

**Comment by kalanchan** [comment]
All complete as part of `6.0.0`
