### ISSUE TITLE
PRD: [Cody Ignore] Enterprise users cannot use ignored repos as context for Commands

### ISSUE THREAD

**Issue by aramaraju** [sourcegraph/jetbrains#1209]
### Description:

When an enterprise admin has configured Cody to allow/ignore repos, Cody commands, both built-in and custom, must not be available to the user

As a user on an enterprise instance that has Cody allow/ignore repos configured...
P0: I cannot run any Cody commands, both built-in and custom, on any excluded code
P1: I am able to understand that I cannot use commands because the code has been excluded by my administrator
P2: I see guidance in the UX for how to request that my admin include an excluded repo

### Objectives:

Cody does not send any code from excluded repos to the LLM when a user is using Cody's commands feature.

### Acceptance Criteria:

- When the user selects content in an excluded file and attempts to perform a built-in command operation using the right-click menu, they should not be able to complete the operation 
- When the user selects content in an excluded file and attempts to perform a built-in command using the in-line menu, they should not be able to complete the operation
- An appropriate notification is provided saying that these operations cannot be completed because the repo is excluded

### Design Tasks:

```[tasklist]
### Design Tasks
- [ ] Add a draft title or issue reference here
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] Add a draft title or issue reference here
```

### Related Docs:

[Cody Ignore and Cody Allow GA PRD](https://docs.google.com/document/d/10tD8n-5py4XWQD9c7doJB7zIuxa7lwiOkpo2d5NLlnA/edit)
[RFC 910: Cody Ignore GA Implementation](https://docs.google.com/document/d/1PMeJHvY0ia2nMewFvs4vrFcmDbRDw9kSyljil-K8Pt8/edit)

**Comment by aramaraju** [comment]
@taylorsperry Could use some help here as I am not completely clear on the different ways commands can be triggered on JBs? 

Additionally, I think it should be an UX decision on whether the operation should be disabled or the operation should run and have an error saying it cannot be completed. I'm fine with either interaction personally (the latter is easier for me)

**Comment by dominiccooney** [comment]
@aramaraju let's break this up by Edit, Document, Generate Unit Test, Ask Cody to Fix, and Custom Commands because we need to track all of those in detail. (Note, no Custom Commands in JetBrains yet.)

> I am not completely clear on the different ways commands can be triggered on JBs?

One of four ways:

Through a context menu:

![Screenshot 2024-03-28 at 17 03 53](https://github.com/sourcegraph/jetbrains/assets/55120/95ba1a41-eba1-404c-aba7-6ccd22c72bd0)

Sidebar menu:

![Screenshot 2024-03-28 at 17 05 02](https://github.com/sourcegraph/jetbrains/assets/55120/a1a6353f-d378-4888-9549-693eecef7980)

Keyboard shortcut

Or command palette:

![Screenshot 2024-03-28 at 17 06 34](https://github.com/sourcegraph/jetbrains/assets/55120/b9d96539-b722-4d92-a472-c6fba26dd421)

> Additionally, I think it should be an UX decision on whether the operation should be disabled or the operation should run and have an error saying it cannot be completed.

+1. Part of why I wanted this issue broken down in detail is so I can map @toolmantim 's design guidance against each item, then go work out what that will take to build.

**Comment by dominiccooney** [comment]
@aramaraju, @taylorsperry: We should polish this specific issue a bit.

- Is the "built-in" part of this is now handled by #1238, #1239, #1240, #1241, #1242?
- Do we have a roll-up tracking issue for all of the Cody Ignore work/PRD criteria?
- Do we need an issue for custom commands? This issue could be focused on custom commands specifically. (What are the plans/timing for adding custom commands to the JetBrains plug-in?)

**Comment by aramaraju** [comment]
@dominiccooney - Yes, I created those additional broken down items for the built-in commands as requested. I'll let @kalanchan chime in on an 'uber' issue for bucketing everything if that helps. 

For custom commands, I agree that if there is a ticket for custom commands (my understanding is that it is not in GA scope based on the [PRD](https://docs.google.com/document/d/1xPCMN-iQgV0MG4gxhK7eDlYXv8lrgLzhtMZp1NDl_K0/edit#bookmark=id.ec6sbvjzynq4)), we should add the behavior for Cody Ignore under that.

**Comment by kalanchan** [comment]
closing this in favour of #1238 #1239 #1240 #1241 #1242
