### ISSUE TITLE
bug: Switching accounts does not switch chats, context repos

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/jetbrains#1210]
### Cody Version

Main b33ee8da1a58527560ea9b05a5976e11421ccfd8

### IDE Information

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 12
Non-Bundled Plugins:
    com.sourcegraph.jetbrains (6.0-localbuild)

Kotlin: 221-1.6.20-release-285-IJ5080.210

### Describe the bug

In VSCode, the chats and chat history are related to the signed-in account.

In JetBrains, when I switch accounts, I'm still looking at the same chat. Repos selected from one instance still appear in the context list, but those repos won't exist/may have different IDs/etc. on another instance.

Loom demonstrating: https://www.loom.com/share/02a4773c4ee84782966696e9e36e5928?sid=8bb32b22-2b1b-4fae-b919-4ee1cb2baba2

### Expected behavior

When I switch accounts, I should get chat history and chosen repos related to the signed-in account.

### Additional context

VSCode also makes it much easier to see what account you're signed in to, and whether you're on the pro plan. This is the first thing you see when you click "Account" in VSCode:

![Screenshot 2024-03-28 at 15 16 55](https://github.com/sourcegraph/jetbrains/assets/55120/e95a11ef-6168-408d-b99d-e469dde6ee8b)

**Comment by taylorsperry** [comment]
I'm fairly certain this was the behavior previously (chat history and context were tied to the account). @pkukielka @mkondratek could something have changed this recently?

**Comment by mkondratek** [comment]
I reviewed the video (thanks Dominic for attaching it) and the code. I see the problem with the enhanced context. We persist it on a "project" level instead of "project-account" level. The video does not show the problem with chats themselves (and I did not observe that).

**Comment by odisseus** [comment]
I wonder if it is possible to create a separate instance of `HistoryService` for each account, or, failing that, to store the chat history of each account in a separate file.

**Comment by odisseus** [comment]
Fixed by #1304.
