### ISSUE TITLE
JetBrains baseline v2 VSC compatibility

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#1212]
### Description:

We need to be able to measure the key actions that a user takes to help us understand what's working and what's not. Some of these events simply need to be updated/verified, while others will be brand new.

❗Guidance from Data & Analytics is that we should be implementing _v2 telemetry_

### Objectives:

Enable visibility into feature usage. 

### Acceptance Criteria:

P0s are events that we're logging in VSC today; P1s are additional requests. They are: 

| Priority | Event | Status |
|----|-------|-------------|
| P0 | Install / uninstall | Update |
| P0 | Auth | Update |
| P0 | Log in / log out | Update | 
| P0 | Send a chat message | Validate |
| P0 | Chat response includes code | ✅ |
| P0 | Use pencil icon to copy code from a chat | New |
| P0 | Use "Insert at cursor" to copy from a chat | New |
| P0 | Use keyboard to copy code from a chat | New |
| P0 | Use keyboard to paste code from a chat | New |
| P0 | Edit code in the chat prompt | New |
| P1 | Export chat history | New |
| P1 | Open the multi-repo selector | New |
| P1 | Add repos to the multi-repo selector | New |
| P1 | Open a historical chat | New | 
| P0 | @ mention a file in chat | Validate |
| P1 | Navigate to a file in a chat response | New |
| P0 | Execute an Explain command | ✅ |
| P0 | Execute a Smell command | ✅ |
| P0 | Click on a code lens to accept, cancel, retry, or view diff | New |
| P0 | Execute a Document command | New |
| P0 | Execute a Test command | New |
| P0 | Execute an Edit command | New |
| P0 | Select an input model when executing Edit | New |
| P0 | Select a range when executing Edit | New |
| P0 | Ask Cody to Fix | New |
| P0 | Completions | ✅? |

### Design Tasks:

```[tasklist]
### Design Tasks
- [ ] Add a draft title or issue reference here
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/sourcegraph/jetbrains/issues/43
- [ ] https://github.com/sourcegraph/jetbrains/issues/1213
- [ ] https://github.com/sourcegraph/jetbrains/issues/1214
- [ ] https://github.com/sourcegraph/jetbrains/issues/1215
- [ ] https://github.com/sourcegraph/jetbrains/issues/1216
- [ ] https://github.com/sourcegraph/jetbrains/issues/1217
- [ ] https://github.com/sourcegraph/jetbrains/issues/1226
- [ ] https://github.com/sourcegraph/jetbrains/issues/1225
- [ ] https://github.com/sourcegraph/jetbrains/issues/1218
- [ ] https://github.com/sourcegraph/jetbrains/issues/1224
- [ ] https://github.com/sourcegraph/jetbrains/issues/1219
- [ ] https://github.com/sourcegraph/jetbrains/issues/1220
- [ ] https://github.com/sourcegraph/jetbrains/issues/1221
- [ ] https://github.com/sourcegraph/jetbrains/issues/1222
- [ ] https://github.com/sourcegraph/jetbrains/issues/1223
- [ ] https://github.com/sourcegraph/jetbrains/issues/1124
- [ ] https://github.com/sourcegraph/jetbrains/issues/1494
```

### Related Docs:

- [PRD: Cody JetBrains](https://docs.google.com/document/d/1xPCMN-iQgV0MG4gxhK7eDlYXv8lrgLzhtMZp1NDl_K0/edit)
- [Cody Event Telemetry](https://docs.google.com/spreadsheets/d/1bidMG9WYdpCmiYez9J4qRkhEZafZ-yNJBpSgw4rGeKc/edit#gid=1695201597)

**Comment by kalanchan** [comment]
related to [#1124](https://github.com/sourcegraph/jetbrains/issues/1124)
