### ISSUE TITLE
P0: Edit command

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#1222]
We need a way to capture usage of the Edit command and a "CAR equivalent" of generated code accepted. The way this is tracked in VSC is with the feature `cody.command.edit` and eventName `cody.command.edit:executed`.

**Comment by kalanchan** [comment]
@daniel.marques could you update and confirm the telemetry events you want to see?

**Comment by danielmarquespt** [comment]
Roughly:

* When an Edit / Test / Documentation is generated
* When an Edit / Test / Documentation is accepted
* When a Edit and Retry is triggered
* When a user clicks Show diff
* Time it takes to generate Edit / Test / Documentation
