### ISSUE TITLE
JetBrains: "20240229" added in LLM name for Enterprise users.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1235]
### Cody Version

v5.5.1-nightly

### IDE Information

PyCharm 2023.3.4 (Community Edition)
Build #PC-233.14475.56, built on February 26, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (5.5.1-nightly)

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB PyCharm editor
2. Login to Cody with Enterprise user
3. Open Cody chat window and check the LLM name

### Observed behavior:
There is "20240229" added in LLM name.

### Expected behavior

LLM name should be correct as "Claude 3 Sonnet by Anthropic"

### Additional context

**Screenshot:**

![Enterprise_Wrong_LLM_name](https://github.com/sourcegraph/jetbrains/assets/158482423/84999436-9e75-4f99-a322-1d644b9dd85a)

**Comment by pkukielka** [comment]
@Daniel Marques
That name comes from the sever, we are using it as is.
Do we want to just hide LLM selection from the enterprise users?
