### ISSUE TITLE
JetBrains: User is unable to run command with any other LLM.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1236]
### Cody Version

v5.5.1-nightly

### IDE Information

PyCharm 2023.3.4 (Community Edition)
Build #PC-233.14475.56, built on February 26, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (5.5.1-nightly)

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB PyCharm editor
2. Login to Cody with Pro user
3. Open any source code file
4. Open Cody chat window and change LLM to some other LLM i.e., Claude 3 Haiku
5. Go to "Commands" and select "Explain Code"

### Observed behavior:
Command will not be performed with Claude 3 Haiku but with default LLM

### Expected behavior

"Explain Code" command should be performed with selected LLM and not default one.

### Additional context

**Video links:**

on 5.5.1-nightly - https://drive.google.com/file/d/1S3eJGSU-q4_VJXT2e9mcqAfQ7RgD4jeo/view?usp=drive_link
on 5.5.0-nightly - https://drive.google.com/file/d/1iK3jNPllPmzZUZF9vk5wFlaYJdmcie9o/view?usp=drive_link

**Comment by pkukielka** [comment]
@daniel Marques
Before we introduced saving the last selected LLM state we were always using default LLM for the commands.
Do we want to keep doing that or do we want to use the last model which was selected for the chat?

**Comment by pkukielka** [comment]
@taylorsperry currently agent API does not allow us to specify LLM model.
It is not a new bug, it was always like that.
If we want to change that a bit of work will be needed on both JB and Cody side.
Does VSC even support switching models for commands?

Either way in the light of the above please let me know if we still think this one is a high priority.

**Comment by kalanchan** [comment]
Going to close this for now, VSC only supports model switching for edit commands which we also have. 

if anyone disagrees feel free to re-open
