### ISSUE TITLE
PRD: [Cody Ignore] Enterprise users cannot use ignored repos as context for Edit Command

### ISSUE THREAD

**Issue by aramaraju** [sourcegraph/jetbrains#1238]
### Description:

When an enterprise admin has configured Cody to allow/ignore repos, Cody Edit command must not be available to the user

As a user on an enterprise instance that has Cody allow/ignore repos configured...
P0: I cannot run the Cody Edit command on any excluded code
P1: I am able to understand that I cannot use the command because the code has been excluded by my administrator
P2: I see guidance in the UX for how to request that my admin include an excluded repo

### Objectives:

Cody does not send any code from excluded repos to the LLM when a user is using Cody's Edit command feature.

### Acceptance Criteria:

- When the user selects content in an excluded file and attempts to perform a Edit command operation using the context menu, they should not be able to complete the operation 
![image](https://github.com/sourcegraph/jetbrains/assets/51247042/a4117c37-9e74-4b55-87ae-31b22bb321bf)
- When the user selects content in an excluded file and attempts to perform a Edit command operation using the sidebar menu, they should not be able to complete the operation 
![image](https://github.com/sourcegraph/jetbrains/assets/51247042/69e6f8e5-1182-4854-8df5-c4f475f2010c)
- When the user selects content in an excluded file and attempts to perform a Edit command operation using a keyboard shortcut, they should not be able to complete the operation 
- When the user selects content in an excluded file and attempts to perform a Edit command operation using the command palette, they should not be able to complete the operation 
![image](https://github.com/sourcegraph/jetbrains/assets/51247042/6ca4d3c7-77fb-479a-9460-a1bcfca723e5)
- An appropriate notification is provided saying that these operations cannot be completed because the repo is excluded

### Design Tasks:

```[tasklist]
### Design Tasks
- [ ] Add a draft title or issue reference here
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/sourcegraph/jetbrains/issues/1254
- [ ] https://github.com/sourcegraph/cody/issues/3641
- [ ] When Edit is covered in TESTING.md, expand to cover Cody Ignore cases
- [ ] https://github.com/sourcegraph/docs/issues/222
```

### Related Docs:

[Cody Ignore and Cody Allow GA PRD](https://docs.google.com/document/d/10tD8n-5py4XWQD9c7doJB7zIuxa7lwiOkpo2d5NLlnA/edit)
[RFC 910: Cody Ignore GA Implementation](https://docs.google.com/document/d/1PMeJHvY0ia2nMewFvs4vrFcmDbRDw9kSyljil-K8Pt8/edit)
[Related VSCode ticket](https://github.com/sourcegraph/cody/issues/3607)

**Comment by kalanchan** [comment]
All complete as part of `6.0.0`
