### ISSUE TITLE
bug: JsonNull exception from plugin

### ISSUE THREAD

**Issue by sqs** [sourcegraph/jetbrains#1244]
### Cody Version

5.5.0

### IDE Information

WebStorm

### Describe the bug

<img width="1245" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/1976/8adf9a50-ae49-457f-a357-7dc4822aeafe">

### Expected behavior

No exception

### Additional context

https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1711743476327019

**Comment by sqs** [comment]
reported via @hopkinscl

**Comment by taylorsperry** [comment]
Also reported here https://github.com/sourcegraph/jetbrains/issues/1183

**Comment by pkukielka** [comment]
Should already by fixed in 5.5.2:
https://github.com/sourcegraph/jetbrains/pull/1211
