### ISSUE TITLE
bug: Telemetry 302 responses crash Agent when debugging

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/jetbrains#1246]
### Cody Version

Agent: a0056f25730b06a250ba2b667f04111bb7666ae8 Extension: 9d17abf6327ae88a8ba8b9bbf9179eb5b3ad328d

### IDE Information

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 12
Non-Bundled Plugins:
    com.sourcegraph.jetbrains (6.0-localbuild)

Kotlin: 221-1.6.20-release-285-IJ5080.210

### Describe the bug

- With sourcegraph/cody in VSCode and run agent:debug
- With sourcegraph/jetbrains in IntelliJ with run Gradle task runIde and this environment: `CODY_AGENT_DEBUG_PORT=3113;CODY_AGENT_DEBUG_REMOTE=true;CODY_JETBRAINS_FEATURES=cody.feature.inline-edits=true`

After repeated restarts, eventually fails to connect to agent with "Failed to start Cody agent" and an underlying "connection refused" stack trace.

Agent output contains this:

```
{"stack":"OTLPExporterError: Found\n    at IncomingMessage.<anonymous> (/Users/dpc/projects/cody/node_modules/.pnpm/@opentelemetry+otlp-exporter-base@0.45.1_@opentelemetry+api@1.7.0/node_modules/@opentelemetry/otlp-exporter-base/src/platform/node/util.ts:131:27)\n    at IncomingMessage.emit (node:events:525:35)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","message":"Found","name":"OTLPExporterError","code":"302"}
graphql.fetch.CodyConfigFeaturesResponse - 257.552625ms
{"stack":"OTLPExporterError: Found\n    at IncomingMessage.<anonymous> (/Users/dpc/projects/cody/node_modules/.pnpm/@opentelemetry+otlp-exporter-base@0.45.1_@opentelemetry+api@1.7.0/node_modules/@opentelemetry/otlp-exporter-base/src/platform/node/util.ts:131:27)\n    at IncomingMessage.emit (node:events:525:35)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","message":"Found","name":"OTLPExporterError","code":"302"}
```

### Expected behavior

Don't crash with repeated attaches.

Looks like telemetry exporter gets a 302 and things start to go south for Agent.

**Comment by taylorsperry** [comment]
Thank you for catching this, @dominiccooney !

**Comment by dominiccooney** [comment]
I suspect this is working as intended, Agent has an "exit" message and closing the IntelliJ window closes the agent. It is annoying when debugging though! Closing for now, this is a minor quality of life improvement we could make later.
