### ISSUE TITLE
[Cody Ignore] Add a banner to editors with Cody Ignored files open

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/jetbrains#1253]
Typical in JetBrains to display a warning [Banner](https://jetbrains.design/intellij/controls/banner/) on files which "informs the user about the state of a specific context in the project. ... to suggest actions that can impact the user’s workflow."

VSCode uses the status bar for the same purpose, see vscode/src/services/StatusBar.ts

[API docs entrypoint.](https://plugins.jetbrains.com/docs/intellij/notifications.html#editor-banner)

**Comment by dominiccooney** [comment]
@danielmarquespt I welcome your input here.

My thinking here is that:
- The Cody Ignore PRD wants to communicate *why* a file is ignored, command disabled, etc. This is a good principle, it will cut down on people cutting and pasting from files their administrator intended to "protect."
- The communication happens with an error message. This is good. We could disable/take away a menu item, but that's confusing because there's no explanation why. The menu item label isn't the place to explain why a command is disabled—it should be short—and in some places it is hard to make those labels dynamic anyway. And you may be using a shortcut anyway and never *see* the menu item.
- But it is annoying to invoke a command, only to get an error message.
- Thus we should use a banner, so you know what's going on, and the meaning of the banner is reinforced if you do go into the commands through shortcut muscle memory or whatever.

**Comment by danielmarquespt** [comment]
The UX for this is a bit different now (maybe simpler?)

It is covered on this discussion: https://sourcegraph.slack.com/archives/C05AGQYD528/p1712864303221559

And the figma file lives here: https://www.figma.com/file/m9Yvgv6W3aPRLfXnxgwnEz/JetBrains?type=design&node-id=1181-17006&mode=design
