### ISSUE TITLE
JetBrains: Guardrails is not available for Enterprise user.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1257]
### Cody Version

v5.5.1-nightly

### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  idea.plugin.protoeditor (233.13135.65)
  DevKit (233.14015.152)
  gherkin (233.11799.165)
  cucumber-java (233.11799.196)
  PythonCore (233.14015.106)
  com.sourcegraph.jetbrains (5.5.1-nightly)
Kotlin: 233.14015.106-IJ

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB PyCharm editor
2. Login to Cody with Enterprise user
3. Open any source code file
4. Right click and go to "Cody > Generate Test" 
5. Check the code snippet from Cody response

### Observed behavior:
Only "Insert at Cursor" and "Cody" buttons are available and there is no indication for Guardrail.

### Expected behavior

Guardrail should appear for generate code snippet from Cody.

### Additional context

**Video link:**

https://drive.google.com/file/d/1KSjLJ7PBz0RJ4QNQqFKjCgO5GuHDYmRf/view?usp=drive_link

**Comment by mkondratek** [comment]
What sourcegraph instance is the account you are logged-in on? I tested it and it works for me on `sg02` (however it fails on `sourcegraph.sourcegraph.com`)

<img width="493" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/19799111/a910dfcc-b957-43db-b85c-d791dce756cc">

**Comment by cbart** [comment]
Cannot reproduce on jetbrains 5.2.2 and sg02 with guardrails verified to be enabled (by graphQL)

To verify guardrails is enabled:

1. User menu in top-right corner
2. Settings
3. Other actions > API console

Execute the following graphQL (check and run example search):

```graphql
query Attribution {
  snippetAttribution(snippet: "linters:\n  disable-all: true\n  enable:\n    - errcheck\n    - godot\n    - gosimple\n    - govet\n    - ineffassign\n    - staticcheck\n    - typecheck\n    - unused", first: 4) {
    nodes {
      repositoryName
    }
    snippetThreshold {
      linesLowerBound
      searchPerformed
    }
  }
  site {
    codyConfigFeatures {
      attribution
    }
  }
}
```

**Comment by cbart** [comment]
Loom: https://www.loom.com/share/de459c2b29354aa7a71e7a024e58d474?sid=cc1746df-58ee-42ee-a1a3-d4ac22004216

**Comment by cbart** [comment]
Tested using IntelliJ IDEA 2023.2 Build #IC-232.8660.185, built on July 26, 2023
Plugin version 5.2.2 (latest update as of today)

**Comment by jay-fibi** [comment]
@mkondratek Here are the updated steps,

1. Login to Cody with Free/Pro user.
2. Open any source code file and run a command "Explain Code"
3. Let the Cody respond
4. Switch account to Enterprise user
5. Run the command "Generate Test" for the code snippet
6. Check the code block from Cody response

**Observed behavior:**
Guardrails is missing with Enterprise user

Attaching `cody-agent-trace.json` file for your reference,
[cody-agent-trace1.json](https://github.com/sourcegraph/jetbrains/files/14922980/cody-agent-trace1.json)


Restart the IDE and perform step-5 again. You will be able to see the Guardrails now.

**Video link:**
https://drive.google.com/file/d/1OrZMeLkQJUlTNZQmfZnnDMRnyoiwjTcF/view?usp=drive_link

**Comment by mkondratek** [comment]
Thanks Jay. I suggest we implement a test in the agent:

1. having dotcom account
2. send a message
3. `extensionConfiguration/didChange` and switch to enterprise account
4. send a message
5.  ensure `setConfigFeatures` has a proper value 

Do the same the other way (enterprise -> dotcom change).

We will need an enterprise testing account for that probably.

**Comment by dominiccooney** [comment]
Possible dup of #1483  CC @kalanchan 

@jay-fibi can you confirm which instance you were using for testing?

**Comment by jay-fibi** [comment]
@kalanchan This issue was occurring due to switching of accounts from Free/Pro to Enterprise. This is an old issue and I was using sg02 at that time. 
#1483 is a new issue and I am on sg04 instance.
