### ISSUE TITLE
Fix the Cody icon in edit/document code lenses

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#1266]
Looks low res

![Image](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/c187dc77-4cca-4128-a154-eca8850a5382/98921f2b-f392-45f4-8a81-c8bcf2298c54?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy9jMTg3ZGM3Ny00Y2NhLTQxMjgtYTE1NC1lY2E4ODUwYTUzODIvOTg5MjFmMmItZjM5Mi00NWY0LThhODEtYzhiY2YyMjk4YzU0IiwiaWF0IjoxNzE3NDUxOTgyLCJleHAiOjMzMjg4MDExOTgyfQ.mBKp3MwOcrzLlLZiCnm9BH2HP70QIAvxar0jrtmao-I)

**Comment by kalanchan** [comment]
fixed in latest
