### ISSUE TITLE
Polish code lens functionality

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#1269]
* After executing the “Document” command and clicking “Edit,” I asked Cody to condense the documentation to 1 sentence. Instead of replacing the code that was generated initially, Cody added an additional second set of documentation (which does apply the edit)

![Image](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/391508c9-5b39-442a-9d53-1a63e3fc249c/f4ae5974-49e2-4961-b5db-1595a04962fe?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy8zOTE1MDhjOS01YjM5LTQ0MmEtOWQ1My0xYTYzZTNmYzI0OWMvZjRhZTU5NzQtNDllMi00OTYxLWI1ZGItMTU5NWEwNDk2MmZlIiwiaWF0IjoxNzE3NDM3NjM3LCJleHAiOjMzMjg3OTk3NjM3fQ.cJpXKvP1hIiR5cLTgAQ2RKxz-SvzJAM-u7gQ0J3ZZbY)

* For the above screenshot, I clicked “Undo” for the one-sentence version of documentation and it worked; when I clicked “Undo” for the first, the code lens for the longer version of the documentation went away, but the documentation itself didn’t.

![Image](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/ec2d2d48-c632-4a12-8fc6-5686b3b156f6/15c46202-fe61-4fe7-bb30-3abee29517ad?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy9lYzJkMmQ0OC1jNjMyLTRhMTItOGZjNi01Njg2YjNiMTU2ZjYvMTVjNDYyMDItZmU2MS00ZmU3LWJiMzAtM2FiZWUyOTUxN2FkIiwiaWF0IjoxNzE3NDM3NjM3LCJleHAiOjMzMjg3OTk3NjM3fQ.3FabF7gLN2VfZpBtwphY5aUJP9x6BBQy7_diLi_dtHs)

* When I switched from my Pro account to my enterprise account, hitting ⬆️still “remembered” my history from when I was signed in as Pro. These histories should probably be contained to the account (the way chat histories are).
* When I executed the “Document” command and clicked “Edit & Retry”, I think the default model was Claude 2.0. This should be Claude 3 Sonnet for Free/Pro users going forward.
* When I switch the model, I can’t hit “OK” until I add instructions. I entered “retry” as my instructions and hit “OK.” New documentation replaced the old documentation, but there are two rows of code lenses.

![Image](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/130a982c-d4a1-4ad4-ab2f-4e6b3bd613c3/7a432c56-7846-43c1-a4f1-5288edbb8a95?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy8xMzBhOTgyYy1kNGExLTRhZDQtYWIyZi00ZTZiM2JkNjEzYzMvN2E0MzJjNTYtNzg0Ni00M2MxLWE0ZjEtNTI4OGVkYmI4YTk1IiwiaWF0IjoxNzE3NDM3NjM3LCJleHAiOjMzMjg3OTk3NjM3fQ.\_sj1uSO-ytPysFak_XIc4jBh4lhTtd5A9LIILsJRTpw)

* When I use the keyboard shortcut command+z instead of clicking “Edit & Retry” the generated code disappears, the code lens stays, but no edit dialog appears. (This is covered in [#1110](https://github.com/sourcegraph/jetbrains/issues/1110))

![Image](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/b2e9c819-a5c2-4365-b45b-62aca37a0e5e/7a470bf9-a443-4ecc-8b7f-b47cf81c9aa0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy9iMmU5YzgxOS1hNWMyLTQzNjUtYjQ1Yi02MmFjYTM3YTBlNWUvN2E0NzBiZjktYTQ0My00ZWNjLThiN2YtYjQ3Y2Y4MWM5YWEwIiwiaWF0IjoxNzE3NDM3NjM3LCJleHAiOjMzMjg3OTk3NjM3fQ.6UZuod2_BPGv0CR4DcxUDgCz0FeUsosTWrZiNHCk6Ww)

**Comment by kalanchan** [comment]
@taylorsperry ready for review

**Comment by taylorsperry** [comment]
A lot of this has been resolved. I'll open new issues for follow-ups.
