### ISSUE TITLE
Polish the edit command

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#1270]
[Loom](https://www.loom.com/share/af91771f4f2f41f1a173956f9538806e?sid=f4183c4d-e32c-484e-aced-5df917aff88f) Two pretty big screen jumps, but applied the edit successfully and the “Cody is working” lens is in the right spot

[Loom](https://www.loom.com/share/4563412d32b946648e4aee0fe984d9e4) “Cody is working” code lens is (inconsistently) in the wrong spot

**Comment by mkondratek** [comment]
Related: [bug: [Inline Edits] NPE from LLM dropdown (probably edit request sent before initialising the dropdown)](https://github.com/sourcegraph/jetbrains/issues/1303#top)
