### ISSUE TITLE
JetBrains: Cody icon is missing from context menu in IntelliJ IDEA editor.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1273]
### Cody Version

v5.5.1-nightly

### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
idea.plugin.protoeditor (233.13135.65)
DevKit (233.14015.152)
gherkin (233.11799.165)
cucumber-java (233.11799.196)
PythonCore (233.14015.106)
com.sourcegraph.jetbrains (5.5.1-nightly)
Kotlin: 233.14015.106-IJ

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB PyCharm & IntelliJ IDEA editors
2. Login to Cody with Free/Pro/Enterprise user
3. Open any source code and right click to open Context menu
4. Check the "Cody" menu item

### Observed behavior:
Cody icon is missing in the context menu for IntelliJ IDEA ediror.

### Expected behavior

Cody icon should appear correctly.

### Additional context

**Screenshots:**

IntelliJ IDEA : 
<img width="598" alt="Screenshot 2024-04-03 at 1 05 43 AM" src="https://github.com/sourcegraph/jetbrains/assets/158482423/66653ca4-0afa-4f0a-b8e5-7205a01c4900">

PyCharm: 
<img width="687" alt="Screenshot 2024-04-03 at 1 06 53 AM" src="https://github.com/sourcegraph/jetbrains/assets/158482423/e4af9105-65d4-4e9b-8ac1-f6248e77d653">

**Comment by mkondratek** [comment]
The actual difference is probably the old vs the new UI.

**Comment by pkukielka** [comment]
Most likely, but still other icons are showing properly, so we need to fix it regardless.
It just does not seem to be a regression.

**Comment by mkondratek** [comment]
It is something from the newer versions of IntelliJ. Note that it affects all action groups e.g. `Diagrams`:

<img width="566" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/19799111/e7c142c0-00da-4c1c-9d69-48e8e6464f43">

(previously there was an icon there too)
