### ISSUE TITLE
Inline Edits: Add error handling

### ISSUE THREAD

**Issue by mkondratek** [sourcegraph/jetbrains#1300]
In particular, we should handle the rate limit error. 

The other possible errors should be identified and handled if needed.

**Comment by mkondratek** [comment]
@taylorsperry, FYI - IMHO we will need some basic error handling at least if we want to enable inline edits.

**Comment by kalanchan** [comment]
From triaging:
@mkondratek  - as a PLG user, if you run into a rate limit, the error is present in the logs but not handled in the UI
@dominiccooney - does this only affect PLG users, do enterprise have limits
@mkondratek - I believe there are limits for both

**Comment by taylorsperry** [comment]
@steveyegge could you also take a look at [this](https://github.com/sourcegraph/jetbrains/issues/1519) and [this](https://github.com/sourcegraph/jetbrains/issues/1515) report while you're working on this? We seem to get a lot of these and it doesn't sound like it actually interrupts normal use of Cody, but users are spammed anyway.
