### ISSUE TITLE
bug: No indicator during autocomplete (Cody icon not spinning)

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/jetbrains#1309]
### Cody Version

5.5.2 and (5.5.5-nightly)

### IDE Information

IntelliJ IDEA 2023.2 (Community Edition)
Build #IC-232.8660.185, built on July 26, 2023
Runtime version: 17.0.7+7-b1000.6 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.sourcegraph.jetbrains (5.5.5-nightly)

Kotlin: 232-1.9.0-IJ8660.185

### Describe the bug

No visual indicator when auto complete is in progress.  

### Expected behavior

The cody icon used to spin to indicate that autocomplete was in progress.  This no longer happens

**Comment by pkukielka** [comment]
@chwarwick You will be happy to hear I fixed it already few days ago ;)
https://github.com/sourcegraph/jetbrains/pull/1294
