### ISSUE TITLE
JetBrains: Chat textbox position changed when user add multi line message and remove it

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1310]
### Cody Version

v5.5.5-nightly

### IDE Information

IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  PythonCore (233.14475.9)
  com.soywiz.korge.korge-intellij-plugin (4.0.4)
  com.sourcegraph.jetbrains (5.5.5-nightly)
Kotlin: 233.14475.28-IJ

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ IDEA editor
2. Login to Cody with Free/Pro/Enterprise user
3. Copy a multi line message and paste it inside Cody message textbox
4. Select whole message and delete it

### Observed behavior:
Cody message textbox position changed after deleting the message content

### Expected behavior

Cody textbox position should be fixed.

### Additional context

**Video link:**

https://drive.google.com/file/d/1jGkM5EHKVPcUi9UiL5T8LqLpM_Uh2nWU/view?usp=drive_link

**Comment by taylorsperry** [comment]
Good catch, thank you, @jay-fibi ! Marking as a P2 (papercut).
