### ISSUE TITLE
[User Testing] Add Gotit tooltips

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/jetbrains#1319]
User Testing results:

https://docs.google.com/document/d/1opkHzO3ZZUHs591ajjy6HYDkouFEI1O7kJzdqVYhEfQ/edit

In order to fix some of the issues found, we should include ["Got it tooltips"](https://jetbrains.design/intellij/controls/got_it_tooltip/) for:

- [ ] On the editor: First time user gets an Autocomplete

`To accept a Cody autocomplete, hit TAB`

- [ ] On context area: First time user opens the sidebar (Enterprise Only)

`Set the context for this discussion by selecting up to 10 relevant repositories indexed on [instance URL]. This helps Cody provide more tailored answers.`

**Comment by meglynst** [comment]
@danielmarquespt Hey again! @rrhyne launched 10 more tests for VS Code and analyzed them and says that discoverability of autocomplete itself is more of a problem than tabbing for the first time. If you could add an issue for discoverability as well, we would appreciate it! See the details about that update here: 

https://sourcegraph.slack.com/archives/C05AGQYD528/p1714350583182199?thread_ts=1713194059.898219&cid=C05AGQYD528
