### ISSUE TITLE
JetBrains: Autocomplete is broken and not suggesting anything

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1345]
### Cody Version

v5.5.6-nightly

### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
idea.plugin.protoeditor (233.13135.65)
DevKit (233.14015.152)
gherkin (233.11799.165)
cucumber-java (233.11799.196)
PythonCore (233.14015.106)
com.sourcegraph.jetbrains (5.5.6-nightly)
Kotlin: 233.14015.106-IJ

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ IDEA editor
2. Login to Cody with Pro user
3. Open a blank Java file and paste following snippet
```
// print Hello World!
System.out.
```
4. Place a cursor at the end of the `System.out.` line
5. Trigger autocompletion with `Opt+\`

### Observed behavior:
Cody Autocomplete is broken.

### Expected behavior

Cody autocomplete should work and code should be autocompleted as below
```
// print Hello World!
System.out.println("Hello World!")
```

### Additional context

**Video link:**

https://drive.google.com/file/d/1Z9gkodR8719gEph2ZAgAmzYHsFSyE6TE/view?usp=drive_link

**Comment by dominiccooney** [comment]
I can't reproduce this at 9c26d2dcd7bf11a7a438b2a7c9d9e5de80cc7230. Please share a debug logs.

**Comment by jay-fibi** [comment]
@dominiccooney This might be a temp issue as I cannot reproduce it now. Closing it for now, but if I hit this again I will share the logs and create a new ticket. Thank you.
