### ISSUE TITLE
JetBrains: Automatic repo recognition is not working after removing the repo and restarting the IDE

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1346]
### Cody Version

v5.5.6-nightly

### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
idea.plugin.protoeditor (233.13135.65)
DevKit (233.14015.152)
gherkin (233.11799.165)
cucumber-java (233.11799.196)
PythonCore (233.14015.106)
com.sourcegraph.jetbrains (5.5.6-nightly)
Kotlin: 233.14015.106-IJ

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ IDEA editor
2. Login to Cody with Enterprise user
3. Open project with enabled Git VCS. This repository must be publicly available on GitHub.
4. Open to Cody tool window.
5. Click on repository button to open `Context Selection` dialog.
6. Remove the repo and re-launch the IDE

### Observed behavior:
Repo will not be re-added automatically.

### Expected behavior

Repo should be automatically recognised and added.

### Additional context

**Video link:**

https://drive.google.com/file/d/1X_fpQV7BvpgflTZBhW-SatXVZONYvM5g/view?usp=drive_link

**Comment by dominiccooney** [comment]
For now, this is basically working as intended. The repo will be implicitly selected and used for context, even if it is not displayed in that list. We are tracking displaying it in the list in #1322 .
