### ISSUE TITLE
JetBrains: Adding remote repo with "https://" is not working.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1354]
### Cody Version

v5.5.6-nightly

### IDE Information

IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
PythonCore (233.14475.9)
com.soywiz.korge.korge-intellij-plugin (4.0.4)
com.sourcegraph.jetbrains (5.5.6-nightly)
Kotlin: 233.14475.28-IJ

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ IDEA editor
2. Login to Cody with Enterprise user
3. Open Cody chat context and add repo with full URL i.e. `https://github.com/sourcegraph/sourcegraph`
4. Try to save the changes

### Observed behavior:

Changes will be discarded and repo will not be added
Remove the "https://" from the URL and try again. Repo will be added successfully.

### Expected behavior

It should allow user to add repo will full URL including `https://github.com/sourcegraph/sourcegraph`

### Additional context

**Screenshot:**

![image (2)](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/796523de-3c3d-46f2-b71e-3e70255ac2b4/57d24d85-5561-4ecc-b373-4882166b7f71?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy83OTY1MjNkZS0zYzNkLTQ2ZjItYjcxZS0zZTcwMjU1YWMyYjQvNTdkMjRkODUtNTU2MS00ZWNjLWIzNzMtNDg4MjE2NmI3ZjcxIiwiaWF0IjoxNzE3NDUyNjQzLCJleHAiOjMzMjg4MDEyNjQzfQ.yNlc8raSj1HDzpNXUnjWnWpFEChLzZ2Pzzl-i3HHRMc)

**Comment by dominiccooney** [comment]
Seems like a good idea.

@danielmarquespt I assume we *don't* want to autocomplete the clone URLs because they will be ugly and duplicative?

**Comment by dominiccooney** [comment]
Note, there's a GraphQL field, `cloneURL` we should be using for this, apparently, and not guessing based on the structure of the clone URLs like we do in `RepoInfo.java`

**Comment by danielmarquespt** [comment]
Exactly. We should accept the cloneURL, but autocomplete should be the “simple" version host.domain/org/repo

**Comment by dominiccooney** [comment]
We need to expose `enterpriseRepoNameResolver` and its cache of remote URLs to repository names through agent.
