### ISSUE TITLE
Log additional telemetry for product analytics KPI tracking

### ISSUE THREAD

**Issue by kelsey-brown** [sourcegraph/jetbrains#137]
Hey team - I have a request for some additional telemetry to get JetBrains logging up to speed with new events and metadata that VSCode has started logging recently. These particular events are now included in metrics that we’re visualizing in Looker, so I want to be sure we get this data for JetBrains as well. 

I’ll list the event names in VSCode below but let me know what other information you need - I’m not entirely sure if the cody agent makes the process of logging these events on an additional clients easy, or if you need further definitions of each event, links to where they are implemented, etc. Please let me know what other information would be helpful. 

cc @taylorsperry this is my “high priority” event list from our conversation [here](https://sourcegraph.slack.com/archives/CN4FC7XT4/p1699928141704479) - happy to chat more if there are more events you want added. 

Events

- CodyVSCodeExtension:Auth:connected (https://github.com/sourcegraph/cody/pull/1911 and misc others)
- CodyVSCodeExtension:completion:partiallyAccepted (https://github.com/sourcegraph/cody/pull/1911)
- CodyVSCodeExtension:completion:persistence:present (https://github.com/sourcegraph/cody/pull/2017)
- CodyVSCodeExtension:completion:persistence:removed (https://github.com/sourcegraph/cody/pull/2017)
- CodyVSCodeExtension:fixupResponse:hasCode
- CodyVSCodeExtension:chatResponse:hasCode
- CodyVSCodeExtension:inlineChat:Paste:clicked
- CodyVSCodeExtension:keyDown:Paste:clicked
- CodyVSCodeExtension:insertButton:clicked
- CodyVSCodeExtension:keyDown:Copy:clicked
- CodyVSCodeExtension:inlineChat:Copy:clicked
- CodyVSCodeExtension:copyButton:clicked

**Comment by kalanchan** [comment]
going to close this for now and let taylor reprioritize this
