### ISSUE TITLE
bug: StringIndexOutofBoundsException

### ISSUE THREAD

**Issue by hopkinscl** [sourcegraph/jetbrains#1377]
### Cody Version

5.5.5

### IDE Information

Webstorm 2023.3.5
Build #WS-233.14808.24, built on March 13, 2024

### Describe the bug

User is seeing the below error and the editor is lagging when using Cody for autocomplete (TypeScript/TSX)
![image](https://github.com/sourcegraph/jetbrains/assets/16723605/390db657-6bd9-45e4-9bec-294801894b13)

### Expected behavior

No exception

### Additional context

Previously reported [here](https://github.com/sourcegraph/jetbrains/issues/679)

**Comment by taylorsperry** [comment]
closing in favor of https://github.com/sourcegraph/jetbrains/issues/1406
