### ISSUE TITLE
bug: com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.source...

### ISSUE THREAD

**Issue by Malrama** [sourcegraph/jetbrains#1404]
### Cody Version

5.5.5

### IDE Information

PyCharm 2024.1 (Community Edition)
Build #PC-241.14494.241, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
  ide.balloon.shadow.size=0
  debugger.new.tool.window.layout=true
  ide.intellij.laf.enable.animation=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.markskelton.one-dark-theme (5.10.0)
  com.sburlyaev.terminal.plugin (0.8.0)
  com.arcticicestudio.nord.jetbrains (0.13.0)
  Dart (241.15845)
  com.codeium.intellij (1.8.27)
  com.thvardhan.gradianto (5.5)
  com.mallowigi.idea (23.0.0)
  com.jetbrains.darkPurpleTheme (1.3)
  com.jetbrains.space (241.14494.150)
  Docker (241.14494.251)
  com.koxudaxi.ruff (0.0.33)
  com.sourcegraph.jetbrains (5.5.5)
  codiumai.codiumai (0.7.33)

### Describe the bug

I got this error starting up the IDE after updating to 5.5.5 and clicked "report"

### Expected behavior

No error meesage

### Additional context

Stacktrace:

```text
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.sourcegraph.cody.history.ChatHistoryPanel$LeafPopupAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.sourcegraph.jetbrains]
 at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
 at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
 at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
 at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
 at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
 
```

**Comment by kalanchan** [comment]
this will be fixed in the next JB release (5.5.10) and above
