### ISSUE TITLE
JetBrains: Automatic repository recognition is not working.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1416]
### Cody Version

v5.5.7-nightly

### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
idea.plugin.protoeditor (233.13135.65)
DevKit (233.14015.152)
gherkin (233.11799.165)
cucumber-java (233.11799.196)
PythonCore (233.14015.106)
com.sourcegraph.jetbrains (5.5.7-nightly)
Kotlin: 233.14015.106-IJ

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ IDEA editor
2. Login to Cody with Enterprise user
3. Open project with enabled Git VCS. This repository must be publicly available on GitHub i.e. https://github.com/sourcegraph/codemod
4. Open to Cody tool window
5. Check the Context Selection 

### Observed behavior:
Repository is not automatically recognised.

### Expected behavior

Automatic repository recognition should work and repo should be added automatically.

### Additional context

**Video link:**

https://drive.google.com/file/d/1jNOjPuCUHpGlAj5G_7B57A_lu-Ju6I3O/view?usp=drive_link

**Comment by taylorsperry** [comment]
@dominiccooney are you the best person to take a look at this?

**Comment by dominiccooney** [comment]
@jay-fibi , you should perform a chat and see what context is fetched. Default context selection should be working. The test pass would be better if it verified that, too.

If there is an issue, it is to display the implicitly picked repo in the context list. This is tracked in #1322.

@taylorsperry I will work on this later. This is not a P0, it is a cosmetic issue with not displaying the implicitly picked repo. Before the repo autocomplete popup we had a similar problem—the context list *always* showed "local context" even when implicit detection failed. Now we never show it. So this is not a new issue exactly, just the surface appearance of it changed with the new repo picker.

**Comment by taylorsperry** [comment]
Thank you, @dominiccooney ! I'm closing in favor of https://github.com/sourcegraph/jetbrains/issues/1322.

**Comment by dominiccooney** [comment]
This was accidentally reopened, so re-closing, but just noting that I have changed the enterprise repo picker in 70e78539124b94b6964c29ab51c2ca953910d569 to always display the state synced with agent. This means we display the automatically selected repo (if any), you can't remove it, and there's a tooltip explaining what is going on.

![Screenshot 2024-05-10 at 16 35 13](https://github.com/sourcegraph/jetbrains/assets/55120/99df332a-fd88-40c1-ba7c-cb3a414f41ec)
