### ISSUE TITLE
JetBrains: The behavior of remote repo added when opening an older chat with more than 10 repo is not clear. 

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1417]
### Cody Version

v5.5.7-nightly

### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
idea.plugin.protoeditor (233.13135.65)
DevKit (233.14015.152)
gherkin (233.11799.165)
cucumber-java (233.11799.196)
PythonCore (233.14015.106)
com.sourcegraph.jetbrains (5.5.7-nightly)
Kotlin: 233.14015.106-IJ

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ IDEA editor
2. Login to Cody with Enterprise user
3. Have 1 remote repo added for Context Selection
4. Open an older Chat from 'Chat History' with more than 10 repo
5. Verify that only 10 repo showing (Bug-1 static list of repo)
6. Click on Pencil icon and check other repo are omitted from the selection
7. Click on 'New Chat' button

### Observed behavior:
Initially, only 1 repo was there by user(already existed) and opening older chat will automatically add other repo without saving. Also, the original repo is replaced with this static list.

### Expected behavior

Repo should not be added automatically when opening older chats.

### Additional context

**Video link:**

https://drive.google.com/file/d/1xV62FjG5NFbvbV6cDNz6x6dtwGX9G4qI/view?usp=drive_link

**Comment by dominiccooney** [comment]
@taylorsperry , I'm assigning this to you to clarify what the product behavior we want here is.

The behavior in the video is what I intended in the code, namely:

- Restoring old chats uses their repositories.
- If the old chat has more than 10 repositories, we take the first ten.
- However, we list all of the repositories in the text entry field in the event users want to edit them. Saving the chat will update the saved repository list to those 10, however.

This, combined with the existing trigger of saving the last used repo list as the default for new chats, explains all the behavior in the video.

If that's not right, that's fine, but we need to know what which of those choices was wrong/what the desired behavior is.

**Comment by taylorsperry** [comment]
No, you're right, @dominiccooney. This behavior is aligned with my expectation, though it's interesting that it was counterintuitive to @jay-fibi. I'm going to close for now, but let's see if other users report the same kind of confusion.
