### ISSUE TITLE
bug: Inline Edits requests fail when performed at the end of your file

### ISSUE THREAD

**Issue by steveyegge** [sourcegraph/jetbrains#1421]
### Cody Version

5.5.7-nightly

### IDE Information

IntelliJ 2023.3.3 Ultimate Edition
Build #IU-233.14015.106, built on January 24, 2024

### Describe the bug

1. Go to the end of your source file (or the top of an empty file)
2. Choose Cody -> Edit Code
3. Give some instructions, such as "create an enum class with the rainbow colors "
4. Send the edit request

The enum is emitted 2-3 times at the end of the file. Repeating the action gradually makes the extra text "shorter" , but there are garbage characters being inserted, particularly  "<C" which is part of the invisible prompt.

### Expected behavior

Should create an enum at the end of the file, without spewing out extra characters.

**Comment by kalanchan** [comment]
Tom pushed a work around that temporarily resolves this, still need to have a final solution

**Comment by pkukielka** [comment]
@kalanchan Streaming was fixed and enabled again, I think problem is gone now, I cannot reproduce it.
