### ISSUE TITLE
JetBrains: "Edit & Retry" keep adding new code snippet instead of replacing the same

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1424]
### Cody Version

v5.5.8-nightly

### IDE Information

PyCharm 2023.3.3 (Community Edition)
Build #PC-233.13763.11, built on January 26, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (5.5.8-nightly)

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ IDEA editor
2. Login to Cody with PRO user
3. Open any source code file and right-click to open context menu
4. Choose "Cody > Edit Code"
5. Enter prompt message "generate doc string" and hit enter
6. Click on "Edit & Retry" ghost text and verify the Edit Code dialog appears
7. Enter the same prompt message and hit enter

### Observed behavior:
Cody will keep the old doc string and re-add new one. 

### Expected behavior

Cody should replace the snippet for "Edit & Retry" 

### Additional context

**Video link:**

https://drive.google.com/file/d/10j6v-I6toZVUWCQlmFRCcprUi2RYN1_G/view?usp=drive_link

**Comment by taylorsperry** [comment]
@jay-fibi I couldn't repro this on `v5.5.10-nightly`. Can you?

**Comment by jay-fibi** [comment]
@taylorsperry this seems to be fixed. I cannot repro it with `v5.5.10-nightly`. Feel free to close it.
