### ISSUE TITLE
JetBrains: Remote repo popup window size is not adequate.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1425]
### Cody Version

v5.5.8-nightly

### IDE Information

PyCharm 2023.3.3 (Community Edition)
Build #PC-233.13763.11, built on January 26, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
com.sourcegraph.jetbrains (5.5.8-nightly)

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ IDEA editor
2. Login to Cody with Enterprise user
3. Click on pencil icon to open remote repo popup window
4. Start adding repo

### Observed behavior:

After adding third repo, the popup size seems very small

### Expected behavior

Remote repo popup window should be bigger to show all repo URLs.

### Additional context

**Screenshot:**

![Screenshot 2024-05-01 at 12 25 07 AM](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/001cad54-4530-4255-b706-386373034b48/3bb31698-3bc8-49ed-bee3-d66c0e76e473?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy8wMDFjYWQ1NC00NTMwLTQyNTUtYjcwNi0zODYzNzMwMzRiNDgvM2JiMzE2OTgtM2JjOC00OWVkLWJlZTMtZDY2YzBlNzZlNDczIiwiaWF0IjoxNzE1MzY4MTMyLCJleHAiOjMzMjg1OTI4MTMyfQ.aun-keLQZu6_o6nvI5xoCrbY_ZrJvZkxQDFoicziWiw "=425x")

**Comment by taylorsperry** [comment]
@danielmarquespt I think you were working on this, correct?
