### ISSUE TITLE
JetBrains: Ghost text disappear when user click on "Edit & Retry" and cancels the action.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1426]
### Cody Version

v5.5.8-nightly

### IDE Information

PyCharm 2023.3.3 (Community Edition)
Build #PC-233.13763.11, built on January 26, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
com.sourcegraph.jetbrains (5.5.8-nightly)

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ IDEA editor
2. Login to Cody with PRO user
3. Open any source code file and right-click to open context menu
4. Choose "Cody > Edit Code"
5. Enter prompt message "generate doc string" and hit enter
6. Click on "Edit & Retry" ghost text 
7. Verify that the dialog box opened for Edit Code
8. Hit `esc` 

### Observed behavior:
Ghost text disappear and the snippet is added. If user want to see the diff then there is no way.

### Expected behavior

Ghost text should be present if user cancels the action. 
This is working fine for "Show Diff" if user return back to left hand side.

### Additional context

**Video link:**

https://drive.google.com/file/d/1hzDP0-BOXaAGAQtJfHdZ7TZrvNk86BR6/view?usp=drive_link

**Comment by taylorsperry** [comment]
I'm not sure the behavior is exactly the same on version `5.5.10`, but there's still a bug: When a user performs and edit action, selects the ghost text to "Edit and Retry," and then cancels, the original edit should persist with the ghost text options to accept/undo/edit/view diff.

**Comment by pkukielka** [comment]
> I'm not sure the behavior is exactly the same on version 5.5.10, but there's still a bug: When a user performs and edit action, selects the ghost text to "Edit and Retry," and then cancels, the original edit should persist with the ghost text options to accept/undo/edit/view diff.

That is indeed not how it works today, and I think it won't be possible to make it work that way without major changes.
What happens today is when user run "Edit and Retry", we do a Undo, and then send a new Edit command with a changed prompt. We could perhaps change a order a bit, and only undo after user accepts the new prompt.
But either way after this happens, if user will cancel on this point, we do not have an easy way to rollback and show previous lens, with previous changes again.

As a matter of fact it also works this way in VSCode.
