### ISSUE TITLE
bug: Cody status bar menu has "nothing here"

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/jetbrains#1438]
### Cody Version

v5.5.8

### IDE Information

IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Licensed to Sourcegraph / Dominic Cooney
Subscription is active until February 28, 2025.
Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
Kotlin analyzer version: 2.0.0-ij241-276
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.jetbrains.space (241.14494.150)
  google-java-format (1.21.0.0)
  DevKit (241.14494.247)
  io.intellij-sdk-thread-access (2.2.1)
  com.jetbrains.packagesearch.intellij-plugin (241.0.8)
  com.sourcegraph.jetbrains (5.5.8)
Kotlin: 241.14494.240-IJ

### Describe the bug

![Screenshot 2024-05-02 at 10 25 39](https://github.com/sourcegraph/jetbrains/assets/55120/6c09d473-cc48-4048-bb31-ae58970e4a84)

### Expected behavior

There's a menu for settings, accounts, etc.

**Comment by taylorsperry** [comment]
@dominiccooney I don't see this on `v5.5.10-nightly`. Do you?

**Comment by dominiccooney** [comment]
I'm on 5.5.9 now and still seeing it. I've been seeing this for ages, actually. Looks like this:

![Screenshot 2024-05-13 at 13 28 49](https://github.com/sourcegraph/jetbrains/assets/55120/28e1b37a-89a9-4f98-b741-8f61d07b0ff1)

Doesn't happen to me when I'm debugging, only when I'm the IntelliJs I'm using as my main editors. Also happens in Rust Rover, etc:

![Screenshot 2024-05-13 at 13 31 18](https://github.com/sourcegraph/jetbrains/assets/55120/6b599153-892e-4243-8bd1-5deb4366456d)

**Comment by taylorsperry** [comment]
another report of this https://github.com/sourcegraph/cody-issues/issues/276

**Comment by pkukielka** [comment]
@dominiccooney interestingly it never happened to me.
On what IJ versions you see that issue?

**Comment by taylorsperry** [comment]
I've not seen this on my version (below) but @olafurpg [reported](https://github.com/sourcegraph/cody-issues/issues/308) it also.

**Comment by taylorsperry** [comment]
@RXminuS also [reported](https://github.com/sourcegraph/cody-issues/issues/276) this, though I haven't seen it on my version: 

IntelliJ IDEA 2023.3.3 (Ultimate Edition)
Build #IU-233.14015.106, built on January 24, 2024
Licensed to Sourcegraph / Taylor Sperry
You have a perpetual fallback license for this version.
Subscription is active until May 12, 2025.
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  markdown.open.vcs.log.link=true
Non-Bundled Plugins:
  com.intellij.ml.llm (233.14015.147)
  mdx.js (233.11799.172)
  com.sourcegraph.jetbrains (5.5.12-nightly)
Kotlin: 233.14015.106-IJ

**Comment by mkondratek** [comment]
The problem occurs for IntelliJ Ultimate (but it's impossible to reproduce it on IC). Our development configuration sets `platformType` to `IC` (which is IntelliJ Community). I did a quick research and just learned that it is possible to perform a dev run for `IU` - one must just change the platform type. Btw the list of all types is here:
https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-types.html#IntelliJPlatformType

**Comment by RXminuS** [comment]
It seems to only be 2024+

**Comment by RXminuS** [comment]
Raised to P0 because root cause is actually quite a fundamental problem.

**Comment by dominiccooney** [comment]
@rik.nauta can you elaborate, what is the underlying cause?

**Comment by RXminuS** [comment]
https://github.com/sourcegraph/jetbrains/pull/1655
