### ISSUE TITLE
JetBrains: Oauth Codebase or Local Codebase

### ISSUE THREAD

**Issue by Surt** [sourcegraph/jetbrains#144]
I was wondering how to set the Codebase, the repo used for context, on a private repo, or just the local repo

![image](https://github.com/sourcegraph/sourcegraph/assets/48085/c0eff1e8-288b-4d5b-935d-a0351686352e)

I tried with oauth routes for gitlab, with a token, etc but I haven't found a solution. Would be great to just read the "project code" or the local git repo.

**Comment by mkondratek** [comment]
Hello @Surt 👋 I am sorry you had to wait so long. I am ready to help you. 

I do not fully understand your question. What are you trying to achieve? Do you want to use a private GitLab repository as a context?
