### ISSUE TITLE
bug: Edits do not correctly stream into the document

### ISSUE THREAD

**Issue by umpox** [sourcegraph/jetbrains#1449]
### Cody Version

latest `main`

### IDE Information

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6.4
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 10
Non-Bundled Plugins:
    com.sourcegraph.jetbrains (6.0-localbuild)

Kotlin: 221-1.6.20-release-285-IJ5080.210

### Describe the bug

https://github.com/sourcegraph/jetbrains/assets/9516420/6f880752-bd67-42e8-af89-408a09f612bd

The text that is applied to the Edit does not match the final LLM response, it contains duplicate chunks as it is streamed in

### Expected behavior

The LLM response matches the Edit applied, no duplicate code

**Comment by taylorsperry** [comment]
@umpox is it ok to close this, given https://github.com/sourcegraph/cody/pull/4030?

**Comment by umpox** [comment]
@taylorsperry Sorry missed this, should be fully fixed by https://github.com/sourcegraph/cody/pull/4172

**Comment by taylorsperry** [comment]
Awesome, thanks, Tom! We'll close once that merges.
