### ISSUE TITLE
PLG: Add in-chat "Upgrade" notification after exceeding rate limit

### ISSUE THREAD

**Issue by exigow** [sourcegraph/jetbrains#146]
Upgrade button can simply navigate to `sourcegraph.com/cody/subscription`.

The design should be similar to VS Code:

![image](https://github.com/sourcegraph/jetbrains/assets/5013708/9eb77174-f1cb-4b4b-a6a6-17f44c3cd9aa)

Important note: PLG features cannot be published before GA, so it must be controlled by the `cody-pro` feature flag.

**Comment by exigow** [comment]
@danielmarquespt, could you please provide some insights on the purpose of the 'Learn More' button?

**Comment by exigow** [comment]
This issue is blocked by: https://github.com/sourcegraph/jetbrains/issues/147

**Comment by olafurpg** [comment]
Closing as fixed. The design can be improved but that is more likely a P2 issue, not P0
