### ISSUE TITLE
JetBrains: Ghost text (code lenses) will not be available if user do "Edit & Retry" multiple times.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1465]
### Cody Version

v5.5.10-nightly

### IDE Information

IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
PythonCore (233.14475.9)
com.soywiz.korge.korge-intellij-plugin (4.0.4)
com.sourcegraph.jetbrains (5.5.10-nightly)
Kotlin: 233.14475.28-IJ

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ IDEA editor
2. Login to Cody with Free/Pro user
3. Open any source code file and select a code snippet
4. Right click to open context menu and choose "Cody > Document Code"
5. Click on "Edit & Retry" and type in something i.e. `generate doc string` and hit enter
6. Again click on "Edit & Retry" and type in something i.e. `create a simple test function` and hit enter

### Observed behavior:
Ghost text(code lenses) is missing for the added code snippet from step-6 above

### Expected behavior

Ghost text should appear correctly so that user can choose Accept, Undo, Edit & Retry, or Show Diff

### Additional context

**Video link:**

https://drive.google.com/file/d/1Mo5sSNxzJlgSvaCwpRKC2i_Tdkgx4Q2j/view?usp=drive_link

**Comment by taylorsperry** [comment]
@jay-fibi I haven't been able to repro this on `5.5.11-nightly`. Are you still seeing this issue? If so, would you please add logs?

**Comment by jay-fibi** [comment]
@taylorsperry Yes, I am still able to repro this issue with `5.5.11-nightly` . Though, it is intermittent and doesn't repro every time. The steps are same as above.

**Comment by jay-fibi** [comment]
@taylorsperry attaching `idea.log` file for your reference
[idea.log](https://github.com/sourcegraph/jetbrains/files/15381792/idea.log)
