### ISSUE TITLE
bug: Autocomplete bug using with Korean(ex. comment)

### ISSUE THREAD

**Issue by kebin0591** [sourcegraph/jetbrains#1467]
### Cody Version

5.5.9

### IDE Information

IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Licensed to Hyung Jin Choo
Subscription is active until October 4, 2024.
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4068M
Cores: 20
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  some.awesome (1.15)
  com.jetbrains.space (241.14494.150)
  Key Promoter X (2024.1.0)
  indent-rainbow.indent-rainbow (2.2.0)
  com.github.copilot (1.5.2.5345)
  com.almightyalpaca.intellij.plugins.discord (1.12.0)
  izhangzhihao.rainbow.brackets (2024.2.3-241)
  com.sourcegraph.jetbrains (5.5.9)
  com.mallowigi (95.0.0)
Kotlin: 241.14494.240-IJ

### Describe the bug

![image](https://github.com/sourcegraph/jetbrains/assets/166422645/c6aaa106-94f6-496f-a11a-8c591a90d3e3)

using autocomplete feature with korean, having a autocomplete preview output bug showing with squares instead korean language.
When I press 'tab' for confirmation of auto complete, it prompts Korean well. 

(Pink color is Cody's Autocomplete message)

### Expected behavior

prompt Autocomplete preview normaly with Korean.

**Comment by dominiccooney** [comment]
@kebin0591 I can't reproduce this… Could you share the encoding of that file, your editor font, and what completions model you are using (if you have changed it?)

**Comment by kebin0591** [comment]
> @kebin0591 I can't reproduce this… Could you share the encoding of that file, your editor font, and what completions model you are using (if you have changed it?)

Yup, np.
Encoding i use is global : UTF-8, same with projects.
For fonts, I use Default setting of IntelliJ. (Jetbrains Mono)
![image](https://github.com/sourcegraph/jetbrains/assets/166422645/3a918420-0732-4c0b-a4cc-2996738e5e95)

And only use IntelliJ, with cody pro, Not changed any completions model. I'm using default completions. (I can't find how can I change those model on intellij)

**Comment by dominiccooney** [comment]
Thanks for those details! This may be specific to Windows.

**Comment by kebin0591** [comment]
> Thanks for those details! This may be specific to Windows.

Ah rly?? So it's window's problem?

**Comment by dominiccooney** [comment]
Yeah, I can reproduce this on Windows 11 with Rust Rover and Cody 5.5.9. I think it is to do with the autocomplete suggestion being in italic.

**Comment by kebin0591** [comment]
> Yeah, I can reproduce this on Windows 11 with Rust Rover and Cody 5.5.9. I think it is to do with the autocomplete suggestion being in italic.

Hmmm that's kinda weird.. Is there any Solution for that?

**Comment by dominiccooney** [comment]
We'll fix it!

**Comment by kebin0591** [comment]
Thanks!!!! I'll wait!!
