### ISSUE TITLE
PLG: Add ability to check account Pro status and current quota / rate limits

### ISSUE THREAD

**Issue by exigow** [sourcegraph/jetbrains#147]
We need the following queries to start working on PLG features: 
* Is Cody Pro enabled?
* What's the current Chat usage and what's the limit?
* What's the current Code usage and what's the limit?

More details: https://docs.google.com/document/d/1qYDsO6GOxGHEB2ZRSO9BWgjTra2adw0y3BDTNkjZqZw/edit

**Comment by vdavid** [comment]
For the record, we have this now:
![CleanShot 2023-12-05 at 00 04 52@2x](https://github.com/sourcegraph/jetbrains/assets/2552265/71cb3d9a-d172-456f-94dd-02dcf88dba1c)

As plain text:
```
x-ratelimit-limit: 1
x-ratelimit-remaining: 0
retry-after: Mon, 27 Nov 2023 11:30:08 UTC
x-is-cody-pro-user: false
```

**Comment by vdavid** [comment]
There is also a GraphQL API to query the limits—I can bring the info here, but I don't think we really need an extra call as these 429s return all the info we need.
Let me know if you need the GraphQL API anyway, or any other info

**Comment by exigow** [comment]
This issue mainly boils down to adding statuses :zap: _You used all X chat (...)_ to the subscription panel that Szymon was working on (currently we have only Upbrade and Usage buttons):

![image](https://github.com/sourcegraph/jetbrains/assets/5013708/f2446598-bdfa-4f7c-b74d-a1bad0eb43d1)

Design: https://www.figma.com/file/m9Yvgv6W3aPRLfXnxgwnEz/JetBrains?type=design&node-id=215-2737&mode=design&t=3fzKnl4VfRYHeh7h-0

**Comment by taylorsperry** [comment]
Is this issue OK to close, @exigow ?
