### ISSUE TITLE
PLG: Replace toast with in-chat "Unable to send message" notification on PRO account after exceeding rate limit

### ISSUE THREAD

**Issue by exigow** [sourcegraph/jetbrains#148]
Currently, the only visual indicator for exceeding the limit is a notification toast. We want this information to be placed in the chat according to the new design:

![image](https://github.com/sourcegraph/jetbrains/assets/5013708/ac379ea0-e8ba-45fe-af20-acb597ff4bda)

We also want to include information about when the next quota reset will occur.

Important note: PLG features cannot be published before GA, so it must be controlled by the cody-pro feature flag.

**Comment by exigow** [comment]
Blocked by: https://github.com/sourcegraph/jetbrains/issues/147

**Comment by olafurpg** [comment]
Closing as fixed the design can be improved later
