### ISSUE TITLE
JetBrains: Random repo got removed when user tries to add more than 10 repo.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1484]
### Cody Version

v5.5.10-nightly

### IDE Information

PyCharm 2023.3.3 (Community Edition)
Build #PC-233.13763.11, built on January 26, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
com.sourcegraph.jetbrains (5.5.10-nightly)

### Describe the bug

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB PyCharm editor
2. Login to Cody with Enterprise user
3. Open Code context and add 10 repo
4. Hit enter and verify the repo added correctly
5. Now add 11th repo and verify that the text is hightlighted yellow
6. Hit enter to save changes and verify the repo list

### Observed behavior:
A random repo got removed and the yellow highlighted repo got added. 

### Expected behavior

The 11th repo should not be added and any random repo should not be removed.

### Additional context

**Video link:**

https://drive.google.com/file/d/1gk9WcoAzgOIVefEQ6K2STaZeIagnF3RG/view?usp=drive_link

**Comment by dominiccooney** [comment]
Good bug.

What's happening here: We're sending all of the repos to the backend, it is returning sorted results, and we're taking the first 10. It's definitely confusing because we've been highlighting the ones added at the bottom of the list in mustard. We should prune those first.
