### ISSUE TITLE
PLG: Add "Upgrade to Cody Pro" and "Current Usage" settings buttons

### ISSUE THREAD

**Issue by exigow** [sourcegraph/jetbrains#149]
We want to enable users to see the current number of available Chat/Code queries **without** exceeding the rate limit.

This is scenario when user downloads the plugin from the marketplace and once is signed in, he should be able to check current usage without interacting with chat (theoretically).

* Usage button should navigate to [sourcegraph.com/cody/manage](http://sourcegraph.com/manage).
* Upgrade button should navigate to [sourcegraph.com/cody/subscription](http://sourcegraph.com/cody/subscription).

Important note: PLG features cannot be published before GA, so it must be controlled by the cody-pro feature flag.

**Comment by exigow** [comment]
~@danielmarquespt, do you have some ideas on how we should show this buttons? I suggested placing these buttons in the settings, but I'm not sure if that's a good solution. Can you please verify this?~

EDIT: Design: https://github.com/sourcegraph/jetbrains/issues/156

**Comment by exigow** [comment]
This issue is blocked by https://github.com/sourcegraph/jetbrains/issues/147.

**Comment by exigow** [comment]
Clarification: Pages are blank because only @sourcegraph.com email addresses have access to the `/cody/manage` and `/cody/subscription`.

**Comment by mkondratek** [comment]
1. Does it mean the upgrade and current usage options SHOULD NOT be available to everyone (but to the users with `@sourcegraph.com` only)?
2. How can I tell whether I am `@sourcegraph.com` or not?
