### ISSUE TITLE
Cody Ignore UI-level blocks

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/jetbrains#1494]

**Comment by dominiccooney** [comment]
@taylorsperry what's the priority on this one? Since Cody Ignore is new I guess adoption is 0 so... P1?

**Comment by taylorsperry** [comment]
I'm not exactly sure what the issue is. Is this enabling telemetry to send an event when a user encounters a UI warning that "Cody is Limited" due to the admin enabling Cody Ignore?

**Comment by dominiccooney** [comment]
Yes, that is it. We have zero Telemetry on these so as-is we won't know how often users are getting actions blocked by Cody Ignore.

**Comment by taylorsperry** [comment]
Got it, thanks! @aramaraju is this a GA blocker? Marking as P1 for now.

**Comment by aramaraju** [comment]
Good with a P1 👍
