### ISSUE TITLE
Add a notification that the extension is out of date

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#151]
Today, users will only notice that their extension version is out of date if they reopen the IDE or navigate to the settings page ([thread](https://sourcegraph.slack.com/archives/C059N5FRYG3/p1701375271622169)). We should make this more easily discoverable by adding a notification as soon as an update is available, with links to release notes. @danielmarquespt could you please help mimic the designs that Tim has for VSC?

**Comment by mkondratek** [comment]
I agree that it would be a very nice experience but I need to make a note. To have a notification as soon as an update is available we need to check for updates e.g. every `x` minutes. Checking for plugin updates can be a time- and resource-consuming process. We must be careful so we do not check for updates too frequently.

**Comment by taylorsperry** [comment]
Thanks @mkondratek, makes sense. Is there a reason we wouldn't be able to check for updates at the same cadence that VS Code does?

**Comment by mkondratek** [comment]
That's a good question. Tbh, I do not know how VS code does it. I am going to find out.
