### ISSUE TITLE
Jetbrains cody extension doesn’t recognize file until a portion of the file has been selected

### ISSUE THREAD

**Issue by AJKemps** [sourcegraph/jetbrains#152]
Sourcegraph version: 5.2.2
Reported by: https://github.com/sourcegraph/accounts/issues/6938

Steps to reproduce:

If you open a file in Jetbrains without selecting any content within the file, the extension provides a non-deterministic response of whether it even has access to that file even when the file is clearly in context at the bottom of the extension.

https://hello.chorus.ai/listen?guid=fbbcab7ac0c94fda8572ac8db42553aa

Expected behavior:
Opening a file in Jetbrains is enough to interact with it via Cody.

Actual behavior:
You must actually select some content in the file for the Cody extension to properly interact with the file or load into context.

**Comment by chwarwick** [comment]
In the video the user switches to a new tab of an open file, then asks “explain this file”  with a response of “Without being provided the contents of this file I do not have enough context…. ”

But then if the user highlights some code and asks “explain this file” it then works properly “Based on the code snippet, samplefile.java does…. ”
