### ISSUE TITLE
bug: Inline Edit lens group does not move with the new lines

### ISSUE THREAD

**Issue by mkondratek** [sourcegraph/jetbrains#1524]
## Scenario
1. Ask Inline Edit to add some code
2. Wait for it to finish
3. Add new lines/ remove lines above the selected area

### Actual
The lens group remains in it's place (almost - it moves according to autocomplete suggestions).

### Expected
The lens group moves to according to the selected area.

## Demo 

https://github.com/sourcegraph/jetbrains/assets/19799111/8ede8d10-2c98-42aa-9ae6-d97716af266c

**Comment by taylorsperry** [comment]
I wouldn't necessarily expect the code lens to move with the cursor, but it still feels jumpy once you start adding lines or getting autocomplete suggestions.
