### ISSUE TITLE
Commands panel buttons don't look like buttons

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#1527]
On `v.5.5.11` the buttons in the Commands panel don't look like buttons.

![Image](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/85bc7337-4628-44f6-8f1e-6b01f7869d6d/52115329-6161-4f8f-afba-66177e9cd1b4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy84NWJjNzMzNy00NjI4LTQ0ZjYtOGYxZS02YjAxZjc4NjlkNmQvNTIxMTUzMjktNjE2MS00ZjhmLWFmYmEtNjYxNzdlOWNkMWI0IiwiaWF0IjoxNzE2MzM4NTY4LCJleHAiOjMzMjg2ODk4NTY4fQ.kKmm1IOrlj_QufZc9s6om-6BejnLVwQUqMUWBEX6M6Q)

**Comment by taylorsperry** [comment]
@danielmarquespt the beta labels will go away for GA, but if you want to take this opportunity to propose any improvements to the button designs, please do!

**Comment by taylorsperry** [comment]
Downgrading to P1 since it's not a GA blocker, but should definitely try to fix!

**Comment by pkukielka** [comment]
@taylorsperry Interestingly I cannot reproduce this on any IntelliJ version.
What version you are on?

**Comment by mkondratek** [comment]
I used the plugin with 2023.3 and 2024.1 recently - I did not notice it. 

Was the new UI on?

Sometimes switching themes causes some problems - anyway, we may want to depriozitize this one.

**Comment by taylorsperry** [comment]
What's the new UI? I'm on: 

IntelliJ IDEA 2023.3.3 (Ultimate Edition)
Build #IU-233.14015.106, built on January 24, 2024
Licensed to Sourcegraph / Taylor Sperry
You have a perpetual fallback license for this version.
Subscription is active until May 12, 2025.
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  markdown.open.vcs.log.link=true
Non-Bundled Plugins:
  com.intellij.ml.llm (233.14015.147)
  mdx.js (233.11799.172)
  com.sourcegraph.jetbrains (5.5.12-nightly)
Kotlin: 233.14015.106-IJ

**Comment by taylorsperry** [comment]
@olafurpg also [reported](https://github.com/sourcegraph/cody-issues/issues/308) it.

**Comment by pkukielka** [comment]
It is a [New UI ](https://www.jetbrains.com/help/idea/new-ui.html) bug. Fixed :)
