### ISSUE TITLE
JetBrains: Getting error "unexpected status code 400" while running commands with enterprise user

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1531]
### Cody Version

v5.5.11-nightly

### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  idea.plugin.protoeditor (233.13135.65)
  DevKit (233.14015.152)
  gherkin (233.11799.165)
  cucumber-java (233.11799.196)
  PythonCore (233.14015.106)
  com.sourcegraph.jetbrains (5.5.11-nightly)
Kotlin: 233.14015.106-IJ

### Describe the bug

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Enterprise user(SG04 instance)
3. Open source code file and run command i.e. Explain Code

### Observed behavior:

Getting error "Sourcegraph Cody Gateway: unexpected status code 400: {"type":"error","error":{"type":"invalid_request_error","message":""claude-3-sonnet-20240229" is not supported on this API. Please use the Messages API instead."}}"

### Expected behavior

Error should not occur and Cody command should be run correctly.

### Additional context

**Screenshot:**

![Screenshot 2024-05-17 at 2 30 01 AM](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/ad1080b0-2ff5-4ebb-bd7d-18d21bc50c83/29208053-51ff-461a-a3b6-f8014944a69e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy9hZDEwODBiMC0yZmY1LTRlYmItYmQ3ZC0xOGQyMWJjNTBjODMvMjkyMDgwNTMtNTFmZi00NjFhLWEzYjYtZjgwMTQ5NDRhNjllIiwiaWF0IjoxNzE2MzE2NDY2LCJleHAiOjMzMjg2ODc2NDY2fQ.GM93dj7yP0DA8hT-Mp89ib3gLqx1Xgs6jmkDHEynS7o "=430x")

**Comment by mkondratek** [comment]
Possible related to: https://github.com/sourcegraph/cody/issues/3973

edit
It does not seem to be related (at least not very directly)
- this issue refers to the enterprise, the other to dotcom
- this issue's error says `"claude-3-sonnet-20240229" is not supported on this API. Please use the Messages API instead.`, the other says: `"openai/gpt-3.5-turbo" is not allowed, allowed: []`

**Comment by pkukielka** [comment]
It's the instance which is misconfigured. VSCode is also strugling:

![image](https://github.com/sourcegraph/jetbrains/assets/1519649/677f5d45-aa17-4d40-a2a6-d15270d4e467)

**Comment by taylorsperry** [comment]
@jay-fibi can you repro this when you're logged in to S02 or Dotcom?

**Comment by jay-fibi** [comment]
@taylorsperry I cannot repro this issue with S02 and Free/Pro accounts.

**Comment by mkondratek** [comment]
I've checked it too - no repro on sg02.

**Comment by dominiccooney** [comment]
@kalan, is this an error condition we need to display better output for? Can we close this?

**Comment by kalanchan** [comment]
My explanation from Slack:

> I think I figured it out, SG04 is pinned on Sourcegraph v5.3.2 which was [released](https://handbook.sourcegraph.com/departments/engineering/dev/process/releases/) on March 8, and Philipp’s [PR](https://github.com/sourcegraph/sourcegraph/pull/60953) added claude3 support to the enterprise on March 22 which introduced the new messages API endpoint. At some point in time, we made claude3 the default LLM for enterprise, so when I spun up SG04 it was trying to reach the messages API and threw the error because v5.3.2 does not have it.

Slight correction after reading the [Anthropic Upgrade to Messages API docs](https://docs.anthropic.com/en/docs/upgrading-to-the-messages-api) - What I think actually happened is that we're passing the model string `claude-3-sonnet-20240229` to the old **text completions** endpoint, and the error we are seeing is the response from Anthropic. I tested this with my own token, using the new messages api and the old text completions endpoint with `claude-3-sonnet-20240229` as the model. 

In the second screenshot, you can see that trying to hit the text completion endpoint with a claude3 model results in the same error we saw in SG04

cc @pkukielka the above is my up to date explanation :) 


![Image](https://github.com/sourcegraph/jetbrains/assets/51868853/330aa081-ddb0-40f3-84af-c2681a077f56)



![Image](https://github.com/sourcegraph/jetbrains/assets/51868853/5a86105d-ae7b-4969-b4fc-fd337842c771)
