### ISSUE TITLE
JetBrains: Slowness observed while selecting/deselecting repo from chat context.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1532]
### Cody Version

v5.5.11-nightly

### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
idea.plugin.protoeditor (233.13135.65)
DevKit (233.14015.152)
gherkin (233.11799.165)
cucumber-java (233.11799.196)
PythonCore (233.14015.106)
com.sourcegraph.jetbrains (5.5.11-nightly)
Kotlin: 233.14015.106-IJ

### Describe the bug

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Enterprise user(SG04 instance)
3. Add remote repo in chat context
4. Try selecting/deselecting repo using checkbox

### Observed behavior:
Slowness observed while selecting/deselecting repo

### Expected behavior

Repo selection should be quick and lag free.

### Additional context

**Video link:**

https://drive.google.com/file/d/1TkR9Fmpo5dauOE8CPbeOddRDgNKI5jwp/view?usp=drive_link

**Comment by dominiccooney** [comment]
This is a consequence of c4a1a467a84b94cfb055e9f5cef98598c3fecd64
