### ISSUE TITLE
JetBrains: Automatically recognized repo got deselected when closing and reopening IDE.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1542]
### Cody Version

v5.5.11-nightly

### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
idea.plugin.protoeditor (233.13135.65)
DevKit (233.14015.152)
gherkin (233.11799.165)
cucumber-java (233.11799.196)
PythonCore (233.14015.106)
com.sourcegraph.jetbrains (5.5.11-nightly)
Kotlin: 233.14015.106-IJ

### Describe the bug

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Enterprise user
3. Open project with enabled Git VCS
4. This repository must be publicly available on GitHub i.e. https://github.com/sourcegraph/cody
5. Verify that the Cody repo is automatically recognized and added to the context
6. Add few more remote repo to the context 
7. Close the IDE and reopen it
8. Check the Chat context window

### Observed behavior:
Automatically recognized repo got deselected.

### Expected behavior

Automatically recognized repo should not be deselected when closing/reopening IDE.

### Additional context

**Video link:**

https://drive.google.com/file/d/1wMfzxatNetkeSd1CP8CdcphE9L5prYxs/view?usp=drive_link

**Comment by taylorsperry** [comment]
This looks like an infelicity that was introduced with the multirepo checkbox updates. @danielmarquespt would you please make sure it's on your list for @dominiccooney for Monday?
