### ISSUE TITLE
JetBrains: Edit remote repo popup is hidden behind the Windows taskbar.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1554]
### Cody Version

v5.5.11-nightly

### IDE Information

IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
PythonCore (233.14475.9)
com.soywiz.korge.korge-intellij-plugin (4.0.4)
com.sourcegraph.jetbrains (5.5.11-nightly)
Kotlin: 233.14475.28-IJ

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Enterprise user
3. Click on pencil button to open remote repo popup 

### Observed behavior:
Edit remote repo popup window gets hidden behind Windows taskbar.

### Expected behavior

Edit remote repo popup should be clearly visible.

### Additional context

**Video link:**

https://drive.google.com/file/d/1TYkg6PtU_sTnG5ZVxrcJrcJuqZq4L3hC/view?usp=drive_link

**Comment by dominiccooney** [comment]
I have fixed this in WIP on this branch: https://github.com/sourcegraph/jetbrains/tree/dpc/issue-1322
