### ISSUE TITLE
gradle :runIde has broken fetching IntelliJ IC versions

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/jetbrains#1563]
In the old days? we could `./gradlew -PplatformRuntimeVersion=2024.1 :runIde` and Gradle would fetch and cache the IDE.

Now, that doesn't happen. If you don't have something cached in `~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC`, then gradle no longer fetches it for you and instead spits at you:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/dpc/projects/jetbrains/build.gradle.kts' line: 383

* What went wrong:
Could not find IntelliJ install for 2024.1
```

**Comment by dominiccooney** [comment]
As a workaround, you can edit `gradle.properties` and change this line:

```
platformVersion=2022.1
```

to the version you're interested in. But you have to remember to set it back.

**Comment by odisseus** [comment]
According to @pkukielka, it has never worked this way. The action of downloading the IntelliJ distribution is embedded deeply in the IntelliJ Platform plugin, and it downloads only the version against which the project is compiled. If you build the plugin with 2022.1 (the default) and invoke `runIde` with 2024.1, you will get an error unless the 2024.1 distribution is already cached by Gradle.

As a workaround, you can change the `platformVersion` [property](https://github.com/sourcegraph/jetbrains/blob/main/gradle.properties#L13) to 2024.1 and invoke `./gradlew compile` just once. Afterwards you can revert the change to the properties file.

**Comment by pkukielka** [comment]
You don't even need to edit property file, just run this:

```
./gradlew -PplatformVersion=2024.1 :runIde.  // just run it once, it will fail too :)
./gradlew -PplatformRuntimeVersion=2024.1 :runIde
```

I know it's not ideal, but the proper solution would most likely require rewriting a bit of what IntelliJ plugin is already doing.

**Comment by dominiccooney** [comment]
@pkukielka that's exactly the behavior that wasn't working for me. I think you can end up in a state where the build product is up to date, but the cache does not contain the runtime version of the plugin.
