### ISSUE TITLE
bug: Document Code may not be filling in the prompt language placeholder

### ISSUE THREAD

**Issue by steveyegge** [sourcegraph/jetbrains#1572]
### Cody Version

5.5.11-nightly

### IDE Information

@danielmarquespt observed that it might be the case that we are not filling in the ${language} for the Document Code prompt, leading to the LLM generating comments in the wrong language.

### Describe the bug

We sometimes get comments from the wrong language generated.  E.g. //-comments in Python, or #-comments in Java.

### Expected behavior

Cody should always generate docs and comments appropriate to the source file's language.

**Comment by danielmarquespt** [comment]
Context: https://sourcegraph.slack.com/archives/C05AGQYD528/p1715878180828269?thread_ts=1715870235.642729&cid=C05AGQYD528

**Comment by dominiccooney** [comment]
AFAIK, document code doesn't inform the LLM of the language so it would be good to test this with a weaker model.

This runs through the shared "edit code" machinery, so we should use science here to check we're making things better not worse with changes here.

FWIW I have not seen this kind of error for a while, although it may be specific to Python…

**Comment by abeatrix** [comment]
I am not able to reproduce this issue on my side, tried to run the document command in Python, TypeScript, Go, and C# files, and they all work as expected. Moreover, we don't use the ${language} placeholder in the document command prompt so I don't think that was the issue before, but we did make some improvement on the tree-sitter queries and pinned the doc command to always use Claude Haiku that might have fixed the original issue. <br><br>@daniel.marques can you let us know if you can still reproduce the issue and if yes, can you share the reproduction steps with us please?
