### ISSUE TITLE
bug: misleading Cody Ignore notification when Agent isn't running

### ISSUE THREAD

**Issue by steveyegge** [sourcegraph/jetbrains#1573]
### Cody Version

5.5.11-nightly

### IDE Information

IntelliJ IDEA 2023.3.6 (Ultimate Edition)
Build #IU-233.15026.9, built on March 20, 2024
Licensed to Steve Yegge
Subscription is active until June 24, 2024.
Runtime version: 17.0.10+1-b1087.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 10
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  editor.minimap.enabled=true
  markdown.open.vcs.log.link=true
Non-Bundled Plugins:
  com.vecheslav.darculaDarkerTheme (1.2.0)
  com.facebook.ktfmt_idea_plugin (1.1.0.49)
  com.jetbrains.space (233.15026.16)
  com.drinchev.projectlabel (1.3.1)
  com.sourcegraph.jetbrains (5.5.11-nightly)
  DevKit (233.15026.24)
  net.ashald.envfile (3.4.2)
  com.intellij.ml.llm (233.15026.24)
  google-java-format (1.22.0.0)
  com.intellij.bigdatatools.core (233.15026.9)
  com.intellij.bigdatatools.binary.files (233.11799.267)
  com.intellij.bigdatatools.rfs (233.15026.9)
  com.intellij.bigdatatools.metastore.core (233.13135.65)
  com.intellij.bigdatatools.spark (233.13135.103)
  com.intellij.bigdatatools.flink (233.13135.103)
  com.github.copilot (1.5.3.5510)
  com.intellij.bigdatatools.zeppelin (233.13135.65)
  com.intellij.bigdatatools.kafka (233.13135.103)
  com.intellij.bigdatatools (233.13135.65)
Kotlin: 233.15026.9-IJ

### Describe the bug

When any of the following occur:

- the Cody Agent fails to start
- the Agent is in the process of starting (including for a few seconds at IDE startup)
- the Agent shuts down and has not yet been restarted

We get the "Cody is Limited -- learn about ignored files" notification.

### Expected behavior

If Cody Ignore is really kicking in, then we should use this notification. But most of the time when I see this message, it is because Agent wasn't running.

This makes it tricky to diagnose, doubly so at on-prem customers. It would be better for us to show the underlying error that resulted in Cody Ignore failing.

### Additional context

This is most likely happening because Cody Ignore is the first thing to fail when Agent is down.

**Comment by dominiccooney** [comment]
Agree that we're going to get a ton of Cody Ignore bug reports which are actually networking, agent startup, etc. bugs. We should give agent a chance to start, and if it isn't healthy show something more accurate and useful.

**Comment by dominiccooney** [comment]
Believe this is fixed in #1651
