### ISSUE TITLE
Cody chat hanging

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#159]
### Installation Information:

I'm on the nightly build (5.2.11078-nightly) and Cody hangs when I enter a question into the chat input. 

### Steps to reproduce:

I could repro logged into both my dotcom account and sourcegraph.sourcegraph. [Loom.](https://www.loom.com/share/9d1f52387ee7425291e5f81a1951f2a9)

### Expected Behaviour:

Cody should generate a response :)

**Comment by mkondratek** [comment]
https://github.com/sourcegraph/jetbrains/pull/163

☝️ this one should fix it.

**Comment by mkondratek** [comment]
Hello @taylorsperry 👋 a lot happened since this issue was raised. I believe that it's fixed by https://github.com/sourcegraph/jetbrains/pull/172. 

Can you confirm that you do not experience this issue anymore? 🙏

**Comment by taylorsperry** [comment]
Not seeing this behavior anymore, thank you, @mkondratek !
