### ISSUE TITLE
bug: We seem to be sending the whole document to the Agent on every streaming notification

### ISSUE THREAD

**Issue by steveyegge** [sourcegraph/jetbrains#1602]
### Cody Version

5.5.12-nightly

### IDE Information

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 11, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 10
Non-Bundled Plugins:
    com.sourcegraph.jetbrains (6.0-localbuild)

Kotlin: 221-1.6.20-release-285-IJ5080.210

### Describe the bug

Rik, @abeatrix and I were debugging client/agent messages and noticed along the way that we seem to be sending textDocument/didChange notifications (or something else that includes the whole file contents) on every single streaming notification, because we never turn off our bulk document listener during streaming.

This works, but is a huge performance penalty for nothing; we believe it's a contributor to the overall sluggishness, and may even contribute to exacerbating existing race conditions.

### Expected behavior

I think we should disable textDidChange notifications to to the agent while streaming responses are in progress.

**Comment by steveyegge** [comment]
@olafurpg -- I've assigned this to you because you just did some work last night on optimizing what we're sending. Feel free to close if this is working as intended.

**Comment by olafurpg** [comment]
Fixed in https://github.com/sourcegraph/jetbrains/pull/1607 with followup PRs

- https://github.com/sourcegraph/jetbrains/pull/1615 fixed major regression, thank you @pkukielka ! 🙇🏻 
- https://github.com/sourcegraph/jetbrains/pull/1611
