### ISSUE TITLE
Disabling Cody breaks remaining Sourcegraph plug-in "Open in Sourcegraph Web" functionality

### ISSUE THREAD

**Issue by morgangauth** [sourcegraph/jetbrains#162]
### Installation Information:

Plugin version 5.2.9816
Seen in IntelliJ

### (optional) Error message or idea.log output:

<img width="380" alt="Screenshot 2023-12-04 at 4 06 42 PM" src="https://github.com/sourcegraph/jetbrains/assets/113058716/de22ca75-4ff1-4586-bf75-ded10fcf6973">

### Steps to reproduce:

1. Log in to Cody
2. Right-click a symbol and go to Sourcegraph>Open Selection in Sourcegraph Web
** Verify that a browser window opens the symbol in configured instance of Sourcegraph
3. Disable Cody by going to Settings>Sourcegraph & Cody > uncheck "Enable Cody"
5. Repeat step 2
** No browser window opens and the following error and message pop up 
<img width="380" alt="Screenshot 2023-12-04 at 4 06 42 PM" src="https://github.com/sourcegraph/jetbrains/assets/113058716/6ad734ad-76ca-463f-92d0-153d6eb0ad8d">

5. Restart IntelliJ
6. Repeat step 2 again
** Note that no browser window opens but the error message and pop up from step 5 do not appear
7. Re-Enable Cody (following step 3 but ensure "Enable Cody" is checked)
8. Note that browser window from previous actions immediately opens

### Expected Behaviour:

Steps 5 and 6 should behave the same as 2, regardless of Cody being enabled or not. 
If there is an error, in step 8, the browser tabs should not reopen without context as some time may have passed between attempting the action and re-enabling Cody.

**Comment by taylorsperry** [comment]
I can repro, thank you for reporting, @morgangauth. Are you aware of any customers who've reported this issue? 

Unless we've been hearing about it from users, I think this can wait until after Cody Enterprise GA since it seems like the impact is on users who don't have Cody enabled. But we should fix afterwards.

**Comment by morgangauth** [comment]
@taylorsperry This was initially reported by a customer https://github.com/sourcegraph/accounts/issues/3993, but have not heard of any other customers being affected AFAIK

**Comment by taylorsperry** [comment]
Super, thank you for the context!
