### ISSUE TITLE
bug: org.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/jetbrains#1623]
### Cody Version

main

### IDE Information

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 11, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 10
Non-Bundled Plugins:
    com.sourcegraph.jetbrains (6.0-localbuild)

Kotlin: 221-1.6.20-release-285-IJ5080.210

### Describe the bug

error when running document code

### Expected behavior

n/a

### Additional context

[idea.log](https://github.com/sourcegraph/jetbrains/files/15424453/idea.log)

Document command crashes when cursor is on a single line:

https://github.com/sourcegraph/jetbrains/assets/51868853/97a26942-1510-4326-be0a-79d39242d776

Edit command command crashes when cursor is on a single line:

https://github.com/sourcegraph/jetbrains/assets/51868853/ba7dfe8d-eb5c-4cd6-84ee-6e7faebf56e1

**Comment by odisseus** [comment]
I couldn't reproduce this on commit 0d2079dd45763275c5cf0b3d5dc4b9d9fe87d9f1. If this problem still occurs, can you attach the trace log?

**Comment by kalanchan** [comment]
@odisseus try placing just your cursor on a line then running a command, it'll break

**Comment by odisseus** [comment]
Apparently this happens only when the file type is not supported (e.g. .ts files in IDEA CE).

**Comment by odisseus** [comment]
The response that causes this exception looks like this:
```
{
  "jsonrpc": "2.0",
  "id": "12",
  "result": {
    "range": {
      "start": {
        "line": 87,
        "character": 0
      },
      "end": {
        "line": 108,
        "character": 9007199254740991
      }
    }
  }
}
```

The problem is that the big number cannot fit into a Java Integer. We could solve this issue in the client by using Long everywhere, but the actual problem lies within the agent, because offsets of such size are very unlikely to exist in a source file.

**Comment by kalanchan** [comment]
@odisseus Beatrix has a PR (https://github.com/sourcegraph/jetbrains/pull/1642) that handles the crashes well. So it seems like this problem only happens in non supported file types and we can just ignore the error?

**Comment by odisseus** [comment]
This might be a symptom of some deeper problem on the agent side. However, if this happens only in unsupported file types, we can just ignore it for now.

Interestingly, the same big number (9007199254740991) appears several times with different edits being applied to different files by different users. See https://github.com/sourcegraph/cody-issues/issues/372, https://github.com/sourcegraph/cody-issues/issues/380.

**Comment by pkukielka** [comment]
That number is `Number.MAX_SAFE_INTEGER`. We need to check where in `Cody` it is used incorrectly (or with the assumption we do not handle properly). I expect it is this place:

`vscode/src/editor/utils/index.ts` in `Cody`:

```
typescriptexport async function getSmartSelection(
    documentOrUri: vscode.TextDocument | vscode.Uri,
    target: vscode.Position
): Promise<vscode.Selection | undefined> {
    const document =
        documentOrUri instanceof vscode.Uri
            ? await vscode.workspace.openTextDocument(documentOrUri)
            : documentOrUri

    const [enclosingFunction] = execQueryWrapper({
        document,
        position: target,
        queryWrapper: 'getEnclosingFunction',
    })

    if (enclosingFunction) {
        const { startPosition, endPosition } = enclosingFunction.node
        // Regardless of the columns provided, we want to ensure the edit spans the full range of characters
        // on the start and end lines. This helps improve the reliability of the output.
        const adjustedStartColumn = document.lineAt(startPosition.row).firstNonWhitespaceCharacterIndex
        const adjustedEndColumn = Number.MAX_SAFE_INTEGER                //  <<===================== [ HERE ]
        return new vscode.Selection(
            startPosition.row,
            adjustedStartColumn,
            endPosition.row,
            adjustedEndColumn
        )
    }

    return getSelectionAroundLine(document, target.line)
}
```

**Comment by pkukielka** [comment]
`export async function getSmartSelection(
    documentOrUri: vscode.TextDocument | vscode.Uri,
    target: vscode.Position
): Promise<vscode.Selection | undefined> {
    const document =
        documentOrUri instanceof vscode.Uri
            ? await vscode.workspace.openTextDocument(documentOrUri)
            : documentOrUri

    const [enclosingFunction] = execQueryWrapper({
        document,
        position: target,
        queryWrapper: 'getEnclosingFunction',
    })

    if (enclosingFunction) {
        const { startPosition, endPosition } = enclosingFunction.node
        // Regardless of the columns provided, we want to ensure the edit spans the full range of characters
        // on the start and end lines. This helps improve the reliability of the output.
        const adjustedStartColumn = document.lineAt(startPosition.row).firstNonWhitespaceCharacterIndex
        const adjustedEndColumn = Number.MAX_SAFE_INTEGER
        return new vscode.Selection(
            startPosition.row,
            adjustedStartColumn,
            endPosition.row,
            adjustedEndColumn
        )
    }

    return getSelectionAroundLine(document, target.line)
}`
