### ISSUE TITLE
JetBrains: "Document Code" command is not working for SG02 Enterprise account.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1636]
### Cody Version

v5.5.14-nightly

### IDE Information

IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  org.jetbrains.plugins.hocon (2023.1.0)
  PythonCore (233.14475.9)
  com.soywiz.korge.korge-intellij-plugin (4.0.4)
  com.sourcegraph.jetbrains (5.5.14-nightly)
Kotlin: 233.14475.28-IJ

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Enterprise user(SG02 account)
3. Open any source code file and select a code snippet
4. Go to Commands and run "Document Code" command

### Observed behavior:
Nothing happed and the command will not produce any output, in the idea log a 400 error occurred,
```
2024-05-25 00:44:45,312 [ 373110]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ EditProvider:onError: Sourcegraph Cody Gateway: unexpected status code 400: {
  "error": {
    "message": "Invalid value: ''. Supported values are: 'system', 'assistant', 'user', 'function', and 'tool'.",
    "type": "invalid_request_error",
    "param": "messages[0].role",
    "code": "invalid_value"
  }
}
```

### Expected behavior

"Document Code" command should run successfully.

### Additional context

**Full idea log** 
[idea.log](https://github.com/sourcegraph/jetbrains/files/15439169/idea.log)

**Video link:**
https://drive.google.com/file/d/13j-xL9pu9C0vE3aHPdz0ifJ5-RvJQzcs/view?usp=drive_link

**Comment by dominiccooney** [comment]
<img src="https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/d6e102a8-a5f5-47d8-bb47-0efaa091246c/1c9be0ec-c3b7-4d8a-beb7-5f947dff840d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy9kNmUxMDJhOC1hNWY1LTQ3ZDgtYmI0Ny0wZWZhYTA5MTI0NmMvMWM5YmUwZWMtYzNiNy00ZDhhLWJlYjctNWY5NDdkZmY4NDBkIiwiaWF0IjoxNzE2OTAzMjIzLCJleHAiOjMzMjg3NDYzMjIzfQ.YIZKPk3fpWbHbmjnUmCQNFtzgVsE7Hq6zEW33ElIFaI " alt="Screenshot 2024-05-28 at 22.32.53.png" width="1325" height="623" />

This is working for me at tip of trunk 12167331689275ba0ef0ad0074ac8ea7fa6e7552
