### ISSUE TITLE
bug: Inline edit gives unexpected results when the cursor is on a method name

### ISSUE THREAD

**Issue by odisseus** [sourcegraph/jetbrains#1639]
### Cody Version

cb65dd17fb394c42585e6ccbcf5af181ac7ab41d

### IDE Information

IDEA CE 2022.1

### Steps to reproduce

1. Open a Java class which has some methods.
2. Place the cursor in the middle a method name. There should be no selected text range.
3. Invoke edit code with this prompt:
   "Change this method name to hello"
4. Cody would generate a new method from scratch, and place the generated snippet right in the middle of the existing method name.

### Expected behavior

The results should be the same as if the whole method name was selected — that is, the existing method should be renamed. For comparison, try invoking the same prompt when the cursor is placed on an empty line inside a class.

This issue doesn't occur every time, but it seems to be quite frequent.

**Comment by mkondratek** [comment]
Tried on the latest main & a kotlin file - I cannot reproduce it

**Comment by odisseus** [comment]
Could not reproduce in version 3dc045135dd30c95843e426f509e45a4d8695610.
