### ISSUE TITLE
[Reported by customer] Invalid authentication data error when adding account from private sourcegraph instance

### ISSUE THREAD

**Issue by Sa1to** [sourcegraph/jetbrains#164]
### Installation Information

It appeared in Rider version 2023.2.2, cody version 5.2.9816

### Describe the bug

https://sourcegraph.slack.com/archives/C059N5FRYG3/p1701298810556439

Unfortunately i wasn't able to reproduce it with s2.

### Expected behavior

User should be able to authenticate with private sourcegraph instance.

**Comment by taylorsperry** [comment]
I believe @Sa1to was looking into this (based on the thread), but I don't know if any progress was made. Since it impacts users being able to authenticate, I'm marking it as a P0.

**Comment by taylorsperry** [comment]
@Sa1to do you know if this is still an issue? Pretty old at this point!

**Comment by mkondratek** [comment]
I do not think so. No one reported any troubles with authentication in over a month already. Let's close it. We will create a new issue if needed.
