### ISSUE TITLE
bug: Edit/Retry after Document Code is exhibiting bad behavior

### ISSUE THREAD

**Issue by steveyegge** [sourcegraph/jetbrains#1643]
### Cody Version

6.0-localbuild

### IDE Information

IntelliJ IDEA 2022.1 (Community Edition) Build #IC-221.5080.210, built on April 11, 2022 Runtime version: 11.0.14.1+1-b2043.25 aarch64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. macOS 14.5 GC: G1 Young Generation, G1 Old Generation Memory: 752M Cores: 10 Non-Bundled Plugins:     com.sourcegraph.jetbrains (6.0-localbuild)  Kotlin: 221-1.6.20-release-285-IJ5080.210

### Describe the bug

1. open a Java source file and select an entire method or function with the mouse.
2. execute Document Code and wait for it to succeed and show the Accept group.
3. Leave the selection alone and don't change anything; click Edit & Retry
4. optionally, scroll to the end of the prompt text in the dialog and add "Use //-syntax" at the end of the prompt.
5. click Edit Code to execute the retry

You may need to repeat this a couple of times. I am not sure if changing the instructions (step 4) matters. I have seen it fail without changing the prompt.

After a few tries, Cody will begin exhibiting symptoms of some underlying bug. I have seen:

- the Agent typescript runtime crashed with a heap allocation error (twice), possibly out of memory.
- duplicated code or extra code added after the doc string
- overwriting the existing code beneath the doc string
- automatic acceptance of the output (it was correct output) without showing the Accept lens group

These look similar to symptoms of de-syncing, but we verified that it is not a desyncing problem using the panic flag.

### Expected behavior

Edit/Retry should always work seamlessly with no extra insertions, deletions, or automatic acceptance.

### Additional context

We did run this with `cody-agent.panic-when-out-of-sync=true`, so we know it isn't a desync problem, despite the similarities in symptoms.

**Comment by dominiccooney** [comment]
We made a lot of improvements here over the intervening period, just tried this in 7.0.0-nightly and it was rock solid. Like ROCK ⭐  SOLID 👨‍🎤 🤘  so closing this one.
