### ISSUE TITLE
JetBrains: Tick is shown for the chat context even though there are few repo deselected.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1678]
### Cody Version

v5.5.18-nightly

### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
idea.plugin.protoeditor (233.13135.65)
DevKit (233.14015.152)
gherkin (233.11799.165)
cucumber-java (233.11799.196)
PythonCore (233.14015.106)
com.sourcegraph.jetbrains (5.5.18-nightly)
Kotlin: 233.14015.106-IJ

### Describe the bug

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Enterprise user
3. Have few remote repo added for chat context
4. Expand the repo list and deselect few repo
5. Click on "New Chat" button

### Observed behavior:
The checkbox for "Enhanced Context N repositories" is showing "tick" even though few repo are unselected by user.

### Expected behavior

The "Enhanced Context N repositories" should display [-] instead of "tick" as there are one or more repo deselected by user.

### Additional context

**Video link:**

https://drive.google.com/file/d/1jsK7_UvlVqgJQU8s6LMvr363dyeUYVzy/view?usp=drive_link

**Comment by taylorsperry** [comment]
this falls into the "feature not a bug" category. i'm going to close for now, but @danielmarquespt this is feedback on multirepo ux, for potential post-ga cleanup.

**Comment by dominiccooney** [comment]
+1 to @taylorsperry 's comment... the Enhanced Context checkbox has an effect even if there are no repositories underneath it, it controls whether we will include files open in tabs, etc.
