### ISSUE TITLE
Investigate and fix the issue with chat hanging

### ISSUE THREAD

**Issue by mkondratek** [sourcegraph/jetbrains#169]

**Comment by mkondratek** [comment]
The first mention in the slack has been made on Dec 5, 10:48PM

**Comment by mkondratek** [comment]
The second encounter: Dec 6, 3:52PM (slack thread)

**Comment by mkondratek** [comment]
@exigow reported the same issue on Dec 8, 00:24AM

**Comment by mkondratek** [comment]
@Sa1to noted:
> I think its because no repo context is selected

**Comment by mkondratek** [comment]
We are looking at it with @exigow. Our findings so far:

We believe that the issue is related to https://github.com/sourcegraph/jetbrains/pull/161 (cc @chwarwick). 

It does not seem that the linked PR introduced the issue (the issue has been there already). 

For sure it is a matter of whether there is a file opened on the project opening or not.

**Comment by chwarwick** [comment]
@mkondratek  @exigow  Any chance it could be related to this https://github.com/sourcegraph/cody/issues/1989. I've been experiencing this on the VS Code side where chat hangs because it's stuck awaiting the context fetching.

**Comment by exigow** [comment]
@chwarwick, possible, but we are still working on finding the cause. We are testing various theories (AWT thread vs main thread) and we noticed some improvement after ensuring that the CodyFileEditorListener is running on the same thread as the CodyAgent, but this causes other problems / strange hallucinations appear in the chat.

**Comment by exigow** [comment]
Important observation: 

![image](https://github.com/sourcegraph/jetbrains/assets/5013708/8a860133-77e3-41ec-b418-6a949f9d86f1)

The current version of the chat does not display the list of files sent to the agent (this `Read X files`). This might also be related. I am tracing now this regression.

**Comment by exigow** [comment]
I traced the changes with bisect and it turns out that the regression was introduced in https://github.com/sourcegraph/jetbrains/pull/111.

```txt
1. 731017d1 Use LogicalPosition for calculating selection range instead VisualPosition (#109) - OK
2. bbb93a8a Fix passing value of CompletionEvent's  'multiline' instead of 'multilineMode' for telemetry data (#121) - OK
3. 1c8a71d7 Bump hardcoded version to prevent issues with version recognition by IDE (#74) - NOT OK
4. d94a5ed2 shorten prefix and update template messaging (#113) - OK
5. ee7e7777 Extract components from CodyToolWindowContent (#76) - OK
6. 1024b220 Migrate common package to Kotlin (#122) - OK
7. e5d60697 Add a visual hint when the user has exceeded the rate limit (#111) - NOT OK
8. 23f901db Increasing autocompletion trigger sensitivity (#129) - OK
9. e5d60697 Add a visual hint when the user has exceeded the rate limit (#111) - NOT OK (additional check)
10. 23f901db Increasing autocompletion trigger sensitivity (#129) - OK (additional check)
11. e5d60697 Add a visual hint when the user has exceeded the rate limit (#111) - NOT OK (additional check)
```

It seems that the changes do not directly cause this bug, but along with them, the **Cody version was bumped** - I think that is the main cause.

This requires further investigation.

**Comment by mkondratek** [comment]
It seems that the same root cause is responsible for the troubles with the sourcegraph links reported by @vdavid 🕵️ 

![image](https://github.com/sourcegraph/jetbrains/assets/19799111/672e6fec-8a7e-4f2f-ba1d-930770b8aff8)

**Comment by mkondratek** [comment]
it should be fixed now with 303 ☝️
