### ISSUE TITLE
JetBrains: Chat autoscrolled to latest message when new message tokens are generated.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1692]
### Cody Version

v5.5.18-nightly

### IDE Information

PyCharm 2023.3.4 (Community Edition)
Build #PC-233.14475.56, built on February 26, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (5.5.18-nightly)

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Pro user
3. Fill the Chat with messages until the scrollbar appears
4. Scroll up. Latest message should be not visible or partially visible
5. Add new message and hit enter

### Observed behavior:
Chat is auto-scrolled to latest message.

### Expected behavior

User should stay at the same position in chat and read older messages without interruptions.

### Additional context

**Video link:**

https://drive.google.com/file/d/1pdk1OosTqfg2FWgUovQCpNnXGliebL5o/view?usp=drive_link

**Comment by mkondratek** [comment]
Hi Jay 👋  This is what we wanted. Here is the issue: [We should auto-scroll to the bottom when submitting a new message](https://github.com/sourcegraph/jetbrains/issues/340#top).

IMHO the present behavior is intuitive and I like it.

We can change it. @danielmarquespt, wdyt?
