### ISSUE TITLE
feedback: Allow set of custom chat prompts

### ISSUE THREAD

**Issue by lwasyl** [sourcegraph/jetbrains#1697]
### Installation Information

com.sourcegraph.jetbrains (5.5.10)

### Share your feedback

It'd be useful to be able to either provide custom prompt for the chat (e.g. asking it to be less verbose and mostly focus on code, to limit output) or even to be able to provide different starting prompts and to trigger chat with either of them, depending on the use case

**Comment by kalanchan** [comment]
we have introduced [prompt library](https://sourcegraph.com/docs/cody/capabilities/commands), feel free to give it a try
