### ISSUE TITLE
bug: Paragraph text not wrapped, no horizontal scrollbars with long generated code lines

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/jetbrains#1698]
### Cody Version

6.0.0-nightly

### IDE Information

IntelliJ IDEA 2024.1.1 (Ultimate Edition)
Build #IU-241.15989.150, built on April 29, 2024
Licensed to Sourcegraph / Dominic Cooney
Subscription is active until February 28, 2025.
Runtime version: 17.0.10+1-b1207.14 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
Kotlin analyzer version: 2.0.0-ij241.15989-9
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  markdown.open.vcs.log.link=true
  llm.generate.commit.summary=true
Non-Bundled Plugins:
  com.jetbrains.space (241.15989.9)
  google-java-format (1.22.0.0)
  DevKit (241.15989.199)
  io.intellij-sdk-thread-access (2.2.1)
  com.intellij.ml.llm (241.15989.156)
  com.jetbrains.packagesearch.intellij-plugin (241.0.9)
  com.sourcegraph.jetbrains (6.0.0-nightly)
Kotlin: 241.15989.150-IJ

### Describe the bug

When Cody generates long lines of code, the following paragraphs wrap at that extended line length so you can't read them. There's no horizontal scrollbar so you can't scroll to see them.

![Screenshot 2024-05-30 at 16 52 21](https://github.com/sourcegraph/jetbrains/assets/55120/38324baf-a51f-4685-a13e-0f6fa14e772b)

### Expected behavior

- Paragraphs wrap to the width of the sidebar
- There's a horizontal scrollbar, or wrapping?, so you can read the generated code

**Comment by odisseus** [comment]
Looks like our Markdown renderer has a problem with code blocks inside a list. Here's an example:

> Show me a bulleted list of operations to implement Forth, and under each bullet show me some Java code illustrating implementation approaches.

```
Implementing Forth, a stack-based programming language, in Java can be achieved by following these operations:

1. **Stack Implementation**
   - Use a `java.util.Stack` or create a custom stack implementation.
   - Example using `java.util.Stack`:
     ```java
     Stack&lt;Object&gt; stack = new Stack&lt;&gt;();
     stack.push(10); // Push value 10 onto the stack
     Object value = stack.pop(); // Pop the top value from the stack
     ```
```

**Comment by dominiccooney** [comment]
Here's [another prompt](https://sourcegraph.slack.com/files/U02RM5BJ7NU/F0774T6FTDE/wide_cody_prompt) from @vdavid which produces the scrolling problem without a bulleted list.

**Comment by rohanmoore** [comment]
Is this issue being actively worked on?
