### ISSUE TITLE
Cody chat has no context information

### ISSUE THREAD

**Issue by mkondratek** [sourcegraph/jetbrains#170]
When asking the chat about the code the responses are out of context. 

![Image](https://github.com/sourcegraph/jetbrains/assets/19799111/8f3db96e-02f3-4160-a356-9cb307cf4cc6)

**Comment by mkondratek** [comment]
> Important observation:
> 
> ![image](https://private-user-images.githubusercontent.com/5013708/288815857-8a860133-77e3-41ec-b418-6a949f9d86f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NzE0MDMsIm5iZiI6MTcwMTk3MTEwMywicGF0aCI6Ii81MDEzNzA4LzI4ODgxNTg1Ny04YTg2MDEzMy03N2UzLTQxZWMtYjQxOC02YTk0OWY5ZDg2ZjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMTc0NTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGMzMGEwMjY2MDhiNzI1ZGZkYjZiMTQ3Mjg4YzJlMjIzM2IyZTAzNGI5ZjY3MWM4MjgyNTM1NjEzYzExNDNhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FW7hUX7Oa9g0BmU63LTm6rG5NUXMLhd4QkUpGBNCSAw)
> 
> The current version of the chat does not display the list of files sent to the agent (this `Read X files`). This might also be related. I am tracing now this regression.

> I traced the changes with bisect and it turns out that the regression was introduced in #111.
> 
> ```
> 1. 731017d1 Use LogicalPosition for calculating selection range instead VisualPosition (#109) - OK
> 2. bbb93a8a Fix passing value of CompletionEvent's  'multiline' instead of 'multilineMode' for telemetry data (#121) - OK
> 3. 1c8a71d7 Bump hardcoded version to prevent issues with version recognition by IDE (#74) - NOT OK
> 4. d94a5ed2 shorten prefix and update template messaging (#113) - OK
> 5. ee7e7777 Extract components from CodyToolWindowContent (#76) - OK
> 6. 1024b220 Migrate common package to Kotlin (#122) - OK
> 7. e5d60697 Add a visual hint when the user has exceeded the rate limit (#111) - NOT OK
> 8. 23f901db Increasing autocompletion trigger sensitivity (#129) - OK
> 9. e5d60697 Add a visual hint when the user has exceeded the rate limit (#111) - NOT OK (additional check)
> 10. 23f901db Increasing autocompletion trigger sensitivity (#129) - OK (additional check)
> 11. e5d60697 Add a visual hint when the user has exceeded the rate limit (#111) - NOT OK (additional check)
> ```
> 
> It seems that the changes do not directly cause this bug, but along with them, the **Cody version was bumped** - I think that is the main cause.
> 
> This requires further investigation.

Findings from @exigow (https://github.com/sourcegraph/jetbrains/issues/169)

**Comment by mkondratek** [comment]
This is the Cody commit:
```
459fd0cd8d5c90f450d4ea121255ea1bb6c5b44f
```

Since this commit the context read files are not included. 

https://github.com/sourcegraph/cody/pull/1706

hah. it makes sense 😅

**Comment by olafurpg** [comment]
@mkondratek Some context here on how to troubleshoot the problem https://sourcegraph.slack.com/archives/C059N5FRYG3/p1702029835872099

**Comment by mkondratek** [comment]
(cc @abeatrix)

**Comment by mkondratek** [comment]
I limited the changes to this single file and change:

https://sourcegraph.com/github.com/sourcegraph/cody@18b56f527dfed147c39edf3e38c8230cd080323d/-/blob/lib/shared/src/chat/transcript/interaction.ts?L64

**Comment by mkondratek** [comment]
https://github.com/sourcegraph/cody/pull/2211

**Comment by adampatterson** [comment]
Is it worth opening another issue for this? I can't get Cody worked fine before the holidays December 15th, and for the past hour have been getting warnings about no Context messages.

**Comment by mkondratek** [comment]
Hello @adampatterson 👋 

Thanks for sharing your experience with this issue. It makes me think that it's origin is somewhere deeper (probably LLM). I cannot remember for sure but I'd rather say that I have seen it even before Dec 15th. I tried to bisect the agents git history but I managed to get the same problem even months ago.


We are on it. Good point that the issue should not be closed yet. It was closed prematurely by one of the PRs that may help.

**Comment by adampatterson** [comment]
@mkondratek no problem!

I'm not sure if it's related but I noticed that the CPU usage goes way up when I open the side panel. No action needed ( for me ).  Since you mentioned the LLM it made me think that it was working at indexing the code base or something.

The Sourcegraph twitter account said that the desktop app is no longer supported. I know that it was using PostgreSQL.  If the app is no longer needed is the extension still using PostgreSQL?

**Comment by mkondratek** [comment]
@adampatterson, you are right about the history. The plugin (extension) does not use PostreSQL.

**Comment by mkondratek** [comment]
@adampatterson, we have not been seeing this issue anymore. I am closing it. 😌 

We hope Cody helps you with your work 🚀  If you find something new or have some suggestions feel free to post a new issue 👋

**Comment by adampatterson** [comment]
Oh yes, the latest updates have made a huge difference!
