### ISSUE TITLE
JetBrains: Keyboard shortcut is not working for "Edit Code..." command.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1709]
### Cody Version

v6.0.0-nightly and v6.0.1-nightly

### IDE Information

IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  org.jetbrains.plugins.hocon (2023.1.0)
  PythonCore (233.14475.9)
  com.soywiz.korge.korge-intellij-plugin (4.0.4)
  com.sourcegraph.jetbrains (6.0.1-nightly)
Kotlin: 233.14475.28-IJ

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Open any source code file and position your caret in the editor and type `ctrl+shift+enter`

### Observed behavior:
"Edit Code..." window will not opened

### Expected behavior

"Edit Code..." window should open correctly with keyboard short cut.

### Additional context

N/A

**Comment by mkondratek** [comment]
I know it's a report for Windows but I verified macOs and it works on it. So it is Windows specific.

**Comment by dominiccooney** [comment]
Ctrl-Shift-Enter is "complete statement" on Windows, so maybe we can't use that binding. 

Windows-Shift-Enter might be nice, but I'm not sure how to refer to it. I noticed nothing in the default keymap \[1\] uses "meta", and JetBrains doesn't map the Windows key to meta by default anyway \[2\]

\[1\] [https://github.com/JetBrains/intellij-community/tree/master/platform/platform-resources/src/keymaps](https://github.com/JetBrains/intellij-community/tree/master/platform/platform-resources/src/keymaps)

\[2\] [https://intellij-support.jetbrains.com/hc/en-us/community/posts/206374219-What-is-the-meta-key-in-windows](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206374219-What-is-the-meta-key-in-windows)

**Comment by dominiccooney** [comment]
Based on feedback from @pkukielka that we should design a cohesive keymap for Windows, assigning this to @daniel.marques.

**Comment by danielmarquespt** [comment]
More details here.<br><br>I made and end to end review. It also proposes changes to the mac keymap to create continuity between the platforms.<br><br>Pretty much everything Cody related starts with a CTRL + ALT (OPTION) + KEY

<br><br>[Keyboard Shortcuts](https://linear.app/sourcegraph/document/keyboard-shortcuts-2f8747a22530)

**Comment by jafin** [comment]
Ctrl Shift Enter does not work on windows (11) in Rider either.
(tested using Cody Nightly  6.0.6) 

Remapping it to something else (i.e. Ctrl-Alt-Shift-Enter) appears to work fine.

**Comment by mkondratek** [comment]
@steveyegge, can you please take a look here? is it fixed be https://github.com/sourcegraph/jetbrains/pull/1782?
