### ISSUE TITLE
feedback: 我是专业版用户，但聊天有限制，我认为我是能无限聊天的

### ISSUE THREAD

**Issue by heidis168** [sourcegraph/jetbrains#1716]
### Installation Information

我是专业版用户，但聊天有限制，我认为我是能无限聊天的

### Share your feedback

我是专业版用户，但聊天有限制，我认为我是能无限聊天的

### Additional context (logs, images, etc)

我是专业版用户，但聊天有限制，我认为我是能
![image](https://github.com/sourcegraph/jetbrains/assets/167956337/abc1dd52-c14f-4a64-8341-11f548eccac1)
无限聊天的

**Comment by chenkc805** [comment]
Hello @semao168 -

What's your sourcegraph username so I can look into this for you?

**Comment by heidis168** [comment]
136449189

**Comment by semao168** [comment]
136449189@qq.com

**Comment by heidis168** [comment]
麻烦解决聊天限制问题

**Comment by heidis168** [comment]
用户名是136449189

**Comment by chenkc805** [comment]
Hello semao, I'm not seeing that username in our database. Could you share the associated email address with this account?

**Comment by heidis168** [comment]
136449189@qq.com 这是我邮件

**Comment by heidis168** [comment]
![1](https://github.com/sourcegraph/jetbrains/assets/167956337/132f97c3-b4e6-4ada-9103-625f6487bcc0)
![2](https://github.com/sourcegraph/jetbrains/assets/167956337/fb58bc53-afa4-49b7-a625-3fbe9de88abe)

**Comment by chenkc805** [comment]
Hello,<br><br>We have reviewed your account and found you to be in violation of our [Acceptable Use Policy](https://sourcegraph.com/terms/aup) and your account was banned.<br>Because of this, your account has been cancelled and no refund will be issued.<br><br>Regards,<br>Kevin
