### ISSUE TITLE
bug: Some of the Edit actions are not possible to rollback using Ctrl+Z

### ISSUE THREAD

**Issue by pkukielka** [sourcegraph/jetbrains#1720]
### Cody Version

6.0.3

### IDE Information

PyCharm 2024.1.2
Windows

### Describe the bug

1. Create unittests using `Generate Unit Tests`
2. Select all content and click `Document Code`
3. Run `Edit Code...` and ask it to "remove all comments"

Now try to bring back comments using Ctrl + Z. It does not work.

### Expected behavior

Ctrl + Z should always undo most recent text edit.

**Comment by odisseus** [comment]
I think that each undo action affects only the most recent edit, which is usually just a few bytes long. If the Cody request has generated a lot of code, the total number of edit actions might exceed the IntelliJ's undo stack.

**Comment by dominiccooney** [comment]
This does undo-redo as one big chunk now.

The one case where we don't: Generate unit tests, as we stream the test content into the new file. That produces incremental edits and you have to undo-undo-undo through them. But the specific issue here is fixed.
