### ISSUE TITLE
bug: JetBrains Cody doesn't work on Windows ARM64

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/jetbrains#1722]
### Cody Version

Build of 2d4b31a7bd8f201d02ed1a8df8dd763805bb519a which is 6.0.3

### IDE Information

IntelliJ IDEA 2024.1.2 (Community Edition)
Build #IC-241.17011.79, built on May 21, 2024
Runtime version: 17.0.11+1-b1207.24 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (6.0-localbuild)
Kotlin: 241.17011.79-IJ

### Describe the bug

On Windows on ARM64, nothing works. Running commands gives Cody Context Filters error messages. And the logs contain this:

```
2024-05-31 03:02:39,457 [  15008]   WARN - #com.sourcegraph.cody.agent.CodyAgent - Unable to start Cody agent
com.sourcegraph.cody.agent.CodyAgentException: Node binary not found at path C:\Users\Dominic Cooney\AppData\Roaming\JetBrains\IdeaIC2024.1\plugins\Sourcegraph\agent\node-win-arm64.exe
2024-05-31 03:02:39,544 [  15095]   WARN - #com.sourcegraph.cody.agent.CodyAgent - Failed to execute call to agent
java.util.concurrent.ExecutionException: com.sourcegraph.cody.agent.CodyAgentException: Failed to start Cody agent
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        ...
```

There is, indeed, no node-win-arm64.exe binary at that path.

### Expected behavior

Expect Cody to work on Windows arm64

**Comment by dominiccooney** [comment]
There are Windows ARM64 node binaries ([here, for example](https://nodejs.org/en/blog/release/v20.12.2)) but they're not in the archive we download from GitHub.

**Comment by olafurpg** [comment]
I believe we can just run the x86 Node binary on ARM64 Windows computers.

**Comment by dominiccooney** [comment]
Good point, also an option.
