### ISSUE TITLE
bug:  Unable to navigate using left cursor when selecting a block and cursor at end of line, started with new inline shortcut hint feature (nightly 6.0.5+)

### ISSUE THREAD

**Issue by jafin** [sourcegraph/jetbrains#1798]
### IDE Information

JetBrains Rider 2024.1.3
Build #RD-241.17011.166, built on June 8, 2024
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
.NET Core v8.0.1 x64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 32
Registry:
  ide.experimental.ui=true
  ide.mac.bigsur.window.with.tabs.enabled=false
  ide.new.project.model.index.case.sensitivity=true

### Bug Description

Only appeared since nightly 6.0.5/6.0.6  Previous nightly and stable are fine.

Attempt to describe the issue.
press `Shift-End` to select line,  
Then attempting to refine the selection using `Shift-Left arrow` results in no action., i.e. the selection scope is ignoring the key.  Shift-Up/Down work ok.

pressing `Shift-Left` then `Shift-Right` also works, so it appears only when cursor is at line end does it break the usage of `Shift-Left`.

Disabling Cody plugin fixes the problem (or reverting to a non 6.0.5/6.0.6 version)

~~Unsure why the shortcut key is being shown to the right of the line?~~ This I believe has only started appearing in the 6.0.5+ nightly.

**EDIT**: I see this is a new "feature", and is expected. **Hopefully it can be toggled on/off** for the user as I personally find it not useful to always be shown.

This is 6.0.6 with cursor at end of line, cannot navigate left using shift-left arrow.

![image](https://github.com/sourcegraph/jetbrains/assets/127927/0d250a3d-c1b4-42d1-9e6f-5322ad359772)

This is 6.0.4 with cursor at end of line, can navigate using shift-left.  Also no shortkey notification visible.
![image](https://github.com/sourcegraph/jetbrains/assets/127927/7551dc8e-69c3-46c2-8a2b-485bfa755c97)

**Comment by jafin** [comment]
Perhaps related to this change in 6.0.5  https://github.com/sourcegraph/jetbrains/commit/aed272c4d6bbf55c42f535ee92f4a58fb10fe66d

Just an observation, the cursor is at the end of the hint when it breaks, but the EOL is actually after the semicolon.
![image](https://github.com/sourcegraph/jetbrains/assets/127927/c3e04745-4ab2-45b4-becd-11ad93ec01a9)

**Comment by jafin** [comment]
Not the original problem, but related to this new hint feature.  In 6.0.7 nightly, it is showing the hint twice?

![image](https://github.com/sourcegraph/jetbrains/assets/127927/1549547e-0c0d-477e-84e3-39b6bb0d9f7a)

**Comment by gauravkumar37** [comment]
+1 I raised the same bug in discord: https://discord.com/channels/969688426372825169/1254102402760572928

Plus on the aesthetics part, not a big fan of the shortcut key being shown every single time, After a couple of times, it's just distracting. IntelliJ IDEs don't have this a a norm (as opposed to VSCode I think).
At least give an option to disable this in settings.

+ @danielmarquespt @steveyegge @mkondratek

**Comment by jafin** [comment]
The Duplicate shortcut is no longer showing in `6.0.8-nightly`.   ❤️ 
The original issue about `Shift+left arrow` selection is still broken though. 😢

**Comment by mkondratek** [comment]
Hello @jafin 👋 thank you for your detailed report 💟 

Yes, the duplicate shortcut issue has been fixed in 6.0.8 (it was presented N number of times where N was the number of projects opened 😅).

I do confirm the other problem. I can reproduce the behaviour with shift-left not working.

We will take care of it soon.

**Comment by gauravkumar37** [comment]
Thanks @mkondratek 
Is it also going to be put behind a config so that we can turn off if we don't want to see the shortcut.

**Comment by sqs** [comment]
Yes, this is annoying. Sorry about this. We will make it not show all the time. (We might show it very occasionally when we think it would be helpful based on the context, but that would come later and we'll just remove it for now.)
