### ISSUE TITLE
Refresh the subscription tab on the account change

### ISSUE THREAD

**Issue by mkondratek** [sourcegraph/jetbrains#180]
> There is one more nice to have - but we can deliver it later:
> We could show the sub tab depending on the account type when it changes. For now when I change to the account that is eligible to see sub tab the tab does not appear. I assume you can add some logic there:
> https://sourcegraph.com/github.com/sourcegraph/jetbrains/-/blob/src/main/kotlin/com/sourcegraph/cody/config/CodyPersistentAccountsHost.kt?L29%3A1-30%3A1

_Originally posted by @mkondratek in https://github.com/sourcegraph/jetbrains/pull/171#pullrequestreview-1777050489_

**Comment by mkondratek** [comment]
closing in favour of https://github.com/sourcegraph/jetbrains/pull/208

**Comment by Sa1to** [comment]
Fixed by https://github.com/sourcegraph/jetbrains/pull/208
