### ISSUE TITLE
JetBrains: "Pro" label is missing from few LLMs for Free users.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1815]
### IDE Information

IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  org.jetbrains.plugins.hocon (2023.1.0)
  PythonCore (233.14475.9)
  com.soywiz.korge.korge-intellij-plugin (4.0.4)
  com.sourcegraph.jetbrains (6.0.8-nightly)
Kotlin: 233.14475.28-IJ

### Bug Description

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free user
3. Open new chat and check the LLM dropdown

### Observed behavior:
"Pro" label is missing from few of the LLMs.

### Additional context

**Screenshot:**

![Pro_label_missing_LLM_Dropdown](https://github.com/sourcegraph/jetbrains/assets/158482423/33d3055e-b2da-47b2-bb6e-e8f6fd042acc)

**Comment by mkondratek** [comment]
expected. closing
