### ISSUE TITLE
bug: Selecting LLM model is not avaliable

### ISSUE THREAD

**Issue by haraldreingruber-dedalus** [sourcegraph/jetbrains#1817]
### IDE Information

RustRover 2024.1.3
Build #RR-241.17011.175, built on June 22, 2024
Licensed to Dedalus HealthCare GmbH

Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
  debugger.attach.dialog.enabled=true
  ide.experimental.ui=true
  org.toml.json.schema=false
  org.rust.lang.cfg.attributes=false
  transferSettings.vscode.onlyCargoToml=true
  llm.ai.assistant.toolwindow.activation.on.start=false
  terminal.new.ui.show.promotion=false
Non-Bundled Plugins:
  GLSL (1.24)
  com.intellij.properties (241.14494.150)
  de.docs_as_co.intellij.plugin.diagramsnet (0.2.5)
  com.jetbrains.edu (2024.5-2024.1-1069)
  org.asciidoctor.intellij.asciidoc (0.42.2)
  com.intellij.ml.llm (241.17011.2)
  com.sourcegraph.jetbrains (6.0.3)
  mobi.hsz.idea.gitignore (4.5.3)
  WGSL (0.0.31)

### Bug Description

According to the docs, it should be possible to select the LLM model: ![expected](https://storage.googleapis.com/sourcegraph-assets/Docs/llm-select-jb.png)

But for me, this field is not available:
![actual](https://github.com/sourcegraph/jetbrains/assets/74898239/c1c42aff-007f-4d0f-81b7-636cd74dc084)

**Comment by kalanchan** [comment]
closing this as this should be fixed
