### ISSUE TITLE
bug: Autocomplete doesn't always show the entire auto-complete text

### ISSUE THREAD

**Issue by mdhender** [sourcegraph/jetbrains#1822]
### IDE Information

GoLand 2024.1.4
Build #GO-241.18034.61, built on June 20, 2024
Licensed to Michael Henderson
Subscription is active until January 31, 2025.
Runtime version: 17.0.11+1-b1207.24 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 16000M
Cores: 10
Metal Rendering is ON
Registry:
  ide.completion.variant.limit=500
  suggest.all.run.configurations.from.context=true
Non-Bundled Plugins:
  org.asciidoctor.intellij.asciidoc (0.42.2)
  com.sourcegraph.jetbrains (6.0.8-nightly)
  com.intellij.tailwindcss (241.17890.21)

### Bug Description

The auto-complete text is sometimes obscured.

![Screenshot 2024-06-26 at 10 57 04 AM](https://github.com/sourcegraph/jetbrains/assets/11139100/05ca7a09-d495-49a9-9ca5-1363d5a6a5dd)

(reported https://community.sourcegraph.com/t/jb-plugin-sometimes-doesnt-show-the-entire-auto-complete-text/609)

**Comment by kalanchan** [comment]
should be fixed on version 7 and above
