### ISSUE TITLE
bug: The "to Edit" popup is too hard to dismiss when selecting to the end of a line

### ISSUE THREAD

**Issue by mdhender** [sourcegraph/jetbrains#1823]
### IDE Information

GoLand 2024.1.4
Build #GO-241.18034.61, built on June 20, 2024
Licensed to Michael Henderson
Subscription is active until January 31, 2025.
Runtime version: 17.0.11+1-b1207.24 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 16000M
Cores: 10
Metal Rendering is ON
Registry:
  ide.completion.variant.limit=500
  suggest.all.run.configurations.from.context=true
Non-Bundled Plugins:
  org.asciidoctor.intellij.asciidoc (0.42.2)
  com.sourcegraph.jetbrains (6.0.8-nightly)
  com.intellij.tailwindcss (241.17890.21)

### Bug Description

I’m using JB Goland with v6.0.8 nightly. When I highlight to the end of the line, Cody displays a wee box with “Ctrl + Shift + glyph to Edit.” That box requires too much effort to dismiss and breaks my concentration. I have to press Escape or the RIGHT ARROW to make it go away. The LEFT ARROW does nothing. When I’m just trying to change code from the caret to the end of the line, it’s annoying.

![Screenshot 2024-06-26 at 10 00 09 AM](https://github.com/sourcegraph/jetbrains/assets/11139100/ce38a66b-b741-4445-a275-b5e915bf446b)

I think that this is a bug and not a feature since I can’t turn it off and it prevents me from easily changing code from the caret to the end of the line.

Other than that, I really like the feature.

(https://community.sourcegraph.com/t/the-to-edit-popup-is-too-hard-to-dismiss-in-jetbrains-ide/607)

**Comment by mdhender** [comment]
May be a duplicate of #1798.

**Comment by jafin** [comment]
+1 Agree, the extra "shortcut tip" can be annoying for users who already know these shortcuts.  
Please make it configurable on/off to give users the option of seeing it.

**Comment by kalanchan** [comment]
we'll work on this next, thanks for reporting!

**Comment by mdhender** [comment]
Fixed with v6.0.14 of the plugin.
