### ISSUE TITLE
JetBrains: Commands are only executed with 'Claude 3 Sonnet' for free users.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1826]
### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  idea.plugin.protoeditor (233.13135.65)
  DevKit (233.14015.152)
  gherkin (233.11799.165)
  cucumber-java (233.11799.196)
  PythonCore (233.14015.106)
  com.sourcegraph.jetbrains (6.0.8-nightly)
Kotlin: 233.14015.106-IJ

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with a Free account
3. Open Cody and start a new chat with a different LLM i.e. `Mixtral 8x7B Mistral`
4. Ask Cody a question and verify that Cody uses the LLM of your choice in step-3
5. Now, open any source code file, and run a command i.e. `Explain Code`

### Observed behavior:
Cody will respond with `Claude 3 Sonnet` instead of `Mixtral 8x7B Mistral`

### Expected behavior:
Cody should respond using `Mixtral 8x7B Mistral` LLM. 

### Note:
This is working fine for Pro users.

### Additional context

**Video link:**

https://drive.google.com/file/d/1ZK-QOrPucZ-1svf1httJ86DuCf9-Xmcd/view?usp=drive_link

**Comment by mkondratek** [comment]
@pkukielka, could you take a look? is it correct that using Claude 3 Sonnet only is the expected and OK behaviour?

**Comment by kalanchan** [comment]
@jay-fibi going to close this as we;re using webviews, if you still notice it please file a new issue
