### ISSUE TITLE
JetBrains: "No API Key" error occurred when running command with Claude 2.0, 2.1 or Instant 

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1827]
### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
idea.plugin.protoeditor (233.13135.65)
DevKit (233.14015.152)
gherkin (233.11799.165)
cucumber-java (233.11799.196)
PythonCore (233.14015.106)
com.sourcegraph.jetbrains (6.0.8-nightly)
Kotlin: 233.14015.106-IJ

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with a Pro account
3. Open any source code file and choose `Claude 2.0 by Anthropic` as LLM
4. Run a command `Execute Code`

### Observed behavior:
Error occurred with "No API key" message

### Expected behavior:
Cody should respond correctly

### Additional context

**Video link:**

https://drive.google.com/file/d/1hDameluAYJCOxsSBZe-Rkdc7yfMVNOtk/view?usp=drive_link

**Comment by mkondratek** [comment]
https://sourcegraph.com/-/editor?remote_url=github.com%2Fsourcegraph%2Fcody&branch=main&file=lib%2Fshared%2Fsrc%2Fmodels%2Findex.ts&start_row=21&start_col=0&end_row=23&end_col=29&editor=JetBrains&version=v6.0.8-nightly

I looks like the models are deprecated now. We are not prepared for llm deprecation. My guess is the old chats should be in readonly mode. We should filter out the deprecated models from the dropdown.

**Comment by mkondratek** [comment]
We should implement a similar behaviour (upgrade llm):
https://sourcegraph.com/-/editor?remote_url=github.com%2Fsourcegraph%2Fcody&branch=main&file=vscode%2Fsrc%2Fmodels%2FmodelMigrator.ts&start_row=10&start_col=0&end_row=28&end_col=0&editor=JetBrains&version=v6.0.8-nightly
