### ISSUE TITLE
bug: Too Many Notifications Upon Startup After Install

### ISSUE THREAD

**Issue by tedyoung** [sourcegraph/jetbrains#1833]
### IDE Information

IntelliJ IDEA 2024.1.4 (Ultimate Edition)
Build #IU-241.18034.62, built on June 20, 2024
Licensed to Ted Young
Subscription is active until November 20, 2024.
Runtime version: 17.0.11+1-b1207.24 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Non-Bundled Plugins:
  socrates.tabshifter (0.34)
  org.nik.presentation-assistant (1.0.15)
  AceJump (3.8.19)
  com.intellij.plugins.all_hallows_eve.colorscheme (241.14494.150)
  com.intellij.spring.websocket (241.14494.158)
  de.platon42.cajon (1.14)
  PlantUML integration (7.10.1-IJ2023.2)
  org.asciidoctor.intellij.asciidoc (0.42.2)
  MetricsReloaded (1.12)
  com.sourcegraph.jetbrains (6.0.3)
  org.b333vv.metricstree (2024.1.0)
  com.intellij.java.rareRefactorings (241.14494.158)
  com.intellij.plugins.html.instantEditing (241.15989.10)
Kotlin: 241.18034.62-IJ

### Bug Description

After installing for the first time, Cody creates many notifications (see screenshot) when the IDE was restarted with a bunch of projects re-open. I'm guessing it's 1 per project that I have open.

Cody: 6.0.3

![image](https://github.com/sourcegraph/jetbrains/assets/382660/0371f327-fdbb-4c94-b73f-d34ef11be015)

**Comment by jdorfman** [comment]
@tedyoung is this still happening?

**Comment by kalanchan** [comment]
should be fixed on version 7 and above, feel free to reopen if it is not
