### ISSUE TITLE
bug: Sourcegraph Cody Gateway: unexpected status code 403: {"error":"Cody Gateway access not enabled"}

### ISSUE THREAD

**Issue by rosca-cristian** [sourcegraph/jetbrains#1834]
### IDE Information

Webstorm. 2024.1.5

### Bug Description

⚠ Error performing this action  Please retry sending your message. If you tried to run a command, try it again. If the issue persists, please create a support ticket.  Error: Sourcegraph Cody Gateway: unexpected status code 403: {"error":"Cody Gateway access not enabled"}
![image](https://github.com/sourcegraph/jetbrains/assets/106065975/5a2e61b0-5630-4c7b-9926-c3c2cec0565b)

### Additional context

Stacktrace:
```text
Sourcegraph Cody Gateway: unexpected status code 403: {"error":"Cody Gateway access not enabled"}

```

**Comment by arnab710** [comment]
Same issue in VScode.

**Comment by Iravata** [comment]
I am facing this issue too in vscode.

**Comment by ackmiecik** [comment]
Ditto, any way to get around it?

**Comment by soarb** [comment]
Just started getting this today in vscode as well. It usually clears itself on re-requests eventually but not at the moment :(

**Comment by oscar-edomex** [comment]
Same here

Seems there are multiple reported. 

#2162 
#2113
#2047 
#1752

**Comment by Mahmoussam** [comment]
same here

**Comment by kalanchan** [comment]
this should've been fixed and was intermittent, feel free to reopen if there are still issues!

**Comment by colevr1** [comment]
today happened again, any workaround to have it back working?
