### ISSUE TITLE
JetBrains: Opening some specific older chats from chat history redirects user to /cody/subscription page

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1839]
### IDE Information

PyCharm 2023.3.4 (Community Edition)
Build #PC-233.14475.56, built on February 26, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (6.0.10-nightly)

### Bug Description

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with a Pro account
3. Go to Chat History and open chats one by one

### Observed behavior:
While opening some chats, user will be redirected to `/cody/subscription` page.

### Expected behavior:
User should not be redirected to  `/cody/subscription` page

### Additional context

**Video link:**

https://drive.google.com/file/d/1ajR7laFq38sVZmLzLs5xnGieGD5FeYH0/view?usp=drive_link

**Comment by kalanchan** [comment]
@jay-fibi going to close this as we're using webviews now, please re-file if its still a problem
