### ISSUE TITLE
JetBrains: Current tier is stuck at "Loading..." in My Account tab on restarting IDE

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1841]
### IDE Information

PyCharm 2023.3.4 (Community Edition)
Build #PC-233.14475.56, built on February 26, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (6.0.10-nightly)

### Bug Description

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with a Pro account
3. Close the IDE and reopen it
4. Open Cody window and check `My Account` tab

### Observed behavior:
Tier status for "Current tier" will never load and stuck at "Loading..."

### Expected behavior:
Current tier should show the correct value.

### Additional context

**Video link:**

https://drive.google.com/file/d/1qS_MANbTYrS4oycascPfwseFZCskgyb2/view?usp=drive_link

**Comment by mkondratek** [comment]
Tested with IC 2022.1 - unable to repro. Needs further investigation.

**Comment by mkondratek** [comment]
I was able to reproduce it with PC 2023.3 as in the report. Fixing...
