### ISSUE TITLE
JetBrains: "Cody can't edit the file..." notification generated twice while deleting a Generate Unit Test file

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1853]
### IDE Information

PyCharm 2023.3.3 (Community Edition)
Build #PC-233.13763.11, built on January 26, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (6.0.11-nightly)

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with a Pro account
3. Open any source code file and choose any LLM
4. Right click to open context menu, and choose Cody > Generate Unit Test
5. Make sure Cody is generating a new file
6. Delete the file while Cody is writing to it

### Observed behavior:
"Cody can'r edit the file" notification generated twice

### Expected behavior:
Only one "Cody can'r edit the file" notification should be generated.

### Additional context

**Video link:**

https://drive.google.com/file/d/10M2VLZbY88yW7Dh5GGmLXyXc1oAy94Uk/view?usp=drive_link

**Comment by mkondratek** [comment]
fixed by https://github.com/sourcegraph/jetbrains/pull/1857
