### ISSUE TITLE
bug: Switching between an enterprise and dotcom accounts breaks the `Subscription` tab

### ISSUE THREAD

**Issue by Gedochao** [sourcegraph/jetbrains#186]
### Installation Information

#IU-233.11799.241 (IDEA IntelliJ Ultimate 2023.3)
nightly Cody plugin: 5.2.12527-nightly

### Describe the bug

1. Log in to an enterprise account in the plugin
2. Go to the Cody toolbar, the `Subscription` tab should not be present.
1. Separately log in to a dotcom account (with the `cody-pro-jetbrains` feature flag enabled)
3. Go to the Cody toolbar, the `Subscription` tab should be there
4. Now go back to account settings and switch back to the Enterprise account.
5. The `Subscription` tab will be gone (as it should).
6. Go to the account settings once more and switch back to the dotcom account.
7. The `Subscription` tab will still be gone, even though it should be back.

### Expected behavior

Switching back and forth between an enterprise account and a dotcom account with the feature flag enabled should not break PLG features (like showing the Subscription tab)

### Additional context (logs, images, etc)

https://github.com/sourcegraph/jetbrains/assets/18601388/2ef1b4a9-ccfb-4f5b-b93b-679c2827433e

**Comment by mkondratek** [comment]
I do confirm. In the latest stable (5.2.12694):
Cody PLG - Pro user ➡️ Cody PLG - Free user 💥 (the tab disappears forever)

I guess it is rather a rare case but let's get it fixed
