### ISSUE TITLE
bug: [Rider] Cody is disabled on this file, by an admin.  This is an enterprise feature but I am a Pro User (rider-cody-nightly-6.0.12) 

### ISSUE THREAD

**Issue by jafin** [sourcegraph/jetbrains#1868]
### IDE Information

JetBrains Rider 2024.1.4
Build #RD-241.18034.76, built on June 24, 2024
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
.NET Core v8.0.1 x64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 32
Registry:
  ide.experimental.ui=true
  ide.mac.bigsur.window.with.tabs.enabled=false
  ide.new.project.model.index.case.sensitivity=true

### Bug Description

Cody is warning with

```
"Cody is disabled on this file"
This feature has been restricted by an Admin.
```

First occurrence of this was seen after installing `Cody AI 6.0.12-nightly`
I have a Pro subscription, Not enterprise. Therefore there can be no enterprise policies/restrictions in place.
This warning seems incorrect

![image](https://github.com/sourcegraph/jetbrains/assets/127927/c446b4ec-683f-4da2-b1be-4f6cb5f3cc21)

**Comment by Nopik** [comment]
I'm getting those as well in Idea. Disabled the notification for whole project, it was too annoying.

**Comment by kalanchan** [comment]
thanks for reporting this, we'll take a look!

@jafin does Cody work at all or is it just the notifications that pop up?

**Comment by Nopik** [comment]
In my case (Idea) Cody works just fine, I do not see any difference. It is just the popup.

**Comment by kalanchan** [comment]
thanks @Nopik! does it only happen on start up and eventually goes away?

**Comment by Nopik** [comment]
It was happening for me for an hour or so, randomly - but usually when I opened new file. It was annoying enough and I eventually disabled that notification completely, not sure if it would go away after a longer time.

**Comment by jafin** [comment]
@kalanchan Mostly at startup from my observation.

**Comment by darthShadow** [comment]
Same on PyCharm 2024.1.4 with Cody 6.0.14. Disabled it after a few minutes of the startup because of too many notifications, so I don't have any long term observations.

**Comment by fyodoriv** [comment]
Same for me, on every file I open. Maybe it's because I'm opening files from a private repo of an organization?

**Comment by justinmilner1** [comment]
@cbrwizard The PR I linked should fix this for people who see it only occasionally - if this is happening on every file, it's likely a different issue. 
Are you an enterprise user? Has this been happening to you consistently even after restart?

**Comment by fyodoriv** [comment]
I am a free user, it's my first time working with Cody and this extension. 
![image](https://github.com/user-attachments/assets/bca4e142-ea9e-4485-a8f0-d4535ac7fbff)

**Comment by justinmilner1** [comment]
@cbrwizard Okay gotcha.

To confirm: This is happening on EVERY file you open, even after restarting extensions?

If you can provide console logs, more info about what 'private repo' refers to, and if you've modified any settings that would be useful.

**Comment by kalanchan** [comment]
should be fixed by above please re-file if it's still a problem

**Comment by fyodoriv** [comment]
This has indeed been fixed for me, thank you!
