### ISSUE TITLE
JetBrains: Guardrail API error occurred for Enterprise user.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1876]
### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  idea.plugin.protoeditor (233.13135.65)
  DevKit (233.14015.152)
  gherkin (233.11799.165)
  cucumber-java (233.11799.196)
  PythonCore (233.14015.106)
  com.sourcegraph.jetbrains (6.0.12)
Kotlin: 233.14015.106-IJ

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with a Enterprise account
3. Open any file and type `generate test` in Cody chat and hit enter
4. Check the code snippet from Cody response

### Observed behavior:
Guardrail API error occurred and failed to check

### Expected behavior:
Guardrail API error should not occur and the code snippet should pass the Guardrail

### Additional context

**Video link:**

https://drive.google.com/file/d/1Tr8jsh9DJrf0VjCX2gkv24YETgpVw38x/view?usp=drive_link

**Comment by jay-fibi** [comment]
Additional node:
I dig further and found that,
1. Login with Cody Free/Pro user
2. Then switch account to Enterprise user
3. Perform above steps given in the bug description

Same issue repro with `6.0.13-nightly`

**Comment by kalanchan** [comment]
On going bug, we'll fix this in a different issue
