### ISSUE TITLE
JetBrains: Cody Ignore notification appear randomly when opening different files

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1877]
### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  idea.plugin.protoeditor (233.13135.65)
  DevKit (233.14015.152)
  gherkin (233.11799.165)
  cucumber-java (233.11799.196)
  PythonCore (233.14015.106)
  com.sourcegraph.jetbrains (6.0.12)
Kotlin: 233.14015.106-IJ

### Bug Description

Platform: macOS

Steps to reproduce:

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with a Pro account
3. Close the IDE and relaunch it
4. Wait for Cody to initialise 
5. Open & close different files and also switch between different LLMs during this step

### Observed behavior:
Cody Ignore notification appear for some random files

### Expected behavior:
Cody Ignore should be disabled for Pro user and only available for Enterprise user

### Additional context

**Video link:**

https://drive.google.com/file/d/19kXGYA_AR7VkmzKCsqkpmKmdTrTyTA7F/view?usp=drive_link

**Comment by kalanchan** [comment]
should be fixed already
