### ISSUE TITLE
bug: unable to get local issuer certificate

### ISSUE THREAD

**Issue by murugesanh** [sourcegraph/jetbrains#1878]
### IDE Information

PyCharm 2023.1.5 (Community Edition)
Build #PC-231.9414.12, built on February 15, 2024
Runtime version: 17.0.10+10-b829.26 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2032M
Cores: 4
Registry:
    editor.focus.mode.color.light=6b727d
    ide.editor.tab.selection.animation=true
    debugger.watches.in.variables=false
    debugger.new.tool.window.layout=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=6b727d

Non-Bundled Plugins:
    net.seesharpsoft.intellij.plugins.csv (3.3.0-231)
    com.sourcegraph.jetbrains (6.0.12)
    ru.meanmail.plugin.requirements (2022.4.1)
    com.millennialmedia.intellibot@lte2000 (0.16.191.8026)
    com.chrisrm.idea.MaterialThemeUI (8.6.4)
    izhangzhihao.rainbow.brackets (2023.3.7)

### Bug Description

unable to use cody from pycharm because of certificate issue

### Additional context

Stacktrace: ```unable to get local issuer certificate```

**Comment by kalanchan** [comment]
going to close this, if this is still an issue feel free to re-open
