### ISSUE TITLE
bug: Sourcegraph Cody Gateway: unexpected status code 400: {"error":"request blocked - if you think this is a mistake, please cont...

### ISSUE THREAD

**Issue by tzutoo** [sourcegraph/jetbrains#1883]
### IDE Information

IntelliJ IDEA 2024.1.4 (Ultimate Edition)
Build #IU-241.18034.62, built on June 21, 2024
You have a perpetual fallback license for this version.
Subscription is active until June 30, 2025.
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 32
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  terminal.new.ui=true
  editor.minimap.enabled=true
  org.toml.json.schema=false
  eslint.additional.file.extensions=svelte
  go.run.processes.with.pty=false
Non-Bundled Plugins:
  com.jetbrains.rust (241.27011.175)
  org.jetbrains.plugins.go-template (241.14494.150)
  com.gafner.giv (2024.1.17)
  org.jetbrains.plugins.go (241.17011.2)
  Pythonid (241.18034.62)
  com.intellij.nativeDebug (241.15989.65)
  com.intellij.aqua (241.18034.82)
  Dart (241.17890.8)
  com.jetbrains.packagesearch.intellij-plugin (241.0.11)
  org.jetbrains.android (241.17011.79)
  com.android.tools.design (241.17011.79)
  io.flutter (80.0.2)
  de.mariushoefler.flutter_enhancement_suite (1.7.1)
  io.plugin.tsnode (2022.11.14-1)
  com.sourcegraph.jetbrains (6.0.12)
Kotlin: 241.18034.62-IJ

### Bug Description

I have tried to signout and signin again, and still face the same problem.

### Additional context

Stacktrace:
```text
Sourcegraph Cody Gateway: unexpected status code 400: {"error":"request blocked - if you think this is a mistake, please contact support@sourcegraph.com and reference this ID: 0dd9a3ab5cb78b8c9e83ebb76e2713bb"}

```

**Comment by mkondratek** [comment]
Hi @tzutoo 👋 we are sorry about the inconvenience you are encountering 🙇‍♂️ 

what are the specific steps to reproduce this error?

**Comment by kalanchan** [comment]
should be fixed, and was intermittent

**Comment by ismayilov750** [comment]
> should be fixed, and was intermittent

Same problem. Do you have fix?

**Comment by mkondratek** [comment]
@ismayilov750, what version of the plugin do you use?

**Comment by ismayilov750** [comment]
My gpt 4o works now.
I have another problem.
I am cody Pro user. my account is ***@***.***
UNABLE TO SEND MESSAGE

You've used all of your chat messages and commands for today.
Learn More

**Comment by mkondratek** [comment]
@ismayilov750, please review your account status in web: https://sourcegraph.com/cody/manage

Also, please make sure you use the latest version of the plugin. 

If you still believe there is an error feel free to open a new GitHub issue 🙏
