### ISSUE TITLE
JetBrains: A closing curly bracket '}' left over when user click on 'Undo' on newly generated unit test

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1885]
### IDE Information

IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  org.jetbrains.plugins.hocon (2023.1.0)
  PythonCore (233.14475.9)
  com.soywiz.korge.korge-intellij-plugin (4.0.4)
  com.sourcegraph.jetbrains (6.0.12)
Kotlin: 233.14475.28-IJ

### Bug Description

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with a Pro account
3. Open any source code file and select code snippet
4. Run command `Generate Unit Tests`
5. Let Cody finish writing unit test file
6. Click on `Undo` button

### Observed behavior:
Closing curly bracket `}` will not be cleared from the file on undo

### Expected behavior:
Everything written by Cody for the file should be undo correctly.

### Additional context

**Video link:**

https://drive.google.com/file/d/1fXDEKQyV1yWEC1c72LsmBn1B-plN3VYs/view?usp=drive_link

**Comment by kalanchan** [comment]
going to close this as we will transition to prompts
