### ISSUE TITLE
bug: self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by androbro** [sourcegraph/jetbrains#1886]
### IDE Information

JetBrains Rider 2024.1.3
Build #RD-241.17011.166, built on June 7, 2024
Licensed to Koen de vulder
Subscription is active until August 22, 2024.
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
.NET Core v8.0.1 x64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 4056M
Cores: 20
Registry:
  ide.experimental.ui=true
  ide.new.project.model.index.case.sensitivity=true
Non-Bundled Plugins:
  com.jetbrains.space (241.17011.48)
  ru.adelf.idea.dotenv (2024.1)
  com.intellij.ml.llm (241.17011.2)
  com.github.dinbtechit.vscodetheme (1.10.10)
  com.sourcegraph.jetbrains (6.0.12)
  com.mallowigi (97.0.0)
  izhangzhihao.rainbow.brackets (2024.2.4-241)

### Bug Description

i switched from github copilot to cody and when i turn on the vpn, i receive this error when trying to chat.
This doesnt happen when i am using copilot or if i am not using the vpn.
This is breaking and would like to get an answer asap or i will be forced to switch to copilot again.

### Additional context

Stacktrace: ```self-signed certificate in certificate chain```

**Comment by mkondratek** [comment]
Hi @androbro, can you please share the full stacktrace? 🙏

**Comment by kalanchan** [comment]
going to close this, if this is still an issue feel free to re-open
