### ISSUE TITLE
bug: Incorrect alert telling me that the file has been excluded from context

### ISSUE THREAD

**Issue by nickgieschen** [sourcegraph/jetbrains#1889]
### IDE Information

Intellij 

### Bug Description

I'm getting the following alert:

<img width="434" alt="2024-07-05_14-44-04" src="https://github.com/sourcegraph/jetbrains/assets/1622224/de60a765-e640-4efb-8797-3f36e3d52ead">

However, I don't have an enterprise account and haven't applied any rules restricting the context. Moroever, autocomplete suggestions *do* appear.

**Comment by mkondratek** [comment]
Hi @nickgieschen 👋 
The notification appears on autocompletes, is that right?
It's explicitly invoked autocompletion (`cmd + \` in the old layout, `control + option + P` in the new layout), right?

**Comment by mkondratek** [comment]
Do you have a Pro or Free tier? Can you provide more details on your environment and repro? 🙏

**Comment by nickgieschen** [comment]
> Hi @nickgieschen 👋 The notification appears on autocompletes, is that right? It's explicitly invoked autocompletion (`cmd + \` in the old layout, `control + option + P` in the new layout), right?

Nope, it happens as soon as I open the file.

I have a Pro account.

Intellij 2024.1.3
MacOS 14.5

**Comment by mkondratek** [comment]
FYI: this should be fixed in the next release - I kindly ask you for some more patience 🙏

**Comment by kalanchan** [comment]
should be fixed already
