### ISSUE TITLE
Error: unable to get local issuer certificat

### ISSUE THREAD

**Issue by kerwinliu00001** [sourcegraph/jetbrains#1897]
### IDE Information

IntelliJ IDEA 2024.1.1 (Community Edition)
Build #IC-241.15989.150, built on April 29, 2024
Runtime version: 17.0.10+1-b1207.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  co.bito.bito-intellij (1.3.4)
  PythonCore (241.15989.150)
  co.fitten.fittencode-intellij-beta (0.10.22-241)
  com.sourcegraph.jetbrains (6.0.12)
  com.alibabacloud.intellij.cosy (1.3.3)
Kotlin: 241.15989.150-IJ

### Bug Description

Error: unable to get local issuer certificat

### Additional context

Stacktrace: ```unable to get local issuer certificate```

**Comment by kalanchan** [comment]
going to close this, if this is still an issue feel free to re-open
