### ISSUE TITLE
bug: self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by sylvain-huppe-infosh** [sourcegraph/jetbrains#1902]
### IDE Information

IntelliJ IDEA 2024.1.4 (Ultimate Edition)
Build #IU-241.18034.62, built on June 20, 2024
Licensed to Sylvain Huppé
Subscription is active until February 19, 2025.
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.jetbrains.space (241.18034.4)
  monokai-pro (1.10)
  com.redhat.devtools.intellij.telemetry (1.1.0.52)
  com.intellij.properties.bundle.editor (241.14494.150)
  net.antelle.intellij-xcode-dark-theme (1.2.4)
  com.robohorse.robopojogenerator (2.3.3)
  Pythonid (241.18034.62)
  com.samdark.intellij-visual-studio-code-dark-plus (2.8)
  com.intellij.javaee.ejb (241.14494.158)
  com.github.camork.fileExpander (2.5)
  woaini.liquibase.plugin (1.3-SNAPSHOT)
  org.asciidoctor.intellij.asciidoc (0.42.2)
  com.yiycf.plugins.mavenDependencyHelper (2.5)
  com.redhat.devtools.intellij.quarkus (1.30.1)
  MavenRunHelper (4.28.0-IJ2022.2)
  io.conceptive.quarkus-intellij-plugin (1.3.2)
  ch.newinstance.plugin.mavendependencychecker (1.11.0)
  com.atlassian.bitbucket.references (2023.1.292)
  org.mapstruct.intellij (1.7.0)
  mdx.js (241.15989.9)
  org.sonarlint.idea (10.7.0.78874)
  com.sourcegraph.jetbrains (6.0.12)
  net.ashald.envfile (3.4.2)
  ru.adelf.idea.dotenv (2024.1)
  com.intellij.wiremock (241.17011.2)
Kotlin: 241.18034.62-IJ

### Bug Description

Works on my MAC OS, but not on my PC.

### Additional context

Stacktrace: ```self-signed certificate in certificate chain```

**Comment by kalanchan** [comment]
going to close this, if this is still an issue feel free to re-open
