### ISSUE TITLE
bug: Sourcegraph Cody Gateway: unexpected status code 400: {"error":"request blocked - if you think this is a mistake, please cont...

### ISSUE THREAD

**Issue by lucifrgzf** [sourcegraph/jetbrains#1904]
### IDE Information

PyCharm 2024.1 (Professional Edition)
Build #PY-241.14494.241, built on March 28, 2024
授权给 kiddy inseams
您有此版本的永久回退许可证。
订阅有效期至 2025年8月1日。
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 6000M
Cores: 16
Registry:
  editor.minimap.enabled=true
Non-Bundled Plugins:
  Batch Scripts Support (1.0.13)
  com.intellij.zh (241.271)
  dev.turingcomplete.intellijdevelopertoolsplugins (4.3.0)
  patrick.kelleter.angular-cli-quick-switch (1.3)
  com.xrath.plugin.fold (1.5.0)
  jebe.liao.JBLHtmlToThymeleaf (1.0)
  com.intellij.ideolog (222.3.2.0)
  com.github.gitofleonardo.simplesqlitebrowser (1.0.7)
  QuickRequest (2024.6.13)
  org.tonybaloney.security.pycharm-security (1.29.0)
  com.ytw88.weappsupport (0.1.0)
  com.sourcegraph.jetbrains (6.0.12)
  cn.yiiguxing.plugin.translate (3.6.2)

### Bug Description

 Please retry sending your message. If you tried to run a command, try it again. If the issue persists, please create a support ticket.  Error: Sourcegraph Cody Gateway: unexpected status code 400: {"error":"request blocked - if you think this is a mistake, please contact support@sourcegraph.com and reference this ID: 387f01a36b662cb839cd817bf59f64eb"} 

### Additional context

Stacktrace:
```text
Sourcegraph Cody Gateway: unexpected status code 400: {"error":"request blocked - if you think this is a mistake, please contact support@sourcegraph.com and reference this ID: 387f01a36b662cb839cd817bf59f64eb"}

```

**Comment by kalanchan** [comment]
going to close this, if this is still an issue feel free to re-open
