### ISSUE TITLE
bug: Cody is disabled on this file popup for .go files in GoLand

### ISSUE THREAD

**Issue by mdhender** [sourcegraph/jetbrains#1917]
### IDE Information

GoLand 2024.1.4
Build #GO-241.18034.61, built on June 20, 2024
Licensed to Michael Henderson
Subscription is active until January 31, 2025.
Runtime version: 17.0.11+1-b1207.24 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 16000M
Cores: 10
Metal Rendering is ON
Registry:
  ide.completion.variant.limit=500
  suggest.all.run.configurations.from.context=true
Non-Bundled Plugins:
  org.asciidoctor.intellij.asciidoc (0.42.2)
  com.sourcegraph.jetbrains (6.0.14)
  com.intellij.tailwindcss (241.17890.21)

### Bug Description

Cody has started showing this popup after upgrading to v6.0.14 of the plugin from the stable channel. I am not using an Enterprise version so this it not all at appropriate. It seems to happen almost every time I open a new tab.

### Additional context

I'm using Pro so this is not at all appropriate. I'd reported something similar before and it turned out to be related to starting up on a slow network. This is showing up almost every time I open a new tab in the editor so it is not the startup issue.

![Screenshot 2024-07-17 at 10 13 13 AM](https://github.com/user-attachments/assets/94838c72-e568-4812-b270-71d6440f29cc)

![Screenshot 2024-07-17 at 10 38 02 AM](https://github.com/user-attachments/assets/508b6597-9f97-48ee-8869-2a9e061bab56)

**Comment by justinmilner1** [comment]
@mdhender Could you provide console output please? If there are timeout messages immediately prior, it is likely the same issue, which I have a PR for [here](https://github.com/sourcegraph/jetbrains/pull/1923), if not, then you're right this is something different.

**Comment by mdhender** [comment]
This does seem to be the same timeout issue.
