### ISSUE TITLE
bug: Rate limiting kicks in for Pro Plan users

### ISSUE THREAD

**Issue by mdhender** [sourcegraph/jetbrains#1920]
### IDE Information

GoLand 2024.1.4
Build #GO-241.18034.61, built on June 20, 2024
Licensed to Michael Henderson
Subscription is active until January 31, 2025.
Runtime version: 17.0.11+1-b1207.24 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 16000M
Cores: 10
Metal Rendering is ON
Registry:
  ide.completion.variant.limit=500
  suggest.all.run.configurations.from.context=true
Non-Bundled Plugins:
  org.asciidoctor.intellij.asciidoc (0.42.2)
  com.sourcegraph.jetbrains (6.0.14)
  com.intellij.tailwindcss (241.17890.21)

### Bug Description

I'm on the Pro plan and still get rate limited on a daily basis. There are many posts on the community forums about this. It seems like the solutions are ad hoc (open a request on yet another web page). This should be resolved because it impacts many users.

### Additional context

![Screenshot 2024-07-18 at 9 44 18 AM](https://github.com/user-attachments/assets/e96c2104-901b-4ae5-8b3f-993932d834c2)

![Screenshot 2024-07-18 at 9 51 35 AM](https://github.com/user-attachments/assets/9b27d0f5-a995-4ed0-bec6-f96a8fe267f7)

**Comment by kalanchan** [comment]
going to close this, if this is still an issue feel free to re-open
