### ISSUE TITLE
JetBrains: New keyboard shortcut keep showing along with messages.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1933]
### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  idea.plugin.protoeditor (233.13135.65)
  DevKit (233.14015.152)
  gherkin (233.11799.165)
  cucumber-java (233.11799.196)
  PythonCore (233.14015.106)
  com.sourcegraph.jetbrains (6.0.15-nightly)
Kotlin: 233.14015.106-IJ

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Open Cody chat window and observed the new keyboard shortcuts
4. Ask anything or run any command

### Observed behavior:
New keyboard shortcut keep showing along with Cody chat messages. 

### Expected behavior:
It should disappear when a question is asked or Cody is responding and shouldn't appear along with chat messages.

### Additional context

**Screenshot:**

<img width="470" alt="Screenshot 2024-07-22 at 10 15 23 PM" src="https://github.com/user-attachments/assets/ef60cb10-0d4b-48d0-832b-c6af82221099">

**Comment by taylorsperry** [comment]
Created Linear issue https://linear.app/sourcegraph/issue/CODY-3025/jetbrains-new-keyboard-shortcut-keep-showing-along-with-messages
