### ISSUE TITLE
JetBrains: Autocompletion is not working for Enterprise account.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1934]
### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
idea.plugin.protoeditor (233.13135.65)
DevKit (233.14015.152)
gherkin (233.11799.165)
cucumber-java (233.11799.196)
PythonCore (233.14015.106)
com.sourcegraph.jetbrains (6.0.15-nightly)
Kotlin: 233.14015.106-IJ

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Open any source code file and write a partial code
4. Trigger Cody autocompletion by `⌃⌥P` shortcut

### Observed behavior:
Autocompletion is not working.

### Expected behavior:
Autocompletion should work correctly.

### Additional context

**Video link:**

https://drive.google.com/file/d/1mIs4-EhQOjh98aWQZNBdB7ienHxBPMze/view?usp=drive_link

**Comment by taylorsperry** [comment]
I'm not able to repro this (autocomplete seems to be fine in intellij for both plg/enterprise for me). [Asked](https://sourcegraph.slack.com/archives/C06R69BC8UW/p1721685545474619) if anyone else was seeing and will create a Linear issue if so.

**Comment by kalanchan** [comment]
going to close this, if this is still an issue feel free to re-open
