### ISSUE TITLE
bug: Change the copy of the JetBrains Cody Pro user limit copy

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/jetbrains#194]
### Installation Information

NA

### Goal
To prevent Cody Pro users from abusing Cody Pro by spamming a bunch of chat/command and autocomplete requests.

### Describe the bug

Current copy:
- Everything under the right hand column (aka Pro messages) in this comment: https://github.com/sourcegraph/jetbrains/pull/166#issuecomment-1843517258

### Expected behavior

Requested copy:
- **Thank you for using Cody so heavily today!** 
- To ensure that Cody can stay operational for all Cody users, please come back tomorrow for more chats, commands, and autocompletes. [Learn more](https://docs.sourcegraph.com/cody/core-concepts/cody-gateway#rate-limits-and-quotas)

**Comment by chenkc805** [comment]
@iskyOS can you give a quick look at the proposed copy and LMK what you think?

**Comment by mkondratek** [comment]
Issue addressed. It is impossible to test it right now b/c of the issue with the agent (PLG Rate limiting error messages are currently broken).
