### ISSUE TITLE
JetBrains: There is no clear way to login to Cody for Free or Pro users.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1942]
### IDE Information

PyCharm 2023.3.3 (Community Edition)
Build #PC-233.13763.11, built on January 26, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (6.0.19-nightly)

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Let the Cody load the welcome screen
3. Check the `Cody Free or Cody Pro` panel
4. Click on `Sign In to Your Enterprise Instance` button

### Observed behavior:
For step-3, there is no login button for Free or Pro users
For step-4, user will be redirected to login to Free or Pro accounts on browser

### Expected behavior:
There should be a clear login button for Free or Pro users.
Clicking on `Sign In to Your Enterprise Instance` button should present a prompt to enter the Enterprise credentials i.e. `Server` and `Token`

### Additional context

**Video link:**

https://drive.google.com/file/d/1zGfYjMw51iN2C2JtOSojijZVsAGiePpN/view?usp=drive_link

**Comment by dominiccooney** [comment]
@jay-fibi , we need your idea.log with reports like this. Thank you for filing this—assigning this to you to add the log.

**Comment by dominiccooney** [comment]
I've started tracking this in CODY-3055.

**Comment by jay-fibi** [comment]
@dominiccooney please find the attached log 
[idea.log](https://github.com/user-attachments/files/16380577/idea.log)
file
