### ISSUE TITLE
JetBrains: Links opened inside Cody window as a web view

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1943]
### IDE Information

PyCharm 2023.3.3 (Community Edition)
Build #PC-233.13763.11, built on January 26, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (6.0.19-nightly)

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Let the Cody load the welcome screen
3. Click on `Terms of Service` or `Privacy Policy` links

### Observed behavior:
A web view of that link will be opened inside Cody window.

### Expected behavior:
User should be redirected on browser for respective links.

### Additional context

**Video link:**

https://drive.google.com/file/d/1PE1wM5w3tankamzSI2pD0XuOmX7P-9GZ/view?usp=drive_link

**Comment by dominiccooney** [comment]
Tracking this in CODY-3054.
