### ISSUE TITLE
JetBrains: Commands panel disappear if user interrupts Cody while responding.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1944]
### IDE Information

PyCharm 2023.3.3 (Community Edition)
Build #PC-233.13763.11, built on January 26, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (6.0.19-nightly)

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Open Cody chat window and ask any question i.e. explain code
4. Click on stop button just before Cody start responding

### Observed behavior:
Commands panel will disappear and never loads

### Expected behavior:
Commands panel and other UI components should be sticky

### Additional context

**Video link:**

https://drive.google.com/file/d/1zPbPKx413NZDd2DcTr9KcPaO2pUpBLlI/view?usp=drive_link

**Comment by dominiccooney** [comment]
Interesting find.

This is timing related. It can also happen in VSCode, but VSCode is faster here so it is less likely to happen.

**Comment by RajatNagoria** [comment]
This issue also repro's when user gives any command for e.g. Explain code and then click New Chat Button

Video link: https://drive.google.com/file/d/1sH6a0hBO0TeHnjc5gbsW4L5V6vGUpYEX/view

**Comment by kalanchan** [comment]
going to close this as we've switched to webviews, feel free to reopen if it's still a problem
