### ISSUE TITLE
JetBrains: Blank chat window opens when user open it multiple times

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1945]
### IDE Information

PyCharm 2023.3.3 (Community Edition)
Build #PC-233.13763.11, built on January 26, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (6.0.19-nightly)

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Click on New Chat button 3-4 times to open more than one chat window

### Observed behavior:
New Chat window will be opened but nothing loads there and showing blank

### Expected behavior:
Chat window should load all the UI components correctly for each new instance.

### Additional context

**Video link:**

https://drive.google.com/file/d/1YP32Xdlh9g88hdFvGkqbPvlMDjkhor4t/view?usp=drive_link

**Comment by dominiccooney** [comment]
We are tracking this in CODY-3015.

**Comment by dominiccooney** [comment]
This has been fixed; the fix will be fixed in the next nightly.
