### ISSUE TITLE
JetBrains: LLM name gets cut if user resize the Cody window

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1946]
### IDE Information

PyCharm 2023.3.3 (Community Edition)
Build #PC-233.13763.11, built on January 26, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (6.0.19-nightly)

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Open Cody chat window and select a long LLM i.e. `Clause 3.5 Sonnet`
4. Resize the Cody window and reduce the width

Observed behavior:
LLM name gets cut and the UI looks messy

Expected behavior:
LLM name along with other UI components should show correctly on resizing the Cody window

### Additional context

**Screenshot:**

<img width="392" alt="Screenshot 2024-07-25 at 12 08 15 AM" src="https://github.com/user-attachments/assets/ecd481f4-7f55-48d9-ac07-2105915fc992">

**Comment by dominiccooney** [comment]
VSCode does the same thing.

@danielmarquespt FYI, might make sense to give the  Recommended badge less real estate and overflow: ellipsis, or do something responsive with a smaller/no recommended chit at small sizes.

![Screenshot 2024-07-25 at 9 17 57](https://github.com/user-attachments/assets/4a1ce398-697d-44fc-a4d1-181ab1789400)
