### ISSUE TITLE
JetBrains: Old login screen appear after removing all accounts.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1947]
### IDE Information

PyCharm 2023.3.3 (Community Edition)
Build #PC-233.13763.11, built on January 26, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (6.0.19-nightly)

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Remove all the accounts configured 

### Observed behavior:
Old login screen appear

### Expected behavior:
New Cody welcome screen should appear 

### Additional context

**Video link:**

https://drive.google.com/file/d/1PN5R5hX89b0BaLXsQqAG84KvRXxJma5L/view?usp=drive_link

**Comment by dominiccooney** [comment]
@jay-fibi , could I get an idea.log for this? 🙏

**Comment by dominiccooney** [comment]
GREAT find, by the way. Your repro video is perfect, I can reproduce this.

I'm also tracking this in CODY-3055 because it will have the same root cause as #1942

**Comment by jay-fibi** [comment]
Attached idea log in the https://github.com/sourcegraph/jetbrains/issues/1942 
If the root cause is same then feel free to close this out.
