### ISSUE TITLE
bug: Sourcegraph Cody Gateway: unexpected status code 400: {"error":"We blocked your request because we detected your prompt to be...

### ISSUE THREAD

**Issue by raparlasiva** [sourcegraph/jetbrains#1949]
### IDE Information

PyCharm 2023.2.7 (Professional Edition)
Build #PY-232.10319.12, built on June 4, 2024
Licensed to Sivasuryateja Raparla
You have a perpetual fallback license for this version.
Subscription is active until June 1, 2025.
Runtime version: 17.0.10+7-b1000.50 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Registry:
    ide.experimental.ui=true

Non-Bundled Plugins:
    net.ashald.envfile (3.4.2)
    com.sourcegraph.jetbrains (6.0.14)

### Bug Description

Getting the below error for anything i type. Even with explain code - i am getting this
⚠ Error performing this action  Please retry sending your message. If you tried to run a command, try it again. If the issue persists, please create a support ticket.  Error: Sourcegraph Cody Gateway: unexpected status code 400: {"error":"We blocked your request because we detected your prompt to be against our Acceptable Use Policy (https://sourcegraph.com/terms/aup). Try again by removing any phrases that may violate our AUP. If you think this is a mistake, please contact support@sourcegraph.com and reference this ID: be22246b3457eadb4977dce5d3b694eb"} 

### Additional context

Stacktrace:
```text
Sourcegraph Cody Gateway: unexpected status code 400: {"error":"We blocked your request because we detected your prompt to be against our Acceptable Use Policy (https://sourcegraph.com/terms/aup). Try again by removing any phrases that may violate our AUP. If you think this is a mistake, please contact support@sourcegraph.com and reference this ID: be22246b3457eadb4977dce5d3b694eb"}

```

**Comment by odisseus** [comment]
Does your project contain anything that can be considered inappropriate? For example, a list of swear words.

Try [ignoring](https://sourcegraph.com/docs/cody/capabilities/ignore-context) files that have such content.

By the way, could you try changing the chat model?

**Comment by chenkc805** [comment]
Thank you for writing in. Our records indicate you're trying to do some session reseting by talking to the LLM, which is not allowed by our safety standards. This resetting may be in the code context you're referencing, if it's not in your prompt. 

If you want to reset a session, we encourage you to open a new chat and start from there. Thank you for being a Cody user!

**Comment by ismayilov750** [comment]
> Thank you for writing in. Our records indicate you're trying to do some session reseting by talking to the LLM, which is not allowed by our safety standards. This resetting may be in the code context you're referencing, if it's not in your prompt.
> 
> If you want to reset a session, we encourage you to open a new chat and start from there. Thank you for being a Cody user!

Request Failed: Sourcegraph Cody Gateway: unexpected status code 400: {"error":"We blocked your request because we detected your prompt to be against our Acceptable Use Policy (https://sourcegraph.com/terms/aup). Try again by removing any phrases that may violate our AUP. If you think this is a mistake, please contact support@sourcegraph.com and reference this ID: 682031308fe2b85c96a679bc24dc31a7"}
