### ISSUE TITLE
JetBrains: New login screen is missing on Windows

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1950]
### IDE Information

PyCharm 2023.3.4 (Community Edition)
Build #PC-233.14475.56, built on February 26, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (6.0.20-nightly)

### Bug Description

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Launch the IDE and wait for Cody to load correctly

### Observed behavior:
Old login screen is shown.

### Expected behavior:
New login screen should be visible.

### Additional context

**Screenshot:**

![image](https://github.com/user-attachments/assets/caee4783-d9ba-4e24-8168-f570d0f7ae1e)

**Comment by jdorfman** [comment]
Thanks @jay-fibi sending this to product.

**Comment by kalanchan** [comment]
going to close this as we switched to webviews, if this is still an issue feel free to re-open
