### ISSUE TITLE
JetBrains: "Settings" button is not working

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1951]
### IDE Information

PyCharm 2023.3.4 (Community Edition)
Build #PC-233.14475.56, built on February 26, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (6.0.20-nightly)

### Bug Description

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Launch the IDE and wait for Cody to load correctly
3. Login to Cody with Free/Pro user
4. Click on "Settings" button

### Observed behavior:
Nothing happens when user click on "Settings" button.

### Expected behavior:
Cody settings should be opened when clicking on that button

### Additional context

**Screenshot:**

![Settings_button_not_woking](https://github.com/user-attachments/assets/84120045-11ab-4911-a234-3673c0720966)

**Comment by jafin** [comment]
Same issue in Jetbrains Rider as well.   (6.0.20-nightly)

**Comment by kalanchan** [comment]
should be fixed in the latest version
