### ISSUE TITLE
JetBrains: File name is not clickable from Cody chat response

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1952]
### IDE Information

PyCharm 2023.3.4 (Community Edition)
Build #PC-233.14475.56, built on February 26, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (6.0.20-nightly)

### Bug Description

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Launch the IDE and wait for Cody to load correctly
3. Login to Cody with Free/Pro user
4. Open any source code file and run a command `Explain Code`
5. Expand the Cody chat context to check the file name used
6. Close the opened source code file and Click on file name from Chat context

### Observed behavior:
Nothing happens when user click on the file name

### Expected behavior:
Respective file should be opened

### Additional context

**Screenshot:**

![image](https://github.com/user-attachments/assets/e6d452c3-d60a-402c-ba6b-7c03a8f5f97d)

**Comment by kalanchan** [comment]
going to close this, if this is still an issue feel free to re-open
