### ISSUE TITLE
JetBrains: Cody is not following the default theme and loads with light theme.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1961]
### IDE Information

IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  org.jetbrains.plugins.hocon (2023.1.0)
  PythonCore (233.14475.9)
  com.soywiz.korge.korge-intellij-plugin (4.0.4)
  com.sourcegraph.jetbrains (6.0.20-nightly)
Kotlin: 233.14475.28-IJ

### Bug Description

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Launch the IDE and wait for Cody to load correctly
3. Login to Cody with Free/Pro user
4. Wait for Cody window to load

### Observed behavior:
Cody will load but shown in a light theme but the theme set in IDE is Dark. Also the UI looks messy.

### Expected behavior:
Cody should follow the IDE theme and the UI should be clean.

### Additional context

**Video link:**

https://drive.google.com/file/d/1an_gZ4MKCNzdzJSDX48JzOZ36zzWjFeU/view?usp=drive_link

**Comment by kalanchan** [comment]
going to close this, if this is still an issue feel free to re-open
