### ISSUE TITLE
bug: missing context in chat responses

### ISSUE THREAD

**Issue by Gedochao** [sourcegraph/jetbrains#198]
### Installation Information

v5.2.12694

### Describe the bug

Cody chat seems to be missing context when answering even very basic questions

### Expected behavior

The context should be recognised by Cody

### Additional context (logs, images, etc)

![image](https://github.com/sourcegraph/jetbrains/assets/18601388/67bd65e2-286b-46ef-8da4-b1a0d08ed6fe)

- may be unblocked by https://github.com/sourcegraph/jetbrains/pull/197

**Comment by pcastelan** [comment]
I've got the same problem. 

I updated Cody last night after work, and now he's acting slow, not giving autocomplete suggestions, and every question I throw at him gets the same answer: `"Unfortunately without seeing any of your actual code or Elasticsearch schema, I do not have enough context to provide etc."`
After this message he even tries to answer with some snippet based on my question, but he's clearly lost. 

In one instance, I copied my code and pasted it in the prompt, and in that case, he gave a better answer.

**Comment by mkondratek** [comment]
@pcastelan, thanks for your update on this issue. This is an important thing to be fixed. We will take care at the very beginning of next week.

**Comment by pkukielka** [comment]
This particular bug is fixed by https://github.com/sourcegraph/jetbrains/pull/217
We are working on fixing all corner cases and bringing that PR into main very soon.

**Comment by mkondratek** [comment]
it should be fixed by #220
