### ISSUE TITLE
JetBrains: Continuous loading is shown when user is switched after giving 'Generate unit Test' command

### ISSUE THREAD

**Issue by RajatNagoria** [sourcegraph/jetbrains#1992]
### IDE Information

**IDE Information**

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
windows11
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
idea.plugin.protoeditor (233.13135.65)
DevKit (233.14015.152)
gherkin (233.11799.165)
cucumber-java (233.11799.196)
PythonCore (233.14015.106)
com.sourcegraph.jetbrains (6.0.22-nightly)
Kotlin: 233.14015.106-IJ

### Bug Description

Platform: windows11

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Select code and Use command "Generate Unit test"
4. Tap on Cody icon in bottom right corner >Tap on manage account
5. Switch to any account > Navigate to code

### **Observed behavior:**
Continuous loading is shown when user is switched after giving 'Generate unit Test' command

### **Expected behavior:**
No loading should be shown

### Additional context

**Video Link:**

https://drive.google.com/file/d/17dOlF2ug5PeonzG_nL1ovQOGkBSJ46Oy/view

**Comment by kalanchan** [comment]
going to close this, if this is still an issue feel free to re-open
