### ISSUE TITLE
 Unclear how to create embeddings index

### ISSUE THREAD

**Issue by jbellis** [sourcegraph/jetbrains#2]
Mousing over the x icon says "repository github.com/datastax/cassandra is not indexed and has no embeddings," but clicking on it does not help and there is nothing relevant in Settings.

![image](https://github.com/sourcegraph/jetbrains/assets/42158/6ef18ef9-58fa-4251-8517-71000795a2b2)

**Comment by taylorsperry** [comment]
Hey, @jbellis. Unfortunately, only the VS Code extension connects to the Cody App, which is why you're not seeing your embeddings in IntelliJ. This is because we're moving away from the dependency on the app and instead prioritizing a one-step solution where you get all your indexing simply from downloading the plugin (whether that's VS Code or a JetBrains IDE). We've just kicked off planning for that, but it's a top priority!

**Comment by jbellis** [comment]
Makes sense. So in the meantime is the plugin just nonfunctional?

**Comment by olafurpg** [comment]
@jbellis Thank you for reporting! The datastax/cassandra repository does not have embeddings on sourcegraph.com so the icon is correct. It's a good point that the plugin should inform the user how to fix the problem, I will bring this up with our design team.

A possible workaround could be to use apache/cassandra instead, which has embeddings available on sourcegraph.com.

For now, the only way to get embeddings for custom repositories with the JetBrains plugin is to connect with an enterprise deployment of Sourcegraph. If you are using VS Code, you can get embeddings for custom repositories without an enterprise deployment by using the Cody App, which is not supported by JetBrains and it's not on our near roadmap to add Cody App support. Instead, we are exploring alternative solutions to support embedding-like functionality without having to install a separate desktop application.

**Comment by danielmarquespt** [comment]
@jbellis Sorry for the late reply.

If the repo is on sourcegraph.com but does not have embeddings it is possible to request embeddings via our [Discord bot](https://discord.gg/5qmwfzv4)

I went ahead and requested embeddings for https://github.com/datastax/cassandra, which are now available


![Image](https://github.com/sourcegraph/jetbrains/assets/7814431/ba58b18c-f8ae-46d7-9dfb-539709489de7)


Like my colleagues replied in this thread, we are exploring easier solutions to enable embeddings of private code

**Comment by serefarikan** [comment]
What is the status of embeddings for private repos for Jetbrains at the moment? The Jetbrains plugin became GA just recently and I'm keen to switch to it over my vs code setup (Cody Pro user here, not enterprise). Is vs code still the only environment for non enterprise users that generates and uses embeddings for private repositories?

**Comment by kalanchan** [comment]
hey @serefarikan, we're working on supporting embeddings and it's still on the roadmap. Apologies for taking it so long on jetbrains. Going to close this as we have more information coming out later
