### ISSUE TITLE
JetBrains: "Applying Edit fails" is shown for fraction of seconds when user tries to ''Generate Unit Test"

### ISSUE THREAD

**Issue by RajatNagoria** [sourcegraph/jetbrains#2005]
### IDE Information

PyCharm 2024.1.4 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
idea.plugin.protoeditor (233.13135.65)
DevKit (233.14015.152)
gherkin (233.11799.165)
cucumber-java (233.11799.196)
PythonCore (233.14015.106)
com.sourcegraph.jetbrains (6.0.22-nightly)
Kotlin: 233.14015.106-IJ

### Bug Description

Platform: Windows 11

**Steps to reproduce:**

1. Have Cody plugin installed in your PyCharm editor
2. Login to Cody with Free/Pro user
3. Make sure user have code written 
4. Select code and give command 'Generate Unit Test'

### Observed behavior:
Applying edit fails message is shown for fraction of seconds

### Expected behavior:
Edit should be applied without any error

### Additional context

**Note:**

- After Code is applied wait for sometime and then click UNDO & Observed
- After Pressing Undo also edit doesn't get deleted

**Video Link:**

https://drive.google.com/file/d/1Ekvi339-dDnwlivcB48gC8PMy7DQSRpj/view

**Comment by pkukielka** [comment]
@RajatNagoria I was not able to reproduce this.
Have you seen it only once or is it more frequent behaviour?

**Comment by RajatNagoria** [comment]
@pkukielka It is more frequently repro for me also It looks like windows specific issue can you try on windows
