### ISSUE TITLE
JetBrains: "Connection closed without receiving any events" error occurred for Claude 3 Opus

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#2020]
### IDE Information

IntelliJ IDEA 2024.2 (Community Edition)
Build #IC-242.20224.300, built on August 7, 2024
Runtime version: 21.0.3+13-b509.4 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.3
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  DevKit (242.20224.159)
  PythonCore (242.20224.300)
  idea.plugin.protoeditor (242.20224.155)
  gherkin (242.20224.159)
  com.jetbrains.space (242.20224.155)
  cucumber-java (242.20224.159)
  com.sourcegraph.jetbrains (6.0.25-nightly)
Kotlin: 242.20224.300-IJ

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Select `Claude 3 Opus LLM`
4. Open any source code file and perform `Explain Code` command

### Observed behavior:
`Connection closed without receiving any events` error occurred

### Expected behavior:
Cody should answer for `Explain Code` command

### Additional context

**Video link:**

https://drive.google.com/file/d/1VIUOyhafjlq0VIANpUnox1FwdaXgkFq0/view?usp=drive_link

Attaching logs 
[idea.log](https://github.com/user-attachments/files/16553576/idea.log)

**Comment by pkukielka** [comment]
It was caused by Anthropic outage as mentioned on the status page for Aug 8:
https://status.anthropic.com/
