### ISSUE TITLE
bug: Sourcegraph Cody Gateway: unexpected status code 403: {"error":"Cody Gateway access not enabled"}

### ISSUE THREAD

**Issue by mahz-other** [sourcegraph/jetbrains#2046]
### IDE Information

PyCharm 2024.1.3 (Professional Edition)
Memory: 2048M
Cores: 32
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  DBN (3.4.4179.0)
  name.kropp.intellij.makefile (241.14494.150)
  net.seesharpsoft.intellij.plugins.csv (3.4.0-241)
  net.plpgsql.ideadebugger (241.0.1)
  net.ashald.envfile (3.4.2)
  ru.adelf.idea.dotenv (2024.1)
  com.sourcegraph.jetbrains (6.0.25)

### Bug Description

⚠ Error performing this action  Please retry sending your message. If you tried to run a command, try it again. If the issue persists, please create a support ticket.  Error: Sourcegraph Cody Gateway: unexpected status code 403: {"error":"Cody Gateway access not enabled"} 

**Error: Sourcegraph Cody Gateway: unexpected status code 403: {"error":"Cody Gateway access not enabled"}** 

### Additional context

Stacktrace:
```text
Sourcegraph Cody Gateway: unexpected status code 403: {"error":"Cody Gateway access not enabled"}

```

**Comment by miguelhisojo** [comment]
This bug is duplicated, will close it
