### ISSUE TITLE
JetBrains: educate new users how to use autocomplete

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/jetbrains#207]
Currently, when users install the plugin they see no instructions on how to use autocomplete. We should display `GotItTooltip` with instructions on how to interact with autocomplete via Tab, Alt-Backslash, Alt-SquareBrackets. The GitHub Copilot plugin has similar functionality that we can use for inspiration.

**Comment by mkondratek** [comment]
done by https://github.com/sourcegraph/jetbrains/pull/1339
