### ISSUE TITLE
JetBrains: "Edit Code" button is not working from Commands.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#2082]
### IDE Information

IntelliJ IDEA 2024.2 (Community Edition)
Build #IC-242.20224.300, built on August 7, 2024
Runtime version: 21.0.3+13-b509.4 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.3
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  DevKit (242.20224.159)
  PythonCore (242.20224.300)
  idea.plugin.protoeditor (242.20224.155)
  gherkin (242.20224.159)
  com.jetbrains.space (242.20224.155)
  cucumber-java (242.20224.159)
  com.sourcegraph.jetbrains (6.0.30-nightly)
Kotlin: 242.20224.300-IJ

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Go to `Commands` and click on `Edit Code`

### Observed behavior:
It does nothing when clicking on `Edit Code`

### Expected behavior:
Clicking on `Edit Code` should open the popup for `Edit Code with Cody`

### Additional context

**Screenshot:**

<img width="1470" alt="Screenshot 2024-08-21 at 2 29 03 AM" src="https://github.com/user-attachments/assets/a0f4dc18-6cfd-43e6-a344-065dd73c1a8f">

**Comment by taylorsperry** [comment]
Closing because this is captured in https://linear.app/sourcegraph/issue/CODY-3238/cant-trigger-edit-command-from-sidebar
