### ISSUE TITLE
JetBrains: Apply button is missing for Enterprise user

### ISSUE THREAD

**Issue by RajatNagoria** [sourcegraph/jetbrains#2091]
### IDE Information

IntellJ IDEA 2024.1.4 (Community Edition)
Build #PC-233.13763.11, built on January 26, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
com.sourcegraph.jetbrains (6.0.30)

### Bug Description

Platform: Windows

**Steps to reproduce:**
1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Enterprise user
3. Open Chat snippet and search for anything

### Observed Behavior:
Apply button is missing for Enterprise user

### Expected behavior:
Apply should be shown for enterprise user

### Additional context

**Video link:** https://drive.google.com/file/d/172AkR7-me6DSPBsFd6S2IlFOGbmdMLxW/view

**Comment by mkondratek** [comment]
I tried this one. It works. Possibly it got fixed already. closing
