### ISSUE TITLE
JetBrains: Signing out from app will redirects user to new login screen and relaunching the IDE will automatically signed in.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#2092]
### IDE Information

PyCharm 2023.3.3 (Community Edition)
Build #PC-233.13763.11, built on January 26, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (6.0.30-nightly)

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB PyCharm editor
2. Login to Cody with Free/Pro user
3. Open Cody window and click on `Account` tab
4. Click on `Sign Out` button and observed Issue-1 below
5. Close the IDE and reopen it and observed Issue-2 below

### Observed behavior:
Issue-1: New login screen will appear instead of old one
Issue-2: Sign Out will not invalidate the token and user signed in automatically on relaunch the IDE.

### Expected behavior:
Old login screen should appear on log out and it should invalidate the token so user has to login in again.

### Additional context

**Video link:**

https://drive.google.com/file/d/1tkTo-XoeB0_9w-7uH480mJXNTtw4ZKn7/view?usp=drive_link

**Comment by pkukielka** [comment]
Fixed in 6.0.32-nightly

**Comment by jay-fibi** [comment]
Reopening this as I am still able to repro the second part of the bug with 7.0.0 stable build.
Cody shows logged in after signing out and relaunching the IDE. 
The session should be invalidated on sign out. 

Ref. video link - https://drive.google.com/file/d/1rXPCvIqZLyKExPguHfxPDjGkO2QsSmTR/view?usp=drive_link

**Comment by RajatNagoria** [comment]
Issue is fixed in Latest 7.0.12
