### ISSUE TITLE
JetBrains: Request Failed: Sourcegraph Cody Gateway: unexpected status code 400 error is shown after clicking Public knowledge only 

### ISSUE THREAD

**Issue by RajatNagoria** [sourcegraph/jetbrains#2104]
### IDE Information

IntellJ IDEA 2024.1.4 (Community Edition)
Build #PC-233.13763.11, built on January 26, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
com.sourcegraph.jetbrains (6.0.31)

### Bug Description

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Enterprise user
3. Make sure there is already file available in source code file
4. Start new chat >  Make sure current repository and current source file is shown
5. Send the request using that > Scroll down and Click on Public Knowledge only

### Observed Behavior:
Request Failed: Sourcegraph Cody Gateway: unexpected status code 400 error is shown after clicking Public knowledge only 

### Expected behavior:
No error should be shown and request should be sent successfully

### Additional context

**Video link:** https://drive.google.com/file/d/1gcG-mXYXkEL8tK4Uz9arBHX57vyfpWId/view?t=1

**Comment by mkondratek** [comment]
I am able to repro this one. Note that this seems to be llm-specific issue.

**Comment by mkondratek** [comment]
The same problem can be accomplished in VS Code

**Comment by mkondratek** [comment]
This is a low prio issue. The error message contains an explanation. The message cannot be empty. We should improve the message probably. 

Linear issue created for tracking: https://linear.app/sourcegraph/issue/CODY-3518
