### ISSUE TITLE
JetBrains: Clicking on filename from Chat context will not navigate user to correct location in code.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#2105]
### IDE Information

IntelliJ IDEA 2024.2 (Community Edition)
Build #IC-242.20224.300, built on August 7, 2024
Runtime version: 21.0.3+13-b509.4 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.3
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
DevKit (242.20224.159)
PythonCore (242.20224.300)
idea.plugin.protoeditor (242.20224.155)
gherkin (242.20224.159)
com.jetbrains.space (242.20224.155)
cucumber-java (242.20224.159)
com.sourcegraph.jetbrains (6.0.31-nightly)
Kotlin: 242.20224.300-IJ

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Open a source code file and select any method 
4. Run `Explain Code` command
5. Move cursor anywhere in the source code file
6. Expand the chat context and click on filename with `Go to Line number

### Observed behavior:
Cursor will not be moved to that position in source code file

### Expected behavior:
Cursor should highlight the particular code snippet.

### Additional context

**Video link:**

https://drive.google.com/file/d/1WZZ9UfTw2S9AODe6W8yJXlZvs6yA7ESo/view?usp=drive_link

**Comment by pkukielka** [comment]
Fixed in 6.0.32-nightly 
@mkondratek to confirm and close

**Comment by mkondratek** [comment]
yup - it works now
