### ISSUE TITLE
bug: Recipes/commands are not properly loaded just after new project is opened

### ISSUE THREAD

**Issue by pkukielka** [sourcegraph/jetbrains#211]
### Installation Information

Happens on 5.2.12694 (and as of today, on main).

### Describe the bug

<img width="638" alt="Screenshot 2023-12-19 at 15 31 37" src="https://github.com/sourcegraph/jetbrains/assets/1519649/51d72b93-da54-4798-8b71-59673c2c5ac0">

Using refresh fixes the issue but the first impression is not optimal.

### Expected behavior

There should be no manual action required to see the commands.

**Comment by olafurpg** [comment]
This is an issue that we definitely need to fix. It's been reported several times and we should have fixed it a while ago.

Without understanding fully the root problem, my proposal would be to stop using `recipes/list` and make this a hardcoded list of button to trigger recipes (aka. commands).

**Comment by mkondratek** [comment]
it's fixed!

**Comment by mkondratek** [comment]
we have a closed issue for this one here: https://github.com/sourcegraph/jetbrains/issues/160

and a merged solution here: https://github.com/sourcegraph/jetbrains/pull/200

it will be released today in a nightly.

do you still experience this issue in the current `main`?

**Comment by pkukielka** [comment]
Indeed looks like it's fixed, I cannot reproduce that issue anymore!
