### ISSUE TITLE
Stable and nightly tags pushed in `push-git-tag-for-next-release.sh` have different versions during the same release

### ISSUE THREAD

**Issue by exigow** [sourcegraph/jetbrains#212]
Example of latest `push-git-tag-for-next-release.sh --stable`:

```
v5.2.12694
v5.2.12677-nightly
```

Should be:

```
v5.2.12694
v5.2.12694-nightly
```

**Comment by exigow** [comment]
Thanks @mkondratek for noticing this!

**Comment by mkondratek** [comment]
good point, thanks for creating this issue 😅

**Comment by mkondratek** [comment]
It's no longer an issue. All the recent releases have the nightly and stable version matching properly.
