### ISSUE TITLE
JetBrains: Cody Chat UI doesn't match Editor theme upon relaunching Editor

### ISSUE THREAD

**Issue by RajatNagoria** [sourcegraph/jetbrains#2171]
### IDE Information

IntellJ IDEA 2024.2.0.2 (Community Edition)
Build #PC-233.13763.11, built on January 26, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11,Mac OS
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
com.sourcegraph.jetbrains (6.0.38)

### Bug Description

Platform: Windows, MAC OS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Any user
3. Relaunch Editor after Opening once

### Observed Behavior:
Cody Chat UI doesn't match Editor theme upon relaunching Editor

### Expected behavior:
Cody Chat UI should match editor theme

### Additional context

![Cody UI Broken](https://github.com/user-attachments/assets/f9ee0c0a-c48a-4332-a6f3-767cb99708b3)

**Comment by dominiccooney** [comment]
I can't reproduce this with 7.0.0-nightly, however I believe we can fail to set the theme when the web content loads slowly, or we race with the editor loading its own theme.
