### ISSUE TITLE
bug: Connection closed without receiving any events

### ISSUE THREAD

**Issue by AlexiumIso** [sourcegraph/jetbrains#2185]
### IDE Information

IntelliJ IDEA 2024.2.1 (Community Edition)
Build #IC-242.21829.142, built on August 28, 2024
Runtime version: 21.0.3+13-b509.11 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4090M
Cores: 12
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  Batch Scripts Support (1.0.13)
  CMD Support (1.0.5)
  com.intellij.ml.llm (242.21829.142)
  com.demonwav.minecraft-dev (2024.2-1.8.1)
  com.sourcegraph.jetbrains (6.0.34)
  com.github.copilot (1.5.20.6554)
Kotlin: 242.21829.142-IJ

### Bug Description

this fucking thing doesn't work

### Additional context

Stacktrace: ```Connection closed without receiving any events```

**Comment by PriNova** [comment]
Hey @oMacronio 

Please update to the latest Cody version. If the error still persists, please open a new report with additional steps to reproduce this issue.

Thank you
