### ISSUE TITLE
bug: Connection closed without receiving any events

### ISSUE THREAD

**Issue by bahrmichael** [sourcegraph/jetbrains#2193]
### IDE Information

IntelliJ IDEA 2024.1.4 (Ultimate Edition)
Build #IU-241.18034.62, built on June 20, 2024
Licensed to Sourcegraph / Michael Bahr
You have a perpetual fallback license for this version.
Subscription is active until April 14, 2025.
Runtime version: 17.0.11+1-b1207.24 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.6.1
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 16
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  eslint.additional.file.extensions=svelte
Non-Bundled Plugins:
  com.github.bric3.excalidraw (0.4.0)
  Key Promoter X (2024.1.0)
  org.jetbrains.plugins.go (241.17011.2)
  com.intellij.aqua (241.18034.62)
  com.intellij.lang.jsgraphql (241.14494.150)
  dev.blachut.svelte.lang (241.17011.2)
  com.sourcegraph.jetbrains (6.0.34)
Kotlin: 241.18034.62-IJ

### Bug Description

Chat failed with an error two times, before eventually picking up again. No idea what to do except to wait and retry.

<img width="470" alt="Screenshot 2024-09-02 at 15 53 37" src="https://github.com/user-attachments/assets/dbfa667a-3be6-4b40-8adc-4c498d695f8b">

### Additional context

Stacktrace: ```Connection closed without receiving any events```

**Comment by dominiccooney** [comment]
We believe this is caused by an Anthropic outage. You can view the current status here: https://status.anthropic.com/ (api.anthropic.com specifically.)

In the meantime, try using a model from a different provider.
