### ISSUE TITLE
JetBrains: New session will not be created when running explain code command with existing response

### ISSUE THREAD

**Issue by RajatNagoria** [sourcegraph/jetbrains#2195]
### IDE Information

PyCharm 2024.2.0.1 (Community Edition)
Build #IC-242.20224.300, built on August 7, 2024
Runtime version: 21.0.3+13-b509.4 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
windows 11
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
DevKit (242.20224.159)
PythonCore (242.20224.300)
idea.plugin.protoeditor (242.20224.155)
gherkin (242.20224.159)
com.jetbrains.space (242.20224.155)
cucumber-java (242.20224.159)
com.sourcegraph.jetbrains (7.0.0-nightly)
Kotlin: 242.20224.300-IJ

### Bug Description

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your PyCharm
2. Login to Cody with Free/Pro user
3. Make sure any chat exist in cody chat
4. Open command section & Run Explain code command
5. Navigate to History Section 

### Observed behavior:
New session will not be created when running explain code command with existing response

### Expected behavior:
Clicking on explain code should start new session

### Additional context

**Video link:** https://drive.google.com/file/d/1Pmkq3SWdcb1lQCecI95mNMhaAetq5KmW/view?t=4

**Comment by pkukielka** [comment]
@RajatNagoria I cannot reproduce this. Does it always happens for you or was it one time thing?

**Comment by RajatNagoria** [comment]
@pkukielka Yes It happens for me always
