### ISSUE TITLE
JetBrains: "Accept" and "Reject" buttons become non-clickable when user generate files from "Cody Apply"

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#2197]
### IDE Information

IntelliJ IDEA 2024.2 (Community Edition)
Build #IC-242.20224.300, built on August 7, 2024
Runtime version: 21.0.3+13-b509.4 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.3
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  DevKit (242.20224.159)
  PythonCore (242.20224.300)
  idea.plugin.protoeditor (242.20224.155)
  gherkin (242.20224.159)
  com.jetbrains.space (242.20224.155)
  cucumber-java (242.20224.159)
  com.sourcegraph.jetbrains (7.0.0-nightly)
Kotlin: 242.20224.300-IJ

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Ask Cody a question `generate 3 separate html files to print hello world with different fonts`
4. Verify Cody respond with valid code output and separate file names
5. Click on `Apply` button and verify Cody generate a file correctly
6. Click on `Accept` button from all 3 code snippets in Cody response
7. Check all three files and try to click `Accept` or `Reject` buttons from files

### Observed behavior:
`Accept` or `Reject` buttons are not clickable

### Expected behavior:
`Accept` or `Reject` buttons should disappear when user clicks on `Accept` from Cody response.

### Additional context

**Video link:**

https://drive.google.com/file/d/1weMkamxVKPwhHXlSz2KdtDVQ7YzVid4P/view?usp=drive_link

**Comment by dominiccooney** [comment]
I just coincidentally had a non-clickable "reject" button from an edit after cmd-tabbing from IntelliJ to Edge and back a bunch. Nothing to do with smart apply, just an edit. The keyboard shortcut worked. 7.0.0-nightly.
