### ISSUE TITLE
bug: received no parseable response data from Anthropic

### ISSUE THREAD

**Issue by Arthur-Senior** [sourcegraph/jetbrains#2212]
### IDE Information

CLion 2024.1.3

### Bug Description

constantly get this error

### Additional context

Stacktrace: ```received no parseable response data from Anthropic```

**Comment by PriNova** [comment]
Hey @Arthur-Senior 

Please update Cody to the latest version. If the issue still persists, please open a new bug report with additional steps to replicate the issue further.

Thank you
