### ISSUE TITLE
bug: java.lang.RuntimeException: Cannot invoke (class=FrameStateManagerAppListener, method=applicationDeactivated, topic=Applicati...

### ISSUE THREAD

**Issue by faysou** [sourcegraph/jetbrains#2237]
### IDE Information

IntelliJ IDEA 2024.2.1 (Ultimate Edition)
Build #IU-242.21829.142, built on August 28, 2024
Licensed to Sofiane Aberkane
Subscription is active until May 30, 2025.
For educational use only.
Runtime version: 21.0.3+13-b509.11 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.6.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  i18n.locale=
  editor.minimap.enabled=true
  org.toml.json.schema=false
  terminal.new.ui=true
Non-Bundled Plugins:
  com.intellij.notebooks.core (242.21829.3)
  PythonCore (242.21829.142)
  com.jetbrains.rust (242.21829.114)
  com.jetbrains.edu (2024.8-2024.2-749)
  com.sburlyaev.terminal.plugin (0.8.0)
  name.kropp.intellij.makefile (242.20224.155)
  Pythonid (242.21829.142)
  intellij.jupyter (242.21829.142)
  com.intellij.nativeDebug (242.21829.165)
  org.jetbrains.plugins.github (242.21829.162)
  com.intellij.bigdatatools.core (242.21829.142)
  com.intellij.bigdatatools.kafka (242.20224.159)
  com.intellij.bigdatatools.binary.files (242.20224.159)
  com.intellij.bigdatatools.databricks (242.20224.419)
  com.intellij.bigdatatools.rfs (242.21829.142)
  com.intellij.bigdatatools.metastore.core (242.20224.159)
  com.intellij.bigdatatools.flink (242.20224.159)
  com.clutcher.comments_highlighter (2024.2.2.1)
  com.sourcegraph.jetbrains (7.0.0)
  com.mallowigi (97.0.0)
  izhangzhihao.rainbow.brackets (2024.2.6-241)
  zielu.gittoolbox (500.2.15+242)
  com.intellij.bigdatatools.spark (242.20224.159)
  com.intellij.bigdatatools.zeppelin (242.20224.159)
  com.intellij.bigdatatools (242.20224.159)
Kotlin: 242.21829.142-IJ

### Bug Description

cody often crashes after linting in rust

### Additional context

Stacktrace:
```text
java.lang.RuntimeException: Cannot invoke (class=FrameStateManagerAppListener, method=applicationDeactivated, topic=ApplicationActivationListener)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:699)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:445)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:424)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:483)
	at jdk.proxy2/jdk.proxy2.$Proxy53.applicationDeactivated(Unknown Source)
	at com.intellij.ide.ApplicationActivationStateManager.updateState(ApplicationActivationStateManager.kt:47)
	at com.intellij.ide.IdeEventQueueKt.processAppActivationEvent(IdeEventQueue.kt:1075)
	at com.intellij.ide.IdeEventQueueKt.access$processAppActivationEvent(IdeEventQueue.kt:1)
	

```
Additional info: ```cody bugs after rust code errors```

**Comment by dominiccooney** [comment]
Thank you for reporting @faysou . 

This is the same stack as #2209, we will track it in that issue.
