### ISSUE TITLE
feedback: Propagate Cody release notes to the JetBrains plugin

### ISSUE THREAD

**Issue by esafak** [sourcegraph/jetbrains#2253]
### Installation Information

Go to the What's New tab of the plugin in the Installed section.

### Share your feedback

Don't just say 'see GitHub'

### Additional context (logs, images, etc)

None

**Comment by PriNova** [comment]
Hey @esafak 

Thank you for reaching out to us.

We decided to have a common source of truth for all of Cody's changes in one place.
