### ISSUE TITLE
JetBrains: "Export" button is non functional and user can't export chats.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#2274]
### IDE Information

IntelliJ IDEA 2024.2 (Community Edition)
Build #IC-242.20224.300, built on August 7, 2024
Runtime version: 21.0.3+13-b509.4 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.3
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  DevKit (242.20224.159)
  PythonCore (242.20224.300)
  idea.plugin.protoeditor (242.20224.155)
  gherkin (242.20224.159)
  com.jetbrains.space (242.20224.155)
  cucumber-java (242.20224.159)
  com.sourcegraph.jetbrains (7.0.3-nightly)
Kotlin: 242.20224.300-IJ

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Go to Chat History tab and click on `Export` button

### Observed behavior:
`Export` button is not clickable and user can't export chats.

### Expected behavior:
User should be able to export chats

### Additional context

**Screenshot:**

<img width="514" alt="Screenshot 2024-09-12 at 2 52 47 AM" src="https://github.com/user-attachments/assets/32b76069-4887-448c-b5cd-ebb7a6842e16">

**Comment by olejorgenb** [comment]
I'm still unable to export chats:

```
PyCharm 2024.3 (Professional Edition)
Build #PY-243.21565.199, built on November 13, 2024
Licensed to *************
Subscription is active until October 17, 2025.
Runtime version: 21.0.5+8-b631.16 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.8.0-40-generic
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 3560M
Cores: 4
Registry:
  vcs.log.index.enable=true
  ide.experimental.ui=true
  i18n.locale=
  python.debug.low.impact.monitoring.api=False
Non-Bundled Plugins:
  com.berzanmikaili.intellij.monokai_pro (2.0.2c)
  MultiHighlight (3.2.0)
  org.intellij.plugins.hcl (243.21565.180)
  com.ultrahob.zerolength.plugin (0.95)
  com.intellij.ideolog (243.21565.208)
  com.tylerthrailkill.intellij.solarized (3.0.0)
  org.jeto.taskfocus (1.2)
  com.arcticicestudio.nord.jetbrains (0.13.0)
  GrepConsole (13.2.0-IJ2023.3)
  com.insyncwithfoo.pyrightls (1.1.0)
  org.jetbrains.plugins.gitlab (243.21565.204)
  org.jetbrains.plugins.github (243.21565.204-ultimate)
  uk.co.ben-gibson.remote.repository.mapper (4.5.2)
  com.sourcegraph.jetbrains (7.4.4)
Current Desktop: ubuntu:GNOME
```

Nothing happens when I click the export button and I get 

```
2024-12-12 14:02:46,881 [223872361]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (/home/ole/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/241.17011.127.plugins/Sourcegraph/agent/index.js:322941:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
```

in the idea.log
