### ISSUE TITLE
JetBrains: File is showing before Project for the chat context with 7.0.3-nightly.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#2275]
### IDE Information

IntelliJ IDEA 2024.2 (Community Edition)
Build #IC-242.20224.300, built on August 7, 2024
Runtime version: 21.0.3+13-b509.4 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.3
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  DevKit (242.20224.159)
  PythonCore (242.20224.300)
  idea.plugin.protoeditor (242.20224.155)
  gherkin (242.20224.159)
  com.jetbrains.space (242.20224.155)
  cucumber-java (242.20224.159)
  com.sourcegraph.jetbrains (7.0.3-nightly)
Kotlin: 242.20224.300-IJ

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin `7.0.2-nightly` installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Have one source code file open and check the Cody chat context sequence
4. Upgrade to Cody plugin `7.0.3-nightly` and restart the IDE
5. Check the sequence of chat context

### Observed behavior:
File is showing before Project

### Expected behavior:
Project should be first as a chat context and any file opened should be next

### Additional context

**Video link:**

https://drive.google.com/file/d/1iV1lrW_EiAIHcSIMM2reRHcMkIdJ8ptJ/view?usp=drive_link

**Comment by pkukielka** [comment]
@taylorsperry that seems to be the case also in VSC.
Is that bug or a feature? :)
