### ISSUE TITLE
bug: After waking the computer system from sleep mode, Cody's sidebar seems frozen, unable to accept input or scroll.

### ISSUE THREAD

**Issue by jonefeewang** [sourcegraph/jetbrains#2279]
### IDE Information

IDE Information
RustRover 2024.1.8
Build #RR-241.18968.39, built on August 20, 2024
Licensed to jonefee wang
Subscription is active until May 26, 2025.
For non-commercial personal development only.
Runtime version: 17.0.11+1-b1207.30 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.6.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
debugger.attach.dialog.enabled=true
ide.experimental.ui=true
llm.ai.assistant.toolwindow.activation.on.start=false
transferSettings.vscode.onlyCargoToml=true
terminal.new.ui.show.promotion=false
org.toml.json.schema=false
Non-Bundled Plugins:
com.vermouthx.idea (1.16.0)
com.sourcegraph.jetbrains (6.0.38-nightly)

### Bug Description

After waking the computer system from sleep mode, Cody's sidebar seems frozen, unable to accept input or scroll.

**Comment by PriNova** [comment]
@jonefeewang 

After updating to the latest Cody version, this issue may be fixed for you.

Thank you
