### ISSUE TITLE
bug: IDE freezes

### ISSUE THREAD

**Issue by Nopik** [sourcegraph/jetbrains#2280]
### IDE Information

IDEA 2024.2.1, MacOS 14.6.1, Cody 7.0.2, M1 Max

### Bug Description

After I upgraded Cody to 7.0.2 today, my Idea started to freeze randomly, sometimes 30 seconds after restart, even if I'm not doing anything (focus out of the IDE window). It was the only change I did over past few days in my IDE, so I do suspect it is Cody fault. I have not confirmed it yet. But in 2-3 hours since I updated IDE got frozen 3 times. I disabled Cody for the time being, and so far no freezes for 1-2 hours. I'll run a day or two without Cody and if there will be no freezes, I'll try re-enabling it again and see if the freezes will return.

When IDE freezes, nothing works, even cursor stops blinking. The only thing I can do is to force IDE to exit & then restart. I wasn't waiting for very long times, maybe up to 2-3 minutes - so maybe after longer time it could unfreeze. When it freezes, there is higher CPU utilization, but not 100%. iStat shows 40-60% CPU usage by Idea when in frozen state, vs <1% in normal operation.

**Comment by Nopik** [comment]
Previously I had Cody 7.0.1 and it was working fine (except throwing exceptions every now and then).

**Comment by antoniocirasole** [comment]
I can vouch for this issue as well. It started happening right after the upgrade.

Also, I happened to upgrade my JDK 

Edit
Exact same configuration as OP.
Mac OS 14.6.1
IntelliJ Runtime: 
Runtime version: 21.0.3+13-b509.11 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by prerak-theCirqle** [comment]
Facing the same here!

**Comment by roke22** [comment]
Same here!!

**Comment by Nopik** [comment]
@mkondratek @pkukielka I hope somebody from your team sees this and act quickly upon it, as this is basically a blocker.

**Comment by Nopik** [comment]
Since I disabled Cody plugin I had no more freezes, and given the amount of feedback I'm not looking forward enabling it again before fix arrives.

**Comment by Nopik** [comment]
After full day of stability without Cody enabled, I enabled Cody to ask it something. 15 minutes later IDE froze again during typing. So, evidence points more and more toward Cody.

**Comment by pkukielka** [comment]
@Nopik Hey, thanks for a report, it was indeed a Cody bug and a fix is already present in a nightly release.
Stable release is planned for Monday, as we need to wait up to 48h for JetBrains review and approval.

**Comment by bjarkevad** [comment]
Installed the 7.0.4 nightly version from https://plugins.jetbrains.com/plugin/9682-cody-ai-coding-assistant-with-autocomplete--chat/versions/nightly and the problem seems to have been solved!

**Comment by cyformatician** [comment]
@Nopik Jetbrains's internal full-line code completion is broken across all JB IDEs with a fix being worked on. You probably have it disabled otherwise you'd be greeted with frequent crashes.

@pkukielka @bjarkevad thanks for the fix and tip!

**Comment by PriNova** [comment]
Closing after issue has been fixed.
