### ISSUE TITLE
feedback: Font size for the CODY UI is too small.

### ISSUE THREAD

**Issue by Nembus** [sourcegraph/jetbrains#2291]
### Installation Information

Installed the latest version of Cody v7.0.2.

### Share your feedback

The UI font for the Cody plugin is too small to be able to read. There is no way to adjust this at all. Using the zoom in the Webstorm's prefs does not change the font size of the Cody UI at all. As much as I'd like to use Cody, I cannot. WebStorm 2024.2.

**Comment by e22m4u** [comment]
Same here with Cody v7.0.6

![Выделение_012](https://github.com/user-attachments/assets/7aef4dfb-1975-4bf0-b437-ded54716f0cd)
