### ISSUE TITLE
bug: chat windows text is in black color in Dark mode - this issue still exisits

### ISSUE THREAD

**Issue by nirzaf** [sourcegraph/jetbrains#2310]
### IDE Information

JetBrains Rider 2024.2.4
Build #RD-242.21829.210, built on September 6, 2024
Licensed to Mohamed Farook
Subscription is active until October 7, 2024.
Runtime version: 21.0.3+13-b509.11 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 10.0
.NET Core v8.0.4 x64 (Server GC)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2002M
Cores: 12
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  dev.turingcomplete.intellijdevelopertoolsplugins (5.0.0)
  org.jetbrains.intellij.scripting-javascript (1.3)
  PythonCore (242.21829.142)
  org.toml.lang (242.20224.155)
  com.intellij.bicep (242.20224.155)
  com.supermaven.intellij (1.38)
  com.codeium.intellij (1.16.4)
  fr.socolin.application-insights-debug-log-viewer (2024.2.0)
  com.elicul.azure-devops-commit-message-plugin (1.0.2)
  com.zhengfei.aicoding (2024.1.15)
  com.sourcegraph.jetbrains (7.0.4)
  zielu.gittoolbox (500.2.15+242)
  mobi.hsz.idea.gitignore (4.5.3)
  com.intellij.resharper.azure (4.1.3)

### Bug Description

Initial Dark Mode: When you open Rider in dark mode, the Cody chat window looks different than expected. This indicates a potential bug or inconsistency in the dark mode theme. refer below screenshot pls

![image](https://github.com/user-attachments/assets/52c8198d-175e-4a12-acbc-751f96eac5e4)

But after changing the theme to light mode and then back to dark mode, or switching to another theme and then back to the original dark mode, the chat window appears as expected. This suggests that the initial glitch is resolved by switching themes. 

![image](https://github.com/user-attachments/assets/82cb7453-fbe6-4ffc-bba9-d8cb039edec5)

### Additional context

I have been experiencing this issue for an extended period, which has significantly impacted my workflow. I kindly request that this matter be addressed with urgency to ensure a seamless user experience, after long frustration I am reporting it, so please fix it asap

**Comment by nicedukk** [comment]
Yes, it's the same on my side. But what's more urgent is that the font size is too small.

**Comment by haraldreingruber-dedalus** [comment]
Same here, I would love to see this fixed as the usability is not nice at the moment.

Ah, the workaround is also good to know! Thanks for sharing!

**Comment by nirzaf** [comment]
I already cancelled my Pro Subscription - doing well with Amazon Q + Codeium - totally free of cost
