### ISSUE TITLE
JetBrains: User doesn't signout from cody even after removing all the account

### ISSUE THREAD

**Issue by RajatNagoria** [sourcegraph/jetbrains#2346]
### IDE Information

Intell J 2024.2.0.2 (Community Edition)
Build #PC-233.13763.11, built on January 26, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
com.sourcegraph.jetbrains (7.0.7-nightly)

### Bug Description

Platform: Windows 

**Steps to reproduce:**

1. Have Cody plugin installed in your JB Intell J editor
2. Login to Cody with Free/Pro user
3. Click on Cody icon in bottom of the editor
4. Click on Manage account > Select account 
5. Click on '-' button > Make sure account gets remove then click on apply
6. Navigate to Cody chat

### Observed behavior:
User doesn't signout from cody even after removing all the account

### Expected behavior:
User should signout immediately after removing all the account

### Additional context

**Video link:** https://drive.google.com/file/d/1ZI2DZDw08TFUESlRFeSW_ZMCr5cPmHBs/view?t=4

**Comment by mkondratek** [comment]
I assume https://github.com/sourcegraph/jetbrains/pull/2382 will fix this one (or make it easier to fix at least), is that right @pkukielka ?
