### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by jdorfman** [sourcegraph/jetbrains#235]
### Installation Information

n/a

### Describe the bug

"Open GitHub to Report Cody Issue" goes to the wrong URL `https://github.com/sourcegraph/sourcegraph/issues/new?template=jetbrains.md`

<img width="499" alt="Image 2023-12-28 at 11 42 46 AM png" src="https://github.com/sourcegraph/jetbrains/assets/398230/c736c129-1720-4908-a95a-4a005d3fb3aa">

### Expected behavior

It should open `https://github.com/sourcegraph/jetbrains/issues/new?assignees=&labels=bug%2Cteam%2Fjetbrains&projects=sourcegraph%2F381&template=bug_report.yml&title=bug%3A+`

### Additional context (logs, images, etc)

See above

**Comment by mkondratek** [comment]
good point, thanks
