### ISSUE TITLE
bug: Unable to use Cody in two IntelliJ IDEs at once 

### ISSUE THREAD

**Issue by ajaynz** [sourcegraph/jetbrains#243]
### Installation Information

Cody plugin 5.2.15221

### Describe the bug

Prior to release of 5.2.15221 I was able to use Cody on multiple IntelliJ IDE's simultaneously.

My normal workflow is to have Android Studio and IntelliJ IDEA CE running side by side to do testing and check cross compatibility. 

But now if I use Cody on Android Studio then the access token on IntelliJ IDEA CE gets wiped and I am prompted for access keychain (see screenshot). 
Once I configure Cody on IntelliJ IDEA CE the access token on Android Studio gets cleared.
<img width="1013" alt="Screenshot 2024-01-04 at 14 59 04" src="https://github.com/sourcegraph/jetbrains/assets/1268945/a1ac1717-510b-4066-a076-6904b1ab2e26">

### Expected behavior

I should be able to run Cody on multiple IntelliJ IDE's simultaneously.

**Comment by mkondratek** [comment]
Hello @ajaynz 👋 thanks for your report (and opening an issue for it - it is much easier to track and solve it thanks to the proper reporting)

I quickly checked the bahaviour of the plugin having two instances of IntelliJ opened. There is something wrong for sure. We will discuss this issue and most likely resolve it soon. It's significant.

**Comment by simonintech** [comment]
When using Goland I also get this popup. In this instance I do not have intellij open.

<img width="366" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/23657075/19e73047-fa82-4e9d-a5f9-34ed81bd0a99">

**Comment by mkondratek** [comment]
@ajaynz, it is very likely that https://github.com/sourcegraph/jetbrains/pull/220 will fix the issue - we hope to deliver it soon (probably Wednesday)

**Comment by taylorsperry** [comment]
I'm marking as "In progress" and P1 since https://github.com/sourcegraph/jetbrains/pull/220 should fix. If not, we'll revisit.

**Comment by mkondratek** [comment]
The mentioned PR has been merged and a new nightly has been released. I was not able to reproduce this issue with the mentioned changes. @ajaynz, feel free to download the latest nightly and verify it too.

**Comment by taylorsperry** [comment]
Thanks for following up, @mkondratek! I'm going to close for now, but @ajaynz please reopen if you're running into the same issue on the latest version. And thank you again for reporting!
