### ISSUE TITLE
PRD: [JB] *On Feb 1* Notify users that Cody Pro trial is coming to an end 

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#244]
### Description:

Notify Cody Pro users that their free trial is coming to an end, and redirect them to `/cody/subscription` page if they'd like to continue using Cody Pro. **This should go live on February 1.** 

### Objectives:

Notify Cody Pro free trial users that their free trial is ending, and provide them with a way to continue using Cody Pro. 

### Acceptance Criteria:

- Starting February 1, all Cody Pro users see a *dismissible* notification that their free trial of Cody Pro will end on February 15
- The notification directs users to sourcegraph.com/cody/subscription
- See work plan for Copy details

### Design Tasks:

```[tasklist]
### Design Tasks
- [ ] Add a draft title or issue reference here
```
@danielmarquespt could you please add a design for this notification? 

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] Add a draft title or issue reference here
```

### Related Docs:

- [Cody Pro Trial --> Paid Transition](https://docs.google.com/document/d/11gVz0IdKDIpdh05rCfmrAJxiIUycKJqJoEBDE7kVbL4/edit)
- [Cody Clients notification work plan](https://docs.google.com/document/d/1p8V_c5wkmNgnCshRdlnjbHqxgkYLVlvpTyDdbHu4VSY/edit)

**Comment by taylorsperry** [comment]
@chenkc805 please review to make sure this meets requirements, and feel free to suggest any copy changes

**Comment by chenkc805** [comment]
"Your Cody Pro trial is ending soon on February 15
Input your credit card here (link: https://accounts.sourcegraph.com/cody/subscription?on-trial=true) to continue using Cody Pro.
You won't be charged until February 15."

**Comment by taylorsperry** [comment]
@kalanchan to work with eng to scope. Depending on the level of effort, we may just email users to let them know that their trial is coming to an end (instead of adding an in-app notification). See [Cody Pro Trial --> Paid Transition](https://docs.google.com/document/d/11gVz0IdKDIpdh05rCfmrAJxiIUycKJqJoEBDE7kVbL4/edit). Marking as P1, since we have an acceptable Plan B.
