### ISSUE TITLE
PRD: [JB] *On Feb 15* Notify users that Cody Pro trial has ended 

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#245]
### Description:

Notify Cody Pro users that their free trial has ended, and redirect them to /cody/subscription page if they'd like to continue using Cody Pro. **This should go live on February 15**.

### Objectives:

Notify Cody Pro free trial users that their free trial is ending, and provide them with a way to continue using Cody Pro.

### Acceptance Criteria:
- On February 15, all Cody Pro users see a dismissible notification that their free trial of Cody Pro has ended
- The notification directs users to sourcegraph.com/cody/subscription
- See [notification work plan](https://docs.google.com/document/d/1p8V_c5wkmNgnCshRdlnjbHqxgkYLVlvpTyDdbHu4VSY/edit#heading=h.dhfi5gdahvcw) for copy

### Design Tasks:

```[tasklist]
### Design Tasks
- [ ] Add a draft title or issue reference here
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] Add a draft title or issue reference here
- [ ] https://github.com/sourcegraph/jetbrains/issues/276
- [ ] https://github.com/sourcegraph/jetbrains/issues/277
- [ ] https://github.com/sourcegraph/jetbrains/issues/283
```

### Related Docs:

- [Cody Pro Trial --> Paid Transition](https://docs.google.com/document/d/11gVz0IdKDIpdh05rCfmrAJxiIUycKJqJoEBDE7kVbL4/edit)
- [Notifications work plan](https://docs.google.com/document/d/1p8V_c5wkmNgnCshRdlnjbHqxgkYLVlvpTyDdbHu4VSY/edit#heading=h.dhfi5gdahvcw)

**Comment by taylorsperry** [comment]
@chenkc805 please review to make sure this meets requirements, and feel free to suggest any copy changes

**Comment by chenkc805** [comment]
"Your Cody Pro trial has ended
Thank you for using Cody Pro, you have been downgraded to Cody Free. Input your credit card here (link: https://accounts.sourcegraph.com/cody/subscription) to continue using Cody Pro for $9 / month, and cancel anytime"

**Comment by kalanchan** [comment]
related to #244

**Comment by taylorsperry** [comment]
@sourcegraph/cody-plg team, @Sa1to had a question about this: "What should be the source of truth of display-notification-date? Hardcoded or fetched from the agent?" Could you please help guide him?

**Comment by vdavid** [comment]
@taylorsperry 
> @sourcegraph/cody-plg team, @Sa1to had a question about this: "What should be the source of truth of display-notification-date? Hardcoded or fetched from the agent?" Could you please help guide him?

Sorry, forgot to respond to this one, but for the record, we've provided the missing info on Slack.

**Comment by kalanchan** [comment]
thanks David, I also noted it here in the [notification work plan](https://docs.google.com/document/d/1p8V_c5wkmNgnCshRdlnjbHqxgkYLVlvpTyDdbHu4VSY/edit#heading=h.dhfi5gdahvcw)
