### ISSUE TITLE
bug: no context in pycharm - no files open

### ISSUE THREAD

**Issue by simonintech** [sourcegraph/jetbrains#250]
### Installation Information

PyCharm 2023.3.1 (Community Edition)
Build #PC-233.11799.298, built on December 12, 2023
Runtime version: 17.0.9+7-b1087.7 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (5.2.15221)

Cody plugin 5.2.15221

### Describe the bug

A python repo open in pycharm. Embedding available on sourcegraph instance. No files open in the pycharm ide.

Ask a couple of questions along the lines of -

How does the application use dataframes?
How does the application use the pandas library?

In both instances the response complains of lack of context. However I believe there is enough context to provide a response of some description.

It does not appear to read files - does not indicate this in the response.

<img width="513" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/23657075/a6803532-eecd-409d-9b15-43b528abae81">

<img width="515" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/23657075/38915926-5a2d-40a9-859e-7d2a7ed16f95">

### Expected behavior

If I try similar approach using VS Code plugin I manage to get a better response. 

<img width="1385" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/23657075/c9b2a59a-d14b-4a02-afac-c64609a3bf4e">

**Comment by taylorsperry** [comment]
Thank you for reporting, @@simoncwaterer 

Given that we're not supporting embeddings for Enterprise for GA, I'm inclined to bump this to P1 unless, @olafurpg, you think this could be a symptom of another context-related problem that we need to address.

**Comment by taylorsperry** [comment]
@simoncwaterer now that the plugin uses Sourcegraph Keyword Search for context, this issue should be resolved. Please reopen if that's not the case.
