### ISSUE TITLE
Improve design for "Insert at cursor" and "Copy" buttons

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/jetbrains#251]
From offline discussion with the team, we agreed that the current design leaves room for improvements because it does not feel idiomatic. Not a blocker for GA but worth looking into in the future. FYI @taylorsperry

![Image](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/727fb01c-3776-4a45-b9c4-c5c33a897df5/97827f3e-531d-4241-8ca3-082841bfdc45?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy83MjdmYjAxYy0zNzc2LTRhNDUtYjljNC1jNWMzM2E4OTdkZjUvOTc4MjdmM2UtNTMxZC00MjQxLThjYTMtMDgyODQxYmZkYzQ1IiwiaWF0IjoxNzE3NDUzMDk5LCJleHAiOjMzMjg4MDEzMDk5fQ.F2vK94Ken58TBx30hwPTChZP1o8XZR68R2eOBUzC-6s)

**Comment by taylorsperry** [comment]
Thank you! I actually think this is pretty bad . . . it looks like it's broken, and I imagine is a pretty simple fix? cc @danielmarquespt
