### ISSUE TITLE
bug: Private repository not load 

### ISSUE THREAD

**Issue by Amnesia80** [sourcegraph/jetbrains#254]
### Installation Information

PhpStorm 2023.3.2
Build #PS-233.13135.108, built on December 21, 2023

Runtime version: 17.0.9+7-b1087.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  debugger.new.tool.window.layout=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
Non-Bundled Plugins:
  commit-message-helper-idea-plugin (1.4.1)
  PlantUML integration (7.4.2-IJ2023.2)
  com.sourcegraph.jetbrains (5.2.15221-nightly)

### Describe the bug

I'm trying to ask Cody something about my linked project and it dont work
![image](https://github.com/sourcegraph/jetbrains/assets/9349978/3137995a-4a45-42d0-b251-20d564d5cb1f)

### Expected behavior

Cody answer my question based on the config file expose on my repo

**Comment by adampatterson** [comment]
I am having the same issues.

If Cody doesn't have contextual knowledge inside of the git history is there a reason why it needs the git repo at all and can't just read the project folder?

At least in the past I asked a question along the lines of "when was this code added" and Cody said that it didn't have access to the history.

**Comment by taylorsperry** [comment]
Thank you for reporting, @Amnesia80! We're aware of a few context issues that we're working to address. I'm marking this as P0 to make sure it gets prioritized.

**Comment by adampatterson** [comment]
@taylorsperry thanks for the update :)

**Comment by taylorsperry** [comment]
Hey @Amnesia80 and @adampatterson, we've made a bunch of improvements over the past couple weeks and this issue should be resolved now. Are either of you still seeing this issue on the [latest version](https://plugins.jetbrains.com/plugin/9682-sourcegraph-cody--code-search/edit/versions)?

**Comment by adampatterson** [comment]
I personally haven't been having any issues which is nice because my trial was up and I'm now a satisfied paying customer 😀

Repos is working, code works, CPU isn't going wild, seems fast. 

All good!

**Comment by Amnesia80** [comment]
Hello @taylorsperry , i just try right now with the last version and it's work better now. I'll make more tests after holidays 

great job & thanks :)

**Comment by taylorsperry** [comment]
Awesome news, thank you @adampatterson and @Amnesia80!
