### ISSUE TITLE
Propose design for enhanced context selection that is idiomatic to IntelliJ

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/jetbrains#258]

**Comment by dominiccooney** [comment]
Enhanced context selection has two display modes now (soon.) The first is for the consumer product, which lists multiple kinds of providers grouped by what they are indexing. The new one is for enterprise and is an editable list of repositories. See the Figma linked in this issue for details: https://github.com/sourcegraph/cody/issues/2628
