### ISSUE TITLE
Cody tab is eating up 200-400 CPU

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#261]
A user [reported](https://plugins.jetbrains.com/plugin/9682-sourcegraph-cody--code-search/reviews#review=94857) on the marketplace that the Cody plugin is eating up 400% CPU and freezing. @pkukielka can repro ([thread](https://sourcegraph.slack.com/archives/C059N5FRYG3/p1704725859869629)). 

Possibly related [feedback](https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1704724589157119) we've received at our hi@sourcegraph.com email address: 

> CPU usage of ~1.7 cores on Goland is too high, I'm on an M1 Pro, so it's not old hardware

**Comment by morgangauth** [comment]
This is also being reported by a [customer](https://github.com/sourcegraph/accounts/issues/380)

**Comment by adampatterson** [comment]
I am experiencing the same issue.  As it stands Cody is unusable in PHP Storm.
