### ISSUE TITLE
The "Problems" tab keeps opening on every change

### ISSUE THREAD

**Issue by chirastefan** [sourcegraph/jetbrains#2669]
### IDE Information

IU-243.21565.193, JRE 21.0.5+8-b631.16x64 JetBrains s.r.o., OS Mac OS X(aarch64) v14.6.1, screens 3456x2234 (200%), 2560x1440 (100%); Retina

### Bug Description

After the upgrade to the latest version, the "Problems" tab keeps opening every time I make a change, by clicking inside the editor, on keyboard press, on tab changes, etc.
The Cody Sourcegraph plugin seems to be the culprit. Cody console runs when I open the IDE, and even if I close the Cody console tab, I think it opens the problems tabs under the hood.

**Comment by mostlydev** [comment]
Same here.  Completely unusable.

**Comment by chirastefan** [comment]
seems to be fixed in the latest version
