### ISSUE TITLE
Update settings UI to configure default model for the current account OR application (require clarification from Product or Design)

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#267]

**Comment by mkondratek** [comment]
Hello @taylorsperry, we are going to make it as application default (it should be a way simpler solution)

**Comment by taylorsperry** [comment]
Sorry, this is probably a dumb question, but does "application default" mean that a user is setting a default LLM for their IDE as opposed to a default for their account? What difference does it make to the user? Even a user who has two accounts (one Pro, one Enterprise, for example) will only be able to change the LLM for their Pro account, since LLM selection for enterprise users is set by the admin.

**Comment by mkondratek** [comment]
@taylorsperry, in short - we can have application persistence and project persistence. Application persistence works across all project opened by the given IDE. Project persistence works only for specific projects.

For the the behaviour is the the model is persisted for a project session. That means if I change to GPT 3.5 and open a new chat, the new chat will have GPT 3.5 set (but a user is able to change it before entering the first prompt). If a user closes the IDE and reopens the project then the dropdown will present the default option (which is Claude 2.0). 

Pls, let me know if that's enough for now and if we can close this one.
