### ISSUE TITLE
Make sure "Cody" option in context menu is active (it's currently marked as grey/disabled)

### ISSUE THREAD

**Issue by pkukielka** [sourcegraph/jetbrains#279]

**Comment by taylorsperry** [comment]
I see the test command is "active" in the right-click menu, so I'm closing. Please reopen if I'm missing something! 
<img width="621" alt="Screenshot 2024-03-11 at 8 25 51 PM" src="https://github.com/sourcegraph/jetbrains/assets/43555476/b4ca3e06-a872-4e96-a509-bbad15e827f3">
