### ISSUE TITLE
Analytics regression since the holidays

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/jetbrains#281]
Context: https://sourcegraph.slack.com/archives/CN4FC7XT4/p1704834121946769

Short summary:

- There's a bug in how we report anonymous user IDs causing analytics to report too high MAU (more users than users on the instance)
- We have observed a drop in CAR after the holidays along with a drop in total autocomplete suggesions

Opening this issue so we can track work on this in our project board.

**Comment by Strum355** [comment]
https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/services/telemetry.ts?L48-49 appears to be creating a new anonymous user ID every time agent starts. I believe we may have to re-add the selected lines [here](https://github.com/sourcegraph/cody/commit/379a095295c84e582cc5512c8b41dd1853b9f251#diff-db07ce759aaa98edd44511c98530f90f5292f381ecb94637825e8d51bddf5a73L51-L62).

\<snipped incorrect comment>

**Comment by taylorsperry** [comment]
Can we close this issue now that https://github.com/sourcegraph/cody/pull/2657 has merged?

**Comment by kelsey-brown** [comment]
I think that PR will fix the issue in the first bullet point (inflated MAU) but I wouldn't necessarily expect it to resolve the second bullet point (drop in CAR) because the CAR metric doesn't rely on the `anonymous_user_id`. I suggest leaving this open until we have a better idea of what's causing the CAR regression.

**Comment by olafurpg** [comment]
Closing this as resolved. CAR is back to ~30% now and the total suggested events was significantly higher last week than the week before. @kelsey-brown please reopen if the MAU issue still persists
