### ISSUE TITLE
feedback: edit-code keybinding is inconsistent both with vscode and internally with chat

### ISSUE THREAD

**Issue by olejorgenb** [sourcegraph/jetbrains#2858]
### Installation Information

PyCharm 2024.3 (Professional Edition)
Build #PY-243.21565.199, built on November 13, 2024
Licensed to *************
Subscription is active until October 17, 2025.
Runtime version: 21.0.5+8-b631.16 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.8.0-40-generic
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 3560M
Cores: 4
Registry:
  vcs.log.index.enable=true
  ide.experimental.ui=true
  i18n.locale=
  python.debug.low.impact.monitoring.api=False
Non-Bundled Plugins:
  com.berzanmikaili.intellij.monokai_pro (2.0.2c)
  MultiHighlight (3.2.0)
  org.intellij.plugins.hcl (243.21565.180)
  com.ultrahob.zerolength.plugin (0.95)
  com.intellij.ideolog (243.21565.208)
  com.tylerthrailkill.intellij.solarized (3.0.0)
  org.jeto.taskfocus (1.2)
  com.arcticicestudio.nord.jetbrains (0.13.0)
  GrepConsole (13.2.0-IJ2023.3)
  com.insyncwithfoo.pyrightls (1.1.0)
  org.jetbrains.plugins.gitlab (243.21565.204)
  org.jetbrains.plugins.github (243.21565.204-ultimate)
  uk.co.ben-gibson.remote.repository.mapper (4.5.2)
  com.sourcegraph.jetbrains (7.4.4)
Current Desktop: ubuntu:GNOME

### Share your feedback

Using edit code (ctrl-k), `Return` insert a new line, while `Ctrl-K` submits. This is inconsistent with the chat keybindings and also with the behavior of edit code in vs code making the feature annoying to use. (and in vs code you lose your prompt if you press ctrl-k again while the edit code dialog is open...)

Personally I would prefer a setting which consistently flips return and shift-return so that "Return" could always insert a new  line.

**Comment by PriNova** [comment]
Hey @olejorgenb 

We'd love to see your feedback here at our community forum https://community.sourcegraph.com/
The product and eng team will have a closer look there

Thank you

**Comment by olejorgenb** [comment]
(Ok, but why encourage feedback as an issue type in this repo then?)

**Comment by PriNova** [comment]
@olejorgenb 

![Screenshot 2024-12-16 154217](https://github.com/user-attachments/assets/e5db14eb-5c92-4e63-bf9e-e4b59c398c35)

This was our place in the beginning to have feedback and feature requests at GitHub but we are moving away from it.

**Comment by olejorgenb** [comment]
Ah, ok. I can't see that message anywhere though.

This is how the "New issue" screen looks like for me:

![image](https://github.com/user-attachments/assets/cb8aa249-afcc-4a0f-890f-53bca7db9f8a)

And readme:

![image](https://github.com/user-attachments/assets/7474040e-fd03-4c2a-9a7c-2e777c56b4c4)

But I suppose you are in the process of making it clearer :+1:
