### ISSUE TITLE
[REQUEST] Add Gemini 1206 

### ISSUE THREAD

**Issue by Eldevia** [sourcegraph/jetbrains#2894]
Happy Christmas!
Please add Gemini 1206 It's the best coding llm at the moment based on the leaderboard. With 2 million token context window!
Or can I somehow add my own api key? I know I can in vs code. But I want to use JetBrains (WebStorm).

**Comment by PriNova** [comment]
Hey @Eldevia 

Happy Christmas to you too. We recently added the Gemini 2.0 Flash experimental model to our selected list. The team is always evaluating if new models arise on the horizon and do their own benchmarks additionally.

Currently, adding own API keys in the JetBrains IDE's is not possible.
Sorry

Happy holidays.
