### ISSUE TITLE
JetBrains: Button "Copy text" from chat is partially hidden and has issues with transparency

### ISSUE THREAD

**Issue by exigow** [sourcegraph/jetbrains#29]
## Steps to reproduce

* Ask Cody to generate code block (for example: "simplify this code").
* Hover generated code block with mouse. 
* Button are now visible.
* Notice that buttons have issues with transparency and positioning.

## Screenshot

![issue](https://github.com/sourcegraph/jetbrains/assets/5013708/677f38d8-ed6b-4761-8ca7-c8e4c5fb768e)

## Additional notes

Plugin version: `5.2.1734-nightly`, but it looks like problem exists in older commits.

Tested on Linux with X11. I'm not sure if this transparency issue occurs on other OS-es.

**Comment by danielmarquespt** [comment]
I want to change the position of those buttons, so until we have a new design this is not and high priority to fix
