### ISSUE TITLE
bug: Context menu option `Sourcegraph > Find with Sourcegraph...` is confusing

### ISSUE THREAD

**Issue by exigow** [sourcegraph/jetbrains#293]
### Installation Information

IntelliJ 2023.3 UE, 5.2.18066-nightly, Linux

### Describe the bug

After clicking on `Sourcegraph > Find with Sourcegraph...` context option with some selection, an additional window (non-browser) opens. This window is not responding with "Loading..." placeholder \~and there is no message or any exception\~.

### Expected behavior

N/A, I am unable to determine what this `Find with Sourcegraph...` is used for.

### Additional context (logs, images, etc)

![Selection_034](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/5e0df0a9-8faa-47f6-9bbd-30087cfc0d68/fbfd0fdb-b9f7-446a-ae2d-f64bb1e1a40a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy81ZTBkZjBhOS04ZmFhLTQ3ZjYtOWJiZC0zMDA4N2NmYzBkNjgvZmJmZDBmZGItYjlmNy00NDZhLWFlMmQtZjY0YmIxZTFhNDBhIiwiaWF0IjoxNzE3NDQ5MTUwLCJleHAiOjMzMjg4MDA5MTUwfQ.F5_d4nVx100-PEPCTF-DtNyyXxofuPFrkyWT0nYUF6Q)

**Comment by exigow** [comment]
UPDATE: I noticed that sometimes a notification appears stating that "my IDE does not support JCEF". IMO ideally, this additional window should be never opened because this creates confusion. 

The notification alone should be sufficient.

**Comment by mkondratek** [comment]
@exigow, are you still able to reproduce this issue with `5.2.18630-nightly`?

**Comment by exigow** [comment]
@mkondratek yeah,

![image](https://github.com/sourcegraph/jetbrains/assets/5013708/5bf67835-48c6-4348-8809-408516341777)

Notification is shown, but i have to close this "Find with Sourcegraph" manually. IMO if we can recognize situation when JCEF is not supported (see: notification) we should disable this option or don't show up this window. It just feels like a broken feature.

**Comment by mkondratek** [comment]
interesting, idk what JCEF is. I wonder if "Find with Sourcegraph" does not work on linux at all. on macos it's fine

**Comment by exigow** [comment]
Yep. I believe that's P4 (issue of least concern). I've reported that just for the record.
