### ISSUE TITLE
Internal Error: `StringIndexOutOfBoundsException: begin 1, end 0, length 0` from autocomplete

### ISSUE THREAD

**Issue by mkondratek** [sourcegraph/jetbrains#299]
![image](https://github.com/sourcegraph/jetbrains/assets/19799111/bca3f7c8-4862-42f6-b2c0-3c4fb40076ad)

> Bug report:
> - I’ve opened my `pnpm-workspace.yaml` file in a repo root, which was **empty**.
> - I triggered completions manually by `⌃space`
> - Got this error
> I’d have preferred to get completions instead, or the little tooltip about “No suggestions” 

Reporter: @vdavid

**Comment by taylorsperry** [comment]
Closing in favor of https://github.com/sourcegraph/jetbrains/issues/679
