### ISSUE TITLE
Improve automatic failure recovery in case of critical agent failures

### ISSUE THREAD

**Issue by pkukielka** [sourcegraph/jetbrains#306]
### Installation Information

Just deploy code from `main`

### Describe the bug

Now critical agent failure during UI operations like `loadNewChatId` are handled directly in the UI code.
Part of this handling could be moved to `CodyAgentService` but it requires careful design and testing to not spam a lot of processes accidentally.

### Expected behavior

 `CodyAgentService` should be able to restart agent in case of every critical failure.

**Comment by mkondratek** [comment]
Can we consider this one as done now? @pkukielka, iirc, if the agent fails it will try to restart on any explicit Cody action (chat message, command, autocomplete) - right?

**Comment by pkukielka** [comment]
Correct, we can close it.
