### ISSUE TITLE
Revisit and cleanup multithreaded code

### ISSUE THREAD

**Issue by pkukielka** [sourcegraph/jetbrains#307]
There are couple of places where we call `completeOnTimeout` or `getNow` on a `CompletableFuture` which contains agent.
This is not always safe and/or correct.
I tried to cleanup most of those places as part of the https://github.com/sourcegraph/jetbrains/pull/303 but there is still few remaining ones which will require a bit bigger refactoring.

**Comment by taylorsperry** [comment]
@pkukielka what's the impact of calling `completeOnTimeout` or `getNow` (ie, how likely is this to cause an issue for a user)?

**Comment by pkukielka** [comment]
@taylorsperry in most cases it means that if particular action takes longer than expected (e.g autocomplete) it will be aborted. There are situations where this is expected (like mentioned autocomplete) but there are also situations where this could be bad.
I do not think this is critical in any way though.

**Comment by chenkc805** [comment]
Given:

* @pkukielka's comment above
* this feels like more of a refactoring than a bug
* this can be probably addressed through lighter-weight ways like better error messages

this seems like lower priority.
