### ISSUE TITLE
The token is not keep after closing PyCharm on GhostBSD/FreeBSD Cody.

### ISSUE THREAD

**Issue by ericbsd** [sourcegraph/jetbrains#309]
### Installation Information

PyCharm 2023.3.2 (Community Edition)
Build #PC-233.13135.95, built on December 19, 2023
Runtime version: 17.0.9+9-1 amd64
VM: OpenJDK 64-Bit Server VM by OpenJDK BSD Porting Team
FreeBSD 13.2-stable
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (5.2.18630)
  name.kropp.intellij.makefile (233.13135.65)
Current Desktop: MATE

### Describe the bug

Every time I open PyCharm, I have to add back the token.

### Expected behavior

I should not have to add the token every time I Pycharm.

### Additional context (logs, images, etc)

[idea.log](https://github.com/sourcegraph/jetbrains/files/13956452/idea.log)

**Comment by jdorfman** [comment]
Thanks for reporting @ericbsd 

We will review it asap

**Comment by mkondratek** [comment]
Hello @ericbsd 👋 I am sorry you are experiencing this issue.

Could you pls double-check that `Save passwords:` option is set to `In native Keychain`?

![image](https://github.com/sourcegraph/jetbrains/assets/19799111/028fb952-fe3a-47dc-b19c-114a627d347d)

**Comment by ericbsd** [comment]
Ah, it is set to Do not save.

The native Keychain is missing, but KeePass is there.

I have set KeePass for now, and I will see why the native  Keychain is missing later.

Now, the token is kept after the restart. 

Thank you! I am fairly new to JetBrains, I was unaware of that option.
