### ISSUE TITLE
JetBrains: Improve no embeddings message for sourcegraph.com users

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/jetbrains#31]
following this issue:

https://github.com/sourcegraph/jetbrains/issues/2

We should improve the UI to inform the user what is going on:

I'm suggesting this message:

> **No embeddings on sourcegraph.com**
> 
> For open-source repos, suggest adding them to sourcegraph.com on our Discord 
> 
> Currently, private embeddings are reserved for enterprise clients.
> 
> [Join Discord](https://discord.gg/rDPqBejz93)

<img width="737" alt="Screenshot 2023-10-16 at 11 15 20" src="https://github.com/sourcegraph/jetbrains/assets/7814431/44ed4e7f-827e-44a2-9477-80bdfc8f003c">

@taylorsperry  to review the copy

**Comment by taylorsperry** [comment]
Marking this as "Missing Input" from Product since we need to make a decision on how we're going to handle embeddings for dotcom users going forward.
