### ISSUE TITLE
bug: No visual indication in editor when a users access token is no longer valid or does not have access to Cody

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/jetbrains#311]
### Installation Information

IntelliJ IDEA 2023.2 (Community Edition)
Build #IC-232.8660.185, built on July 26, 2023
Runtime version: 17.0.7+7-b1000.6 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.sourcegraph.jetbrains (5.2.18630-nightly)

Kotlin: 232-1.9.0-IJ8660.185

### Describe the bug

When an access token is no longer valid, there is no visual indication in the IDE until you open the plugin settings authentication section.

Additionally when a user connects to an enterprise version and has not been granted Cody access there is no indication of any error. The plugin settings show a valid connection to the instance.  Any chats do not respond.   The following can be found in the idea.log
```
2024-02-09 11:42:42,230 [  98588]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ SimpleChatPanelProvider: postError: cody is not enabled: user does not have permission CODY#ACCESS
```

Chat displays the users input but then does nothing.
Commands do the same
Autocompletes do not display and no change in indication

### Expected behavior

Chat/commands should at a minimum display an the error message that the token is no longer valid.
Autocomplete should show in an error or disabled state.

**Comment by taylorsperry** [comment]
@chwarwick will this work be addressed by [Access token expiration (P0 complete) sourcegraph/sourcegraph#58652](https://github.com/sourcegraph/sourcegraph/issues/58652), or is there separate work required on the client side?

**Comment by chwarwick** [comment]
@taylorsperry This is work that needs to be completed on the client side.  It's a gap between vs code functionality and JetBrains,  I think it's important but not time critical as I don't expect any tokens to start expiring until closer to the end of April.

**Comment by chwarwick** [comment]
@taylorsperry  Added to this report this is the same poor experience occurs when a user connects to an enterprise instance but does not have Cody access.

**Comment by aramaraju** [comment]
@kalanchan Is this work being addressed by the JBs team?
