### ISSUE TITLE
bug: No visual indicator when autocomplete is running

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/jetbrains#312]
### Installation Information

IntelliJ IDEA 2023.2 (Community Edition)
Build #IC-232.8660.185, built on July 26, 2023
Runtime version: 17.0.7+7-b1000.6 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.sourcegraph.jetbrains (5.2.18630-nightly)

Kotlin: 232-1.9.0-IJ8660.185

### Describe the bug

The Cody icon shows no visual indication that an autocomplete is attempting to be generated

### Expected behavior

Previously the Cody icon would spin when it was attempting to generate an autocomplete.  There should be some indication that it is currently attempting to generate an autocomplete.

**Comment by mkondratek** [comment]
hello 👋  I quickly checked for `5.2.18630-nightly` - the indicator works for me however I could not get an automatically triggered autocompletion 😕 we will take a look

**Comment by mkondratek** [comment]
I can see the mentioned problem on our `main`
