### ISSUE TITLE
Investigate logging & telemetry disk usage

### ISSUE THREAD

**Issue by mkondratek** [sourcegraph/jetbrains#315]
Recently we received a report from a user. 

The user claims that they dumped ~80GB of logs to my `/var/log/syslog` effectively bringing their workstation almost to a halt and printing errors that the system has too little space to work normally.

A major part of the logs were entries like this:
```
WARN - #com.sourcegraph.cody.CodeFleEditorListener - server is null
```

We should carefully analyze our logging practices, review the existing logs, probably remove or hide some logs by default.

We should take a look at the telemetry that appears in the logs too.

**Comment by mkondratek** [comment]
UPDATE: the mentioned log (`server is null`) has been removed there: https://github.com/sourcegraph/jetbrains/pull/303

**Comment by mkondratek** [comment]
Does anyone know where are those log files stored? I checked `Help / Show Log in Finder`. In the "worst" case I had 12 idea log files each 10mb (or less).

```
IntelliJ IDEA 2023.3.2 (Ultimate Edition)
...
Non-Bundled Plugins:
  DevKit (233.13135.104)
  nl.rubensten.texifyidea (0.9.3)
  com.virtuslab.git-machete (4.1.1-27-SNAPSHOT+git.6ba3ca9-dirty)
  com.sourcegraph.jetbrains (5.2.20247-nightly)
Kotlin: 233.13135.103-IJ
```

**Comment by chwarwick** [comment]
Also reported here https://github.com/sourcegraph/cody/issues/2773
