### ISSUE TITLE
Add shortcuts to create new chat, focus on the chat, trigger commands

### ISSUE THREAD

**Issue by pkukielka** [sourcegraph/jetbrains#322]

**Comment by exigow** [comment]
The idiomatic way for switching between toobars in IntelliJ uses shortcuts like Alt + 1 (project files), Alt +2 (bookmarks), Alt + 3 (find) and so on. I think we should follow this convention because the Cody is also a toolbar.

Unfortunately, all the numbers are taken (including Alt + 0 which points to "commit" toolbar), but we should come up with a similar solution.

**Comment by exigow** [comment]
Looks like `alt + /` is already taken by built-in IntelliJ action called `Cyclic Expand Word` and `alt + shift + /` is taken by `Cyclic Expand Word (backwards)`.

This is an issue because VS Code uses the `alt + /` to create New Chat. We need to come up with something else.

**Comment by exigow** [comment]
TODO: Ensure that the toolbar also has a functional `Escape` button that takes you back to the main code screen. All toolbars are working this way so we should follow this convention.

**Comment by mkondratek** [comment]
### Keyboard shortcuts

| Command       | Windows / Linux                                  | MacOs                                                |
|---------------|--------------------------------------------------|------------------------------------------------------|
| Open Cody tool window |  <kbd>Alt</kbd> + <kbd>=</kbd> | <kbd>Option</kbd> + <kbd>=</kbd> |
| Open a new chat |  <kbd>Alt</kbd> + <kbd>-</kbd> | <kbd>Option</kbd> + <kbd>-</kbd> |
| Explain Code  | <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>1</kbd> | <kbd>control</kbd> + <kbd>Shift</kbd> + <kbd>E</kbd> |
| Smell Code    | <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>2</kbd> | <kbd>control</kbd> + <kbd>Shift</kbd> + <kbd>S</kbd> |
| Generate Test | <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>3</kbd> | <kbd>control</kbd> + <kbd>Shift</kbd> + <kbd>T</kbd> |

See https://github.com/sourcegraph/jetbrains/blob/86d70a9f5dec0260eb80c61934839d132fcb637f/TESTING.md.
