### ISSUE TITLE
Ensure that chat history is isolated by the Sourcegraph account

### ISSUE THREAD

**Issue by pkukielka** [sourcegraph/jetbrains#323]

**Comment by taylorsperry** [comment]
Closing as I this seems to be fixed: When I log into my enterprise account (v5.3.2999-nightly), I don't see historical chats from my dotcom account. 

Enterprise
![Image](https://github.com/sourcegraph/jetbrains/assets/43555476/2b3690cd-46e0-4212-b498-317d07b0a4af)

Dotcom
![Image](https://github.com/sourcegraph/jetbrains/assets/43555476/5a7f84f7-3c64-4f1b-bbd6-5f27b41c57f9)
