### ISSUE TITLE
JetBrains: need to sign in every time I restart IDE on Windows

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/jetbrains#38]
To reproduce

* Install Cody for IntelliJ *on Windows*
* Sign in, confirm chat + autocomplete works as expected
* Exit IntelliJ
* Restart IntelliJ
* Nothing works, autocomplete and chat are unresponsive. No visual hint about what's wrong.
* Open settings and see that the account is missing access token

![Image](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/dccb2e85-b7c5-43a6-8f1b-674d74cfa648/a50a03b3-edfa-4e07-a31a-16e1003e295d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy9kY2NiMmU4NS1iN2M1LTQzYTYtOGYxYi02NzRkNzRjZmE2NDgvYTUwYTAzYjMtZWRmYS00ZTA3LWEzMWEtMTZlMTAwM2UyOTVkIiwiaWF0IjoxNzE3NDUyMzM0LCJleHAiOjMzMjg4MDEyMzM0fQ.WVOsFoa0baVOyUJpZvNb_nplpdCD8hEOug6euzT09_8)

**Comment by exigow** [comment]
@olafurpg, I'm having difficulties with reproducing your issue on 2023.1.3 CE and 2023.2.3 CE.

Everything seems to be working as expected. After a restart, Cody remains properly authorized and responsive. Tokens are present in the settings. I've attempted to replicate the issue in various ways (such as random shutdowns, having multiple IDEs open, switching between plugin versions, switching between different IDE versions, and removing/adding Sourcegraph accounts) but without success.

Can you please provide more context? Do you think there's any specific detail that might be causing the issue on your Windows but not on mine? Maybe specific sign-in method?

**Comment by exigow** [comment]
Note: I was not able to build cody agent from scratch (https://github.com/sourcegraph/cody/issues/1461) on Windows. My attempt to reproduce this issue was on official releases (latest and nightly) but It probably shouldn't make a difference, though.

**Comment by olafurpg** [comment]
@exigow Thank you for investigating. I am able to reliably reproduce this issue with a Windows Server instance on Google Cloud. I have changed the priority to P3 and removed the "Release" field on the assumption that this issue is restricted to Windows Server. Let's shelve this issue for now and re-prioritize if we get a reliable reproduction in a non-Server Windows instance.

**Comment by olafurpg** [comment]
Recording of my Windows Server instance showing that the access token gets lost when I restart IntelliJ

https://github.com/sourcegraph/jetbrains/assets/1408093/179e3067-3054-4005-a0f2-15cbeb882a77

**Comment by aamehedi** [comment]
Same here. For me my cody access token get lost every time ai restart my WebStorm
![image](https://github.com/sourcegraph/jetbrains/assets/8770038/beb8b4d5-1c8c-413a-99c6-c38d3369b4bf)

**Comment by aamehedi** [comment]
@olafurpg I was able to fix it by changing the passworkd settings my WebStorm.
Go to **Appearnce & Behaviour** > **System Settings** > **Passwords** and then select any suitable option other than the **"Do not save. forget passwords after restart"**
![image](https://github.com/sourcegraph/jetbrains/assets/8770038/64274ed5-39fa-4770-b927-1c9630b6a238)

**Comment by olafurpg** [comment]
@aamehedi Thank you for sharing! That's an interesting find, I was not familiar with this setting. It's great to know there exists a workaround. It would be good to update the Cody plugin to warn users when they have "forget passwords" enabled.
