### ISSUE TITLE
bug: Revoke the access token when a user signs out of JetBrains and VSCode

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/jetbrains#434]
### Installation Information

Most recent version of Cody in JetBrains

### Describe the bug

Steps to repro:

* With account A, have signed in with it 20+ times, and therefore have 20+ access tokens
* Log out of account A in VS Code
* Try signing back into account A in VS Code
* See error

![Screenshot 2024-01-26 at 4 51 32 PM](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/99bf7df8-563f-4144-a8d9-17f7874dd1d5/b45ce634-27e1-429d-8d66-56e76b7f2b1f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy85OWJmN2RmOC01NjNmLTQxNDQtYThkOS0xN2Y3ODc0ZGQxZDUvYjQ1Y2U2MzQtMjdlMS00MjlkLThkNjYtNTZlNzZiN2YyYjFmIiwiaWF0IjoxNzI2NjMxOTUxLCJleHAiOjMzMjk3MTkxOTUxfQ.CM-6R9uUR7GfOoWhjFWrMapL8GgOTHznydC8HsNuxis)

### Expected behavior

This is a new feature for enterprise customers, but PLG users (aka users not on their own Enterprise instance) should never encounter this bug

@eseliger suggested revoking the access token when you sign out of Cody in the IDE. Context: [https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1706317215280919](https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1706317215280919)

### Additional context (logs, images, etc)

*No response*

**Comment by chenkc805** [comment]
Related task in VS Code: https://github.com/sourcegraph/cody/issues/2935

**Comment by dominiccooney** [comment]
Retitling this "and VSCode" because the VSCode issue was autoclosed as stale without being fixed AFAICT.

**Comment by dominiccooney** [comment]
Should we be invalidating any token when you sign out, or just ones we created with the sign-in flow?

Might be painful if a user is reusing the same token elsewhere to invalidate it…

**Comment by chenkc805** [comment]
Yeah - can we do some sort of first in, last out (FILO) with tokens, where the oldest token that you authenticated with just gets discarded in favor of the new one? I can't imagine that anyone with 20+ tokens would be keeping around that 1st token…

**Comment by dominiccooney** [comment]
Ok, @ara.khan is that enough to go on or do you need more design support? Can you bring #discuss-security in on this too, since we are messing with token issuance…
