### ISSUE TITLE
feedback: Support running Cody behind a proxy

### ISSUE THREAD

**Issue by ajaynz** [sourcegraph/jetbrains#436]
### Installation Information

Running Cody on windows machine with Jebrains Cody plugin.

### Share your feedback

Cody currently can't connect to Sourcegraph Cloud if it's behind a proxy. 
The Cody plugin doesn't seem to respect the IntelliJ Proxy setting.

**Comment by ajaynz** [comment]
@taylorsperry tagging for prioritisation

**Comment by taylorsperry** [comment]
Thanks @ajaynz. Adding this [thread](https://sourcegraph.slack.com/archives/C059N5FRYG3/p1705948118244299) for context and tagging @aramaraju for input since this is around support for Enterprise.

**Comment by aramaraju** [comment]
@ajaynz It will be great help if we could clear up a few questions I have around this:

1. Are customers expecting to have a fully on-premises setup where they don't want any traffic leave their network? 

2. Or are they comfortable with the traffic leaving the environment, provided it goes through their proxy?

**Comment by ajaynz** [comment]
@aramaraju 
Customer is using Sourcegraph Cloud for Cody and the Cody plugin needs to go through a proxy access the internet.

**Comment by kalanchan** [comment]
will be launched in 6.0!
