### ISSUE TITLE
bug: com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.sourcegraph.cody.CodyActionGroup' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.sourcegraph.jetbrains]

### ISSUE THREAD

**Issue by AnuragAmbuj** [sourcegraph/jetbrains#441]
Plugin version: ```5.2.20247```
IDE version: ```IU-241.9959.31```
Exception: ```com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.sourcegraph.cody.CodyActionGroup' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.sourcegraph.jetbrains]```
Stacktrace:
```text
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.sourcegraph.cody.CodyActionGroup' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.sourcegraph.jetbrains]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:198)

```

**Comment by exigow** [comment]
Thanks for reporting!

**Comment by exigow** [comment]
It seems that we are using something that will be removed soon. However, I'm wondering why we are getting exceptions instead of deprecation warnings.

**Comment by AnuragAmbuj** [comment]
I sincerely apologise for the duplicates, these get automatically reported in my case. I am checking how to turn those off.

This is a warning as far as I am concerned, just with a stack trace for devs to fix such issues. There is no issue with the plugin's working. Also users can choose to not report or not disable the plugin.

What I have seen is Jetbrains deprecates and removes its APIs very often with its versions, so IMO plugin may require active fixing at all times.

This deprecation notice from Jetbrains might cause compatibility issues with future stable versions of Jetbrains products.

**Comment by taylorsperry** [comment]
closing in favor of https://github.com/sourcegraph/jetbrains/issues/610
