### ISSUE TITLE
Feature Request: Add active label next to the active accoun in settings

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/jetbrains#477]
### Installation Information

All versions

### Share your feedback

Quality of life improvement: Add a clear label to display which account is active. The only feeback is provided by the ✓ icon but its very subtle 

<img width="646" alt="Screenshot 2024-02-02 at 15 00 05" src="https://github.com/sourcegraph/jetbrains/assets/7814431/8b7169e1-0418-4d6e-bc48-edc5ec5a1646">

**Comment by exigow** [comment]
+1

This should be easy to fix.
