### ISSUE TITLE
Cody is not remembering the previous conversations and keeps forgetting. 

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#512]
### Installation Information

Version:
5.2.21709

### Describe the bug

Steps to reproduce:

1. Have Cody plugin installed in your JetBrains IntelliJ IDEA editor
2. User is already logged in to Cody
3. Open 'Chat' and type a message "my favorite color is red"
4. Close the editor
5. Reopen the editor and open 'Chat'
6. Type a message "what's my favorite color?"

**Observed behavior:**
Cody will not give a correct answere and forget the previous conversation.

### Expected behavior

Cody should remember previous conversations.

Video attachment:
https://drive.google.com/file/d/1E6dgptSQRgcXz5iq2gIkcsVEyAmmm0sd/view?usp=drive_link

**Comment by chenkc805** [comment]
I think this is low priority, since when you restart the IDE, I'm pretty sure we start a new chat without context of previous conversations. @taylorsperry can disagree with me here though!

**Comment by taylorsperry** [comment]
Agree that it's not a P0 (P0s are generally issues that prevent a user from using Cody at all), but I would expect Cody to remember chat history after restarting the IDE. That's the behavior in VSC. 

<img width="880" alt="Screenshot 2024-02-07 at 11 08 07 AM" src="https://github.com/sourcegraph/jetbrains/assets/43555476/04264bd0-5aaa-4551-b475-d80fe38ada79">

**Comment by pkukielka** [comment]
There was confusion there. 
Cody will remember what you said to it, but in the scope of the single conversation.
If you will watch the reproduction video you will notice question was asked in the new chat.
Cody have no persistent memory between the chats.
