### ISSUE TITLE
[P2] - Menu options will disappear when user click on "Disable Cody Autocomplete" from Cody settings.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#533]
### Installation Information

Version:
5.2.21709

### Describe the bug

Steps to reproduce:

1. Have Cody plugin installed in your JetBrains IntelliJ IDEA editor 
2. User is already logged in to Cody
3. Click on "Cody" icon from bottom-right corner to open settings
4. Click on "Disable Cody Autocomplete" option
5. Again click on "Cody" icon from bottom-right corner

**Observed behavior**
Both the options "Disable Cody Autocomplete" and "Disable Cody Autocomplete for Java" disappear.

### Expected behavior

It should toggle between Disable/Enable and not completely remove from the menu.

Screenshots:
<img width="701" alt="Screenshot 2024-02-07 at 9 50 30 PM" src="https://github.com/sourcegraph/jetbrains/assets/158482423/4df7dd10-a82f-4505-974a-46b84d1386ff">
<img width="647" alt="Screenshot 2024-02-07 at 9 54 42 PM" src="https://github.com/sourcegraph/jetbrains/assets/158482423/8922f16c-7106-480e-aa8e-8ec5cbc0adec">

**Comment by dominiccooney** [comment]
I can reproduce this at tip 6e3cd8577afa7cac754ed354a5c2b77ea2ae3ed8 (post 5.5.10) so this is still an issue.

**Comment by kalanchan** [comment]
can't repro
