### ISSUE TITLE
Selected text is not pre-filled for "Find with Sourcegraph..." from "Sourcegraph" context menu

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#534]
### Installation Information

Version:
5.2.21709

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains IntelliJ IDEA editor
2. User is already logged in to Cody
3. Open any file and select a word from the code
4. Right click and select 'Sourcegraph > Find with Sourcegraph...' 

**Observed behavior:**
Selected word from the code is not pre-filled in the "Find with Sourcegraph" search query.

### Expected behavior

Selected work from the code should be pre-filled in the search query.

**Note:** 
If user clicks on "Sourcegraph > Search Selection on Sourcegraph web" then the search query will have the selected word pre-filled.

Video link:
https://drive.google.com/file/d/1K-JA7k8_nvKSbMyGQQQpwmGafme5WhUF/view?usp=drive_link

**Comment by taylorsperry** [comment]
Thanks for reporting, @jay-fibi! This is a known issue https://github.com/sourcegraph/sourcegraph/issues/40601, which we'll revisit once we can spend more time integrating the "Search" functionality of the plugin with Cody. Closing it as a duplicate.
