### ISSUE TITLE
JetBrains: Switching between Pro to Free will not get reflected on JetBrains IDE and requires restart

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#550]
### Installation Information

Version:
5.2.21709

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains PyCharm editor
2. User is already logged in to Cody with PRO subscription
3. Go to [Sourcegraph cody subscription] (https://sourcegraph.com/cody/subscription) page
4. Click on "Cancel subscription" and select "Switch to free"
5. Go to PyCharm editor and check "Cody > Subscription" tab

**Observed behavior:**
It should automatically change the current subscription

### Expected behavior

Subscription keep showing "Cody Pro" as Current tier.

### Additional context (logs, images, etc)

**Note:**
This change gets reflected immediately on VS Code editor.

**Video link:**
https://drive.google.com/file/d/1Ly7iFYYm70pxq0XsB_r5DTtvbzHiXy1X/view?usp=drive_link

**Comment by taylorsperry** [comment]
When a user upgrades Free to Pro, there's a notice on the subscription panel that the user needs to restart the IDE for the upgrade to take effect. We should at least include the same notice when a user *downgrades* from Pro to Free. 

The ideal scenario, of course, is that they don't need to restart at all, but I suspect that's a larger effort (in which case it's fine to address after Feb 15).
