### ISSUE TITLE
feedback: Multirepo context selection papercuts

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/jetbrains#557]
### Installation Information

IntelliJ IDEA 2023.2 (Community Edition)
Build #IC-232.8660.185, built on July 26, 2023
Runtime version: 17.0.7+7-b1000.6 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.sourcegraph.jetbrains (5.2.22980-nightly)

Kotlin: 232-1.9.0-IJ8660.185

### Share your feedback

- Starting a new chat resets the repo selection and also collapses the context tree so it took me a while to realize that the repos I had added were removed.  I missed the save button didn't realize I should use it (I'm not a usual JetBrains user it could be that I'm not used to the conventions)
- Adding a new repo to context opens the dialog but the focus is on the Add button so I need to click or tab to the text box.
- Unchecking a repo and clicking the save ✔️  does not have the expected effect.  Opening a new chat both repos are present and checked.

**Comment by taylorsperry** [comment]
Fixed in https://github.com/sourcegraph/jetbrains/pull/623
