### ISSUE TITLE
bug: IntelliiJ crash report

### ISSUE THREAD

**Issue by raznar** [sourcegraph/jetbrains#565]
### Installation Information

On version `5.2.21709` (slack thread with customer: https://sourcegraph.slack.com/archives/C039TJ9TJ2Y/p1706912853962849?thread_ts=1706910668.266109&cid=C039TJ9TJ2Y)

Original issue was hard disk space filling up

### Describe the bug

Customer reports (in addition to hard disk filling up) that IntelliJ crashes "once in a while"
Strack trace attached
[stack_trace.txt](https://github.com/sourcegraph/jetbrains/files/14223987/stack_trace.txt)

### Expected behavior

IDE client should not crash when using Cody

**Comment by taylorsperry** [comment]
We've also started seeing this from reports from community reports within the past 6 hours. https://github.com/sourcegraph/jetbrains/issues/560

Seems like something new cc @pkukielka
