### ISSUE TITLE
bug: On Pycharm, codes suggestions sometime get inline.

### ISSUE THREAD

**Issue by ericbsd** [sourcegraph/jetbrains#582]
### Installation Information

PyCharm 2023.3.2 (Community Edition)
Build #PC-233.13135.95, built on December 19, 2023
Runtime version: 17.0.9+9-1 amd64
VM: OpenJDK 64-Bit Server VM by OpenJDK BSD Porting Team
FreeBSD 14.0-stable
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  eu.osimowicz.plugins.intellij.CodeBlocksSorter (0.1.2)
  com.github.blarc.ai-commits-intellij-plugin (1.5.1)
  com.sourcegraph.jetbrains (5.2.22980-nightly)
  name.kropp.intellij.makefile (233.13135.65)
Current Desktop: MATE

### Describe the bug

I get this when pressing the enter key to the next line.
![image](https://github.com/sourcegraph/jetbrains/assets/4249848/f15d9e1f-81a2-4f12-b1b3-1062563bb852)
When I start writing, everything is fine.
![image](https://github.com/sourcegraph/jetbrains/assets/4249848/23961e28-842c-45a0-8816-d6622ae60864)
If erased, I will get back weird in line with suggestions.
![image](https://github.com/sourcegraph/jetbrains/assets/4249848/54a5616c-22cf-4ef1-8682-454b58485df3)
If I press the tab key I get this:
![image](https://github.com/sourcegraph/jetbrains/assets/4249848/2b7e6c04-71f9-46be-8b2d-ab0b2056f386)

### Expected behavior

The suggested code is displayed correctly.

**Comment by jdorfman** [comment]
Hey @ericbsd! Just checked with the team and they have a few urgent things to fix, but I will work with @taylorsperry on getting this prioritized!

**Comment by ericbsd** [comment]
Thank you!

**Comment by taylorsperry** [comment]
Thanks for flagging, @ericbsd! It's on our board and I'll make sure we get it picked up.

**Comment by jdorfman** [comment]
Thanks @taylorsperry 

and thanks again @ericbsd for reporting :)

**Comment by kalanchan** [comment]
haven't been able to reproduce, feel free to reopen!
