### ISSUE TITLE
bug: missing generate docstring command

### ISSUE THREAD

**Issue by husinwijaya-grabtaxi** [sourcegraph/jetbrains#594]
### Installation Information

GoLand 2023.3.3
Build #GO-233.14015.113, built on January 26, 2024
Licensed to Grabtaxi Holdings Pte Ltd

Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4000M
Cores: 10
Metal Rendering is ON
Registry:
  ide.completion.variant.limit=500
  suggest.all.run.configurations.from.context=true
Non-Bundled Plugins:
  com.cn.oddcn.plugin.gobuildergenerator (1.1.1)
  com.intellij.ml.llm (233.14015.147)
  com.sourcegraph.jetbrains (5.2.21709)
  com.github.copilot (1.4.14.4554)
  uk.co.ben-gibson.remote.repository.mapper (4.4.0)

### Describe the bug

Missing generate docstring command:
<img width="473" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/110683632/9e11819a-288d-4d92-8a12-9596513e5401">

### Expected behavior

There should be generate docstring command

**Comment by taylorsperry** [comment]
Thanks for filing a bug, @husinwijaya-grabtaxi! We've temporarily removed the `doc` command because we're replacing it with functionality that adds documentation inline. Those improvements are on deck :)

**Comment by husinwijaya-grabtaxi** [comment]
Hi @taylorsperry , thanks for the response.. may I know if the feature still available in some older version of the plugin? I find it very useful and plan to use it until the replacement feature is ready
