### ISSUE TITLE
[UX QA] Local repos should not be represented as remote repos

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/jetbrains#598]
The local repo should not be repeated as a remote repo because:

1. It might not even be part of the Sourcegraph instance
2. It is already listed as a context source on the "Local section" 

![Image](https://github.com/sourcegraph/jetbrains/assets/7814431/373becba-0ae9-4ee9-b269-4eb2a0b180f9)

**Comment by pkukielka** [comment]
Fixed in previous release
