### ISSUE TITLE
bug: Chat persistence is flaky

### ISSUE THREAD

**Issue by mkondratek** [sourcegraph/jetbrains#602]
## Scenario
1. Open IDE
2. Open a new chat
3. Write "My name is Mikołaj"
4. Wait for the reply 
5. Close project (do not click anywhere in the editor, do not save files)
6. Reopen the project 
7. Restore the chat 

## Actual
Messages are missing 

## Expected
Messages are in place

---

It may work **sometimes**.

**Comment by exigow** [comment]
This flaky behaviour is a know issue for all settings with state stored in PersistentState components. Unfortunately, IntelliJ decides on its own when the settings are saved, and there is no straightforward mechanism to trigger this. The only thing I found is an option to use classes that are internal/non-public API, but I think that's out of the question. 

We had a discussion recently, and we should seriously consider option to replace it with our own JSON file / don't use persistent settings for this.
