### ISSUE TITLE
Add agent endpoint to search for remote repositories for multi-repo context

### ISSUE THREAD

**Issue by pkukielka** [sourcegraph/jetbrains#605]
We already have UI which can be easily connected to such functionality if we can provide it on the agent side:
https://github.com/sourcegraph/jetbrains/blob/main/src/main/kotlin/com/sourcegraph/cody/context/ui/AddRepositoryDialog.kt#L74
Ideally it should be possible to ask for the first N repos containing given text.

**Comment by pkukielka** [comment]
Implementation we need is there: https://github.com/sourcegraph/cody/blob/main/vscode/src/context/repo-picker.ts#L82
But unfortunately it is now behind the picker, and there is no clear interface to obtain a repo list directly.

We have two choices:
* rewrite it to expose repo search through API
* add option for agent to wrap any picker - could be useful in future, but probably much more work

**Comment by dominiccooney** [comment]
Extension doesn't have code for the filtering or laziness, that is handled by VSCode QuickPick. So we need something similar for JetBrains; we could do it in Kotlin or TypeScript. I guess TypeScript makes sense, emacs might buckle under the weight of deserializing the enormous number of repos some people have.

**Comment by dominiccooney** [comment]
(Removed, was tagging for Agent protocol input but I have enough to go on.)

**Comment by dominiccooney** [comment]
[Figma linked here](https://github.com/sourcegraph/jetbrains/issues/982#issue-2170025506) is relevant to the UX we're trying to achieve.

That looks like:
- Highlighting in the results.
- Helpers for getting the short name from the whole repo name (eg `"github.com/sourcegraph/sourcegraph"` &Rarr; (`"sourcegraph/sourcegraph"`, `"GitHub"`) (do we have an "official" code host mapping anywhere?)
- The fuzzy results are presented in a pretty tight list, so maybe we can just cap that at a maximum number of results and be done with it.
