### ISSUE TITLE
JetBrains: "Add" button is showing enabled without entering anything in "Add Remote Repo" textbox.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#633]
### Installation Information

Version:
5.2.23857-nightly and 5.2.23711-nightly

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains IntelliJ IDEA editor
2. User is already logged in to Cody with PRO subscription
3. Click \[+\] button in the context panel

**Observed behavior:**
"Add" button is showing enabled

### Expected behavior

"Add" button should only be enabled after user enter any repo url in the textbox.

### Additional context (logs, images, etc)

**Screenshot:**

![Screenshot 2024-02-14 at 12 48 22 AM](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/df7abdf1-7bae-4166-aee5-86f88868c672/a23d3d3e-29c7-4350-84ab-17ea8ff53ea7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy9kZjdhYmRmMS03YmFlLTQxNjYtYWVlNS04NmY4ODg2OGM2NzIvYTIzZDNkM2UtMjljNy00MzUwLTg0YWItMTdlYThmZjUzZWE3IiwiaWF0IjoxNzE0NDY1MDQ3LCJleHAiOjMzMjg1MDI1MDQ3fQ.um3X-HhdoqYtGNYBmkDfnVFB7oOOmxIG_gUw4-7l2Eg "=964x")

**Comment by mkondratek** [comment]
<img width="494" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/19799111/d1f724de-7eb5-44d0-bc58-62cfcf2a6bf6">

at least we are consistent with IntelliJ 😅

**Comment by dominiccooney** [comment]
This issue is no longer relevant: Enterprise users use the popup to enter repos since #1308 , and self-serve users can't manually add repositories.

**Comment by kalanchan** [comment]
old designs, closing
