### ISSUE TITLE
JetBrains: "Save Current Context as Default" is not working correctly for multiple repo added.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#634]
### Installation Information

**Version:**
5.2.23857-nightly and 5.2.23711-nightly

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains IntelliJ IDEA editor
2. User is already logged in to Cody with Enterprise subscription
3. Click [+] button in the context panel and add 4-5 new repo
4. Deselect few repo and click on "Save Current Context as Default" button
5. Click on "New Chat" and verify repo selection from context panel 

**Observed behavior:**
Saved context will not preserve the repo selection made my user.

### Expected behavior

It should preserve the repo selection when user click on "Save Current Context as Default" button after selecting required repo.

### Additional context (logs, images, etc)

**Video link:**

https://drive.google.com/file/d/1Skm2ECRkSf0vuyQ8l8IsTTMyEaNHpp4z/view?usp=drive_link

**Comment by taylorsperry** [comment]
I believe the issue here is that there shouldn't be a "Save Current Context as Default" button since the expected behavior is that Cody will start new chats with the same context it had for the previous chat. Confirming with @danielmarquespt

**Comment by pkukielka** [comment]
FYI I cannot reproduce this locally.
@mkondratek @Sa1to @exigow can you give it a try as well?

**Comment by pkukielka** [comment]
> I believe the issue here is that there shouldn't be a "Save Current Context as Default" button since the expected behavior is that Cody will start new chats with the same context it had for the previous chat. Confirming with @danielmarquespt

That was what I agree with @danielmarquespt as well. Change of the behaviour was just merged: https://github.com/sourcegraph/jetbrains/pull/646
