### ISSUE TITLE
JetBrains: Code context files are not preserved when re-launching the editor and opening previous chat from "Chat History".

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#636]
### Installation Information

**Version:**
5.2.23857-nightly and 5.2.23711-nightly

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains IntelliJ IDEA editor
2. User is already logged in to Cody with PRO subscription
3. Open any code file, select code snippet and go to Cody "Commands" and select "Explain Code"
4. Verify that At the top of the chat transcript, the arrow dropdown to display the code that Cody used as context.
5. Close the editor and relaunch it.
6. Go to Cody "Chat History"
7. Open the recent chat from step-3

**Observed behavior:**
Chat context files are missing from the transcript/conversation history.

### Expected behavior

It should keep showing the chat context used to generate that response.

### Additional context (logs, images, etc)

**Video link:**

https://drive.google.com/file/d/1eY59lT1mi8YTfTT_Ou_ntjtCTYtbmcQD/view?usp=drive_link

**Comment by pkukielka** [comment]
I took the liberty to change title from " Code context is not preserved" to " Code context files are not preserved" as that is what is happening there.
Context is still the same, and transcript is preserved (which you can check by asking some question regarding history of the conversation). 
It's something we should fix, but it have small impact (if any) on the followup answers of the agent.

**Comment by kalanchan** [comment]
going to close for now, let's revisit if it becomes a problem
