### ISSUE TITLE
Log additional telemetry to track "% of cody code inserted from chats/commands"

### ISSUE THREAD

**Issue by kelsey-brown** [sourcegraph/jetbrains#637]
Per request from this [PRD](https://docs.google.com/document/d/1RO6BiFILyciMy8UtkznX6Z4ewqzJhwmhg7CEKI-YrSg/edit) (and to get to parity with logging in VSCode), we need to start logging the events + metadata required to measure “% of cody code inserted or pasted from chats and commands”. Requirements below:

**Code generation events**  
These events log when Cody returns code via a chat or command/fixup response.

- Event: CodyJetBrainsPlugin:fixupResponse:hasCode
    - Behavior: fires when a fixup response from cody contains code
    - Metadata: logs the lineCount, the number of lines of code generated in the response
- Event: CodyJetBrainsPlugin:chatResponse:hasCode
    - Behavior: fires when a chat response from cody contains code
    - Metadata: logs the lineCount, the number of lines of code generated in the response

**Code insert events**
These events log when the user copies/inserts code returned by cody via a chat or command response. 

- Event: CodyJetBrainsPlugin:keyDown:Paste:clicked
    - Behavior: Fires on paste event from hot-keys (e.g. cmd+v)
    - Metadata: logs the lineCount, the number of lines of code generated in the response
- Event: CodyJetBrainsPlugin:insertButton:clicked
    - Behavior: fires when user clicks paste button in the extension
    - Metadata: logs the lineCount, the number of lines of code generated in the response and logs the lineCount metadata
- Event: CodyJetBrainsPlugin:inlineChat:Paste:clicked
    - Behavior: fires when user clicks paste button inline and logs the lineCount metadata
    - Metadata: logs the lineCount, the number of lines of code generated in the response and logs the lineCount metadata
 
Note that these events need to be instrumented as V1 to meet the customer's timeline requirements. 

cc @abeatrix who instrumented most (all?) of these events in VSCode - please let me know if I'm off-base on the behavior of any events!

cc @aramaraju and @taylorsperry FYI

**Comment by aramaraju** [comment]
@taylorsperry Can you help make this happen :) ?

**Comment by taylorsperry** [comment]
@pkukielka could you please help make sure this gets assigned? Thank you! cc @aramaraju

**Comment by pkukielka** [comment]
Hey, I some additional questions:

1)

```
Event: CodyJetBrainsPlugin:chatResponse:hasCode
Behavior: fires when a chat response from cody contains code
Metadata: logs the lineCount, the number of lines of code generated in the response
```

I see this event is already logged as `CodyVSCodeExtension:chatResponse:hasCode` in the cody, and JetBrains uses that part of the code. So it will be kind of logged twice. Is that expected or should we skip it?

2) `fixupResponse` - IntelliJ does not have fixups right now so I assume this is not in the scope?

3) `Note that these events need to be instrumented as V1 to meet the customer's timeline requirements.`
|I see all that events in VS code are logged with `hasV2Event: true` param. Maybe it indicates V1 also, but I'm a bit confused as I see few different APIs for logging being used currently. Who would be best person to talk about that with?

**Comment by kelsey-brown** [comment]
>1. I see this event is already logged as CodyVSCodeExtension:chatResponse:hasCode in the cody, and JetBrains uses that part of the code. So it will be kind of logged twice. Is that expected or should we skip it?

I _think_ this question relates to item 3 here, so see the response there. 

> 2. fixupResponse - IntelliJ does not have fixups right now so I assume this is not in the scope?

Ah I'm sorry, I didn't realize we didn't have feature parity here. Yes you can assume this is out of scope until that feature is added

> 3. |I see all that events in VS code are logged with hasV2Event: true param. Maybe it indicates V1 also, but I'm a bit confused as I see few different APIs for logging being used currently. Who would be best person to talk about that with?

@dadlerj or @akalia25 could you point @pkukielka in the right direction here? At a high level, we are transitioning to a new way of logging these events (called V2) but we're right in the middle of that transition, so we haven't switched over our production analytics to use any V2 data yet - we're still using V1. Until we make the switch, we're essentially logging both a V1 and V2 event for many of these events. We expect this to be short term - we'll eventually retire V1 and only log V2.
