### ISSUE TITLE
JetBrains: cody.at-mention '@' is slow to respond for a large repo.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#652]
### Installation Information

Plugin version: `5.3.27-nightly`
IDE version: `IC-233.14015.106`

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains IntelliJ IDEA editor
2. User is already logged in to Cody with PRO subscription
3. Have a large repo added i.e. https://github.com/JetBrains/intellij-community
4. Local Project is already indexed
5. Start a new chat and type '@' any file name

**Observed behavior:**
Result will start populating after 20+ seconds

### Expected behavior

If the local project is already indexed then it should not take 20+ seconds to populate the suggestions.

### Additional context (logs, images, etc)

**Video link:**

https://drive.google.com/file/d/1eghsawBNCBFbItXmR1STUrkYEXQP1l-K/view?usp=drive_link

**Comment by taylorsperry** [comment]
This is not totally surprising (@beyang anticipated this). I don't think it's a blocker for tomorrow, but definitely something we should follow up on next week.

**Comment by kalanchan** [comment]
From refinement session:
- Needs more attention and a better(?) implementation to quickly surface large files in @ search 
- @taylorsperry would like to see his higher prioritized

**Comment by mkondratek** [comment]
https://github.com/JetBrains/intellij-community/blob/19540c2d9bb9e405e9a65d538a7a1fafdf723b9b/platform/lang-impl/src/com/intellij/ide/actions/GotoFileAction.java#L15

This is probably the best we can find in IntelliJ code and this is not enough 😕
