### ISSUE TITLE
JetBrains: "Chat History" from yesterday is not available for enterprise account.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#656]
### Installation Information

Plugin version: `5.3.27-nightly`
IDE version: `IC-233.14015.106`

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains IntelliJ IDEA editor
2. User is already logged in to Cody with Enterprise subscription and have performed some Cody chat yesterday
3. Remove the account and used another account today
4. Again login to Enterprise account today

**Observed behavior:**
"Chat History" from yesterday is gone.

### Expected behavior

"Chat History" for Enterprise account should be available.

### Additional context (logs, images, etc)

**Screenshot:**

![Screenshot 2024-02-15 at 12 22 57 AM](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/9a02fc39-6d82-4ce5-8d73-bf63c8691588/435123e2-d8cf-4ed9-a418-e2ed04774bbf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy85YTAyZmMzOS02ZDgyLTRjZTUtOGQ3My1iZjYzYzg2OTE1ODgvNDM1MTIzZTItZDhjZi00ZWQ5LWE0MTgtZTJlZDA0Nzc0YmJmIiwiaWF0IjoxNzE3MTAxNTU4LCJleHAiOjMzMjg3NjYxNTU4fQ.du8ugOeCoukUzq8SSwojlRATKHU-xomlV200ajcX7tM "=406x")

**Comment by jay-fibi** [comment]
Update:
It is loading for me now. Not sure what happened atm. Feel free to close it out.

**Comment by taylorsperry** [comment]
Thanks for flagging. We'll monitor this!

**Comment by mkondratek** [comment]
Our persistence seems to show some flakiness occasionally 😕
