### ISSUE TITLE
bug: StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#679]
Multiple reports of this exception. Collecting them here: 

https://github.com/sourcegraph/jetbrains/issues/560
https://github.com/sourcegraph/jetbrains/issues/569
https://github.com/sourcegraph/jetbrains/issues/570
https://github.com/sourcegraph/jetbrains/issues/576
https://github.com/sourcegraph/jetbrains/issues/577
https://github.com/sourcegraph/jetbrains/issues/580
https://github.com/sourcegraph/jetbrains/issues/581
https://github.com/sourcegraph/jetbrains/issues/583
https://github.com/sourcegraph/jetbrains/issues/585
https://github.com/sourcegraph/jetbrains/issues/588
https://github.com/sourcegraph/jetbrains/issues/589
https://github.com/sourcegraph/jetbrains/issues/604
https://github.com/sourcegraph/jetbrains/issues/614
https://github.com/sourcegraph/jetbrains/issues/618
https://github.com/sourcegraph/jetbrains/issues/629
https://github.com/sourcegraph/jetbrains/issues/644
https://github.com/sourcegraph/jetbrains/issues/579
https://github.com/sourcegraph/jetbrains/issues/799

**Comment by mkondratek** [comment]
This issue should be fixed by https://github.com/sourcegraph/jetbrains/pull/567 in the latest release ([5.3.27](https://plugins.jetbrains.com/plugin/9682-sourcegraph-cody--code-search/versions/stable/486681)).

**Comment by taylorsperry** [comment]
Nice, let's keep an eye on it and close if we don't get any reports from the latest version. Sound good?

**Comment by pkukielka** [comment]
No new reports from new versions, closing this one.

**Comment by mobile-pablo** [comment]
Its repeating

**Comment by mobile-pablo** [comment]
<img width="1687" alt="Zrzut ekranu 2024-07-4 o 10 16 51" src="https://github.com/sourcegraph/jetbrains/assets/70174448/f32abb24-6eaf-4f19-9cb8-b97e31219927">

**Comment by mkondratek** [comment]
Hi @mobile-pablo 👋 Please note which AI assistant throws the exception - it's GitHub Copilot to be blamed, not Cody 😄 I kindly invite you to switch and use Cody instead 😉

**Comment by mobile-pablo** [comment]
Sorry bad PR haha
