### ISSUE TITLE
bug: ResponseErrorException: accessing Sourcegraph GraphQL API

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#680]
Multiple reports of what appear to be the same issue, collected here: 

https://github.com/sourcegraph/jetbrains/issues/501
https://github.com/sourcegraph/jetbrains/issues/514
https://github.com/sourcegraph/jetbrains/issues/521
https://github.com/sourcegraph/jetbrains/issues/564
https://github.com/sourcegraph/jetbrains/issues/568
https://github.com/sourcegraph/jetbrains/issues/578
https://github.com/sourcegraph/jetbrains/issues/590
https://github.com/sourcegraph/jetbrains/issues/591
https://github.com/sourcegraph/jetbrains/issues/595
https://github.com/sourcegraph/jetbrains/issues/615
https://github.com/sourcegraph/jetbrains/issues/616
https://github.com/sourcegraph/jetbrains/issues/625
https://github.com/sourcegraph/jetbrains/issues/643
https://github.com/sourcegraph/jetbrains/issues/654
https://github.com/sourcegraph/jetbrains/issues/655
https://github.com/sourcegraph/jetbrains/issues/657
https://github.com/sourcegraph/jetbrains/issues/667
https://github.com/sourcegraph/jetbrains/issues/688
https://github.com/sourcegraph/jetbrains/issues/701
https://github.com/sourcegraph/jetbrains/issues/711
#791

**Comment by pkukielka** [comment]
Partially addressed by https://github.com/sourcegraph/jetbrains/pull/876 but we should get to the bottom of the problem.
Looks like a problem with this endpoint: https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/lib/shared/src/sourcegraph-api/graphql/queries.ts?L15%3A1-26%3A3
