### ISSUE TITLE
bug: ResponseErrorException: current user subscription data not found

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#681]
Multiple reports, collected here: 

https://github.com/sourcegraph/jetbrains/issues/487
https://github.com/sourcegraph/jetbrains/issues/508
https://github.com/sourcegraph/jetbrains/issues/516
https://github.com/sourcegraph/jetbrains/issues/536
https://github.com/sourcegraph/jetbrains/issues/558
https://github.com/sourcegraph/jetbrains/issues/573
https://github.com/sourcegraph/jetbrains/issues/674
https://github.com/sourcegraph/jetbrains/issues/713
https://github.com/sourcegraph/jetbrains/issues/840

**Comment by mkondratek** [comment]
This comment can be important: https://github.com/sourcegraph/jetbrains/issues/754#issuecomment-1954370619

> I am able to reliably reproduce this issue on virtual machine.
> 
> This is somehow related to https://github.com/sourcegraph/jetbrains/issues/38. I'm receiving "Missing access token" after restart.
~ @exigow

**Comment by taylorsperry** [comment]
Hey @mkondratek and @pkukielka, a user recently reported this (I don't have any more context than this [thread](https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1710456688565169), so I don't know how long ago/which version)

> On my IDEs, such as Goland, I periodically have to sign in again, but I'm not sure what causes this. With Sourcegraph, my token hasn't changed as I've kept it the same.

Should I request more info from the user (version? logs if it happens again?) or do you suspect the problem has been addressed by PRs related to this issue?
