### ISSUE TITLE
bug: Failed to start Cody agent

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#723]
#859 #815 #813 #811 #809 #808 #807 #801 #798 #792 #785 #783 #781 #779 #777 
 #776 #775 #774 #773 #772 #771 #770 #757 #747 #739 #738 #727 #726 #724 #719 
 #718 #717 #714 #712 #709 #708 #704 #699 #698 #697 #696 #683 #617

**Comment by pkukielka** [comment]
I did a few changes to address this issue:

- added better verbose logging which should help us debug the issue if it will persist
- removed need of copying agent binary every time on startup
- removed some unnecessary calls to agent on startup
- increased agent startup timeout (looks like it was too short on older machines)

That should at least partially mitigate the issue. Long term solution would require more in-depth profiling of cody startup but I would not count for easy wins there.

@taylorsperry 
I do not plan to do more work on this in this cycle. 
I would say let's keep it open, but move to the next cycle and observe if amount of reports will drop after my current changes are released.

**Comment by mkondratek** [comment]
@pkukielka idk if you've seen it already but the error from this: https://github.com/sourcegraph/jetbrains/issues/859 looks slightly different 

```
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
```

**Comment by pkukielka** [comment]
> @pkukielka idk if you've seen it already but the error from this: #859 looks slightly different
> 
> ```
> Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
> ```

It's a different issue in my opinion, I reopened it.
Every agent issue can lead to problem with cody startup, but especially crashes are a different thing.
This one was specifically related to slow/hanging startup.

**Comment by taylorsperry** [comment]
Hey @pkukielka we've gotten a few reports of of agent failing to start in v5.3.3914 (which I believe was cut after you shipped your fixes). 

https://github.com/sourcegraph/jetbrains/issues/1008
https://github.com/sourcegraph/jetbrains/issues/1009
https://github.com/sourcegraph/jetbrains/issues/1011
https://github.com/sourcegraph/jetbrains/issues/1012
https://github.com/sourcegraph/jetbrains/issues/1024
https://github.com/sourcegraph/jetbrains/issues/1053
https://github.com/sourcegraph/jetbrains/issues/1063
https://github.com/sourcegraph/jetbrains/issues/1055
https://github.com/sourcegraph/jetbrains/issues/1066
https://github.com/sourcegraph/jetbrains/issues/1067
https://github.com/sourcegraph/jetbrains/issues/1068
https://github.com/sourcegraph/jetbrains/issues/1069
https://github.com/sourcegraph/jetbrains/issues/1084

**Comment by taylorsperry** [comment]
`5.4.358-nightly` 
https://github.com/sourcegraph/jetbrains/issues/1107

`5.4.358`
https://github.com/sourcegraph/jetbrains/issues/1126
https://github.com/sourcegraph/jetbrains/issues/1139

per @pkukielka these should be fixed in next release
