### ISSUE TITLE
bug: NullPointerException

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#724]
https://github.com/sourcegraph/jetbrains/issues/684
https://github.com/sourcegraph/jetbrains/issues/695
https://github.com/sourcegraph/jetbrains/issues/702
https://github.com/sourcegraph/jetbrains/issues/705
https://github.com/sourcegraph/jetbrains/issues/706
https://github.com/sourcegraph/jetbrains/issues/720
https://github.com/sourcegraph/jetbrains/issues/721

**Comment by pkukielka** [comment]
Fixed by https://github.com/sourcegraph/jetbrains/pull/722
