### ISSUE TITLE
bug:  IntelliJ indentation incorrect when doing method fill

### ISSUE THREAD

**Issue by ajaynz** [sourcegraph/jetbrains#787]
### Installation Information

I am using latest IntelliJ release against demo.sourcegraph.com

### Describe the bug

Ask Cody to fill out a bubble sort algo,  Cody writes it out properly but the indentation is not right:
https://www.loom.com/share/c25117f5a67a4435a4a5d74b01b7bfb4?sid=75369066-d9f8-4c84-99b3-6146050d271e

### Expected behavior

New line after each { bracket, followed by indentation

**Comment by taylorsperry** [comment]
@ajaynz are you still able to repro this issue? I believe it should be fixed by https://github.com/sourcegraph/jetbrains/pull/1005. Please reopen if not.

**Comment by ajaynz** [comment]
Hi @taylorsperry the indentation seems to be fixed. 
But nonetheless - I have been having issues with completions offlate.
I posted my [feedback here](https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1712052224691419)
