### ISSUE TITLE
JetBrains: "Copy" button border gets cut for generated test in Cody window.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#788]
### Installation Information

Plugin version: ```5.3.27```
IDE version: ```IC-233.14475.28```

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains IntelliJ IDEA editor
2. User is already logged in to Cody with Pro subscription
3. Select code and click on "Generate Test" command
4. Check the generated test from the response

**Observed behavior:**
Border for "Copy" button gets cut.

### Expected behavior

"Copy" button should be clearly visible.

### Additional context (logs, images, etc)

Screenshot:

![CopyText](https://github.com/sourcegraph/jetbrains/assets/158482423/831efee2-ef84-4709-a723-d772ff5f90a5)

**Comment by olejorgenb** [comment]
Happens on linux for pycharm using the old style jetbrain UI as well.

5.5.10 plugin version
