### ISSUE TITLE
bug: Choose your own LLM missing on Pro

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/jetbrains#793]
### Installation Information

v5.3.27

### Describe the bug

LLM selector missing on pro

### Expected behavior

supposed to include all LLM choices - claude 2.1, gpt4, etc

### Additional context (logs, images, etc)

5.2.23857-nightly 
![image](https://github.com/sourcegraph/jetbrains/assets/51868853/bcaf0295-35d2-40db-91d4-3a6f61067c83)

5.3.27
![image](https://github.com/sourcegraph/jetbrains/assets/51868853/6a889f70-030d-44db-a388-4ad04357afcb)

cody pro confirmation
![image](https://github.com/sourcegraph/jetbrains/assets/51868853/1857c8cb-722a-4cb2-946a-ada60a60df3b)

**Comment by mkondratek** [comment]
It should be fixed by https://github.com/sourcegraph/jetbrains/pull/796. a new release ([5.3.1544](https://github.com/sourcegraph/jetbrains/releases/tag/v5.3.1544)) is available in as a pre-release (and will be available soon as a release version - stable channel).

**Comment by marvin-hansen** [comment]
Same here. Still missing.

**Comment by marvin-hansen** [comment]
Switching to nightly installs version 5.3.1544 which fixes the problem. Please release this to stable soon

**Comment by mkondratek** [comment]
@marvin-hansen the stable channel version should be available 🚀
