### ISSUE TITLE
JetBrains: Issue with loading Cody Recipes

### ISSUE THREAD

**Issue by exigow** [sourcegraph/jetbrains#80]
![image](https://github.com/sourcegraph/jetbrains/assets/5013708/61d06dcf-26f6-45f1-8613-e3ebc24e0b09)

* At first glance it's not related to our latest changes.
* Manual **Retry** fixes issue.

Link to reporter message: https://sourcegraph.slack.com/archives/C059N5FRYG3/p1698955627508139

**Comment by taylorsperry** [comment]
@exigow I'm closing this since it's old and recipes/commands seem to be working correctly.
