### ISSUE TITLE
JetBrains: File context for enhanced context is showing wrong info for "Explain Code" command

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#901]
### Installation Information

Plugin version: `5.3.2625-nightly`
IDE version: `PC-233.13763.11`

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains PyCharm editor
2. User is already logged in to Cody with any Free/Pro/Enterprise subscription
3. Open any file and click on "Explain Code" command
4. Verify the enhanced context from response

**Observed behavior:**
File context info is wrong and file name is shown twice with different line numbers selection

### Expected behavior

Correct context info should be displayed

### Additional context (logs, images, etc)

**Video link:**

https://drive.google.com/file/d/1GNsnRxdRb3PNOyKGHTT3JP2KpEk1y_2d/view?usp=drive_link

**Comment by pkukielka** [comment]
@jay-fibi 
> name is shown twice with different line numbers selection

That is a new feature, not a bug. Assistant is now able to use different parts of the file for a context and it reports it.
Although I agree selected lines looks like a bit weird, it would be nice to compare that with VS Code.
