### ISSUE TITLE
bug: GraphQL query fails due to issues with local certificates

### ISSUE THREAD

**Issue by pkukielka** [sourcegraph/jetbrains#915]
### Installation Information

So far observed on (and probably can happen on any version):

Plugin version: 5.3.27
IDE version: WS-233.14015.89

Plugin version: 5.3.27
IDE version: WS-233.14475.40

### Describe the bug

https://github.com/sourcegraph/jetbrains/issues/867
#752
#944
> Error: accessing Sourcegraph GraphQL API: FetchError: request to https://sourcegraph.com/.api/graphql?CurrentUserCodySubscription failed, reason: unable to get local issuer certificate (https://sourcegraph.com/.api/graphql?CurrentUserCodySubscription)

#711
https://github.com/sourcegraph/jetbrains/issues/842
> Error: accessing Sourcegraph GraphQL API: FetchError: request to https://sourcegraph.com/.api/graphql?CurrentUserCodySubscription failed, reason: self-signed certificate in certificate chain (https://sourcegraph.com/.api/graphql?CurrentUserCodySubscription)

https://github.com/sourcegraph/jetbrains/issues/853
https://github.com/sourcegraph/jetbrains/issues/855
https://github.com/sourcegraph/jetbrains/issues/847
> Error: accessing Sourcegraph GraphQL API: FetchError: request to https://sourcegraph.com/.api/graphql?CurrentUserCodySubscription failed, reason: getaddrinfo ENOTFOUND sourcegraph.com (https://sourcegraph.com/.api/graphql?CurrentUserCodySubscription)

Full stack traces are in the linked issues.

### Expected behavior

To be discussed/checked. I'm not 100% sure if that is legitimate failure or issue with how we are handling those certificates.

**Comment by taylorsperry** [comment]
@pkukielka is this related to the certificate work you're doing in https://github.com/sourcegraph/sourcegraph/issues/61021?
