### ISSUE TITLE
JetBrains: Character "f" is appended in Cody suggestions.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#930]
### Installation Information

Plugin version: `5.3.2625-nightly`
IDE version: `PC-233.13763.11`

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains PyCharm editor
2. User is already logged in to Cody with Free/Pro/Enterprise account
3. Open a python file and type "print()" and remove the ")" character
4. Wait for Cody code suggestion to trigger

**Observed behavior:**
Cody code suggestion is adding an unwanted character "f" in the `print(f"hello...")` statement

### Expected behavior

The suggested code should not be having such unwanted characters appended

### Additional context (logs, images, etc)

**Video link:**

https://drive.google.com/file/d/1a36XlBkMvzrzndIYiyq1q8gUubXp2XPn/view?usp=drive_link

**Comment by taylorsperry** [comment]
I'm unable to repro this on `5.3.1544` on MacOS @jay-fibi . Has this been resolved, or is it specific to Windows?

**Comment by jay-fibi** [comment]
@taylorsperry I am unable to repro this issue today with `5.3.2999-nightly` on MacOS. No, it is not Windows specific. Feel free to close it.
