### ISSUE TITLE
PRD: [JB] Chats expose the context Cody used to generate a response

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#94]
### Description:

As a user, I want to know exactly what Cody used as context when providing a response to a chat prompt. While I may tag particular repos, files, or symbols to help guide Cody in the right direction, I know that Cody won't send everything in a given repo or file to the LLM when generating a response. I want to know which chunks of code were sent to the LLM and be able to navigate to that part of my codebase. For example, if I ask Cody where auth is defined and give my-repo as context, Cody may send my-repo/auth.js/15-34 to the LLM. I'd want to understand that my-repo/auth.js/15-34 was used as context and be able to navigate to line 15 of that file.

We know that confusion about context is a serious pain point among users, which is why we're introducing more visibility (and, in a separate PRD issue, more configurability). We also know that users go to Cody chat for onboarding, brainstorming, and help figuring out "where to start," which means that they might not always be very prescriptive in the context that they give Cody, even when we're able to support pretty granular configurability.

### Objectives:

Give users clear visibility into what Cody used as context when generating a response and allow them to navigate to those parts of their codebase.

```[tasklist]
### Acceptance Criteria:
- [x] https://github.com/sourcegraph/jetbrains/issues/375
- [x] https://github.com/sourcegraph/jetbrains/issues/376
- [ ] https://github.com/sourcegraph/jetbrains/issues/377
- [x] Show remote context files
- [x] show multiple link renders
```

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/sourcegraph/jetbrains/issues/255
- [ ] https://github.com/sourcegraph/jetbrains/issues/298
- [ ] https://github.com/sourcegraph/jetbrains/issues/339
```

### Related Docs:

- [PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit)

**Comment by taylorsperry** [comment]
We'll also need to handle drift between branches/embeddings. I've opened https://github.com/sourcegraph/cody/issues/2462 to start discussing with the VSC team. We should collaborate with them on the problem space and solution.

**Comment by olafurpg** [comment]
Is it OK if we remove "clickable links" from the acceptance criteria? We can turn that into a P1/P2 issue for post GA. This user story is currently P0 and only blocked by lack of clickable links.

**Comment by taylorsperry** [comment]
As much as I'd like to have the clickable links (which I think promote usability), it's not a blocker for GA and there are other things that are more. I've removed the GA prefix.

**Comment by mkondratek** [comment]
done
