### ISSUE TITLE
PRD: [JB] It's easy to copy code that Cody generates in chats

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#95]
### Description:

As a user, I want to copy and paste code that Cody suggests in a chat. Instead of having to highlight the code and press command+c and command+v, I want to see options to copy the code with one click or insert the code at my cursor in my project file.

### Objectives:

Make copy and pasting code easy with one-click options to copy code or insert code at cursor. It's important that these are easily discoverable for the user.

```[tasklist]
### Acceptance Criteria:
- [ ] Easily discoverable "copy code" option
- [ ] Easily discoverable "insert at cursor" option
```

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
```

### Related Docs:

- [PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit)

**Comment by taylorsperry** [comment]
Moving this from "Done" to "To consider in planning" because we need to make sure that we still meet this criteria when we move to the new UI.

**Comment by olafurpg** [comment]
Moving this back to "Done" since we're still keeping the same chat *UI* in the sidebar, we're only moving to the new chat API in the agent. I may have used the phrase "move to the new chat UI" when I technically meant the new "chat API" (it was called "new chat UI" in VS Code)

**Comment by olafurpg** [comment]
From offline discussion with the team, we agreed that the current design leaves room for improvements because it does not feel idiomatic. Not a blocker for GA but worth looking into in the future. FYI @taylorsperry 

![Image](https://github.com/sourcegraph/jetbrains/assets/1408093/d0428b80-81bd-4485-98df-465c0b685d3a)
