### ISSUE TITLE
PRD: [JB] Users can edit a previous prompt and get a new response from Cody

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#96]
### Description:
As a user, I want to be able to edit and resubmit an existing prompt and get a new response. This is a feature that ChatGPT supports and is likely to be an expectation among Cody users as well.

### Objectives:

P1: Allow Cody users to edit and resubmit an existing prompt and get a new response; P2: Support this without destroying the initial prompt and response, so that users can see all iterations of their initial prompt.

```[tasklist]
### Acceptance Criteria:
- [ ] P1: Users can easily edit and resubmit an existing prompt to get a new response.
- [ ] P2: Users can browse all iterations of an edited prompt and their responses.
```

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/sourcegraph/jetbrains/pull/25
```

### Related Docs:

- [PRD: Your-Title]()

**Comment by mkondratek** [comment]
IDK if that's enough but we have a chat history - a user can navigate through the sent prompts with up and down arrows

**Comment by exigow** [comment]
> IDK if that's enough but we have a chat history - a user can navigate through the sent prompts with up and down arrows

+1, related PR: https://github.com/sourcegraph/jetbrains/pull/25

**Comment by exigow** [comment]
Marked as Done. @taylorsperry FYI

**Comment by taylorsperry** [comment]
Closing because P1 is done. The P2 (being able to view multiple iterations of the same edited chat) is something I need to think about more.
