### ISSUE TITLE
JetBrains: Cody autocompletion is not working on Windows.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#964]
### Installation Information

Plugin version: ```5.3.2999-nightly```
IDE version: ```IC-233.14475.28```

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains IntelliJ IDEA editor
2. User is already logged in to Cody with Free/Pro/Enterprise account
3. Open any Java file and type as below,
```
// print Hello World!
System.out. 
```
4. Place a cursor at the end of the `System.out.` line.
5. Trigger autocompletion with `Alt + /`

**Observed behavior:**
Cody autocompletion does not triggered.

### Expected behavior

Cody autocompletion should work and finish the remaining line of code as below,
```
// print Hello World!
System.out.println("Hello World!")
```

### Additional context

**Video link:**

https://drive.google.com/file/d/1T551u6MBUH1-5STDjQv7uf4l0nHX5fxB/view?usp=drive_link

**Comment by pkukielka** [comment]
Fixed in https://plugins.jetbrains.com/plugin/9682-sourcegraph-cody--code-search/versions/nightly/499547
