### ISSUE TITLE
JetBrains: LLM dropdown shows "Unknown by Unknown" when selecting earlier chat from 'Chat History'.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#965]
### Installation Information

Plugin version: `5.3.2999-nightly`
IDE version: `IC-233.14475.28`

### Describe the bug

**Steps to reproduce:**

1. Install JetBrains IntelliJ IDEA editor and open any git project. 
2. Have Cody plugin installed in your editor.
3. Login to Cody using Google account having a Chat History.
4. Upon successful login, go to 'Chat History' and open any previous chat.

**Observed behavior:**
LLM dropdown values shown as "Unknown by Unknown".

### Expected behavior

LLM values should be correctly shown for historical chats.

### Additional context

**Video link:**

https://drive.google.com/file/d/1twXIim-KCeEmH4u3l0iEILguCDCZXtJG/view?usp=drive_link

**Comment by mkondratek** [comment]
@jay-fibi can you share `.idea/cody_history.xml` (maybe as a Google Drive file or via Slack)? 🙏

**Comment by mkondratek** [comment]
Note that there can be cases when we do not know the model for a historical chat - e.g. a users malformed the persistence file OR something went wrong on saving the persistence file. Ideally, we would show such a chat as ready only.

btw: my recent changes renamed "Unknown" to "Default" so this scenario seems to be less error-like to the user.

**Comment by jay-fibi** [comment]
@mkondratek Shared the file via Slack.
