### ISSUE TITLE
JetBrains: File will not be opened when clicking on file name from Context in response in Windows.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#966]
### Installation Information

Plugin version: `5.3.2999-nightly`
IDE version: `IC-233.14475.28`

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains IntelliJ IDEA editor
2. User is already logged in to Cody with Free/Pro/Enterprise account
3. Open any file and go to "Commands" and select "Explain Code" and make sure that only single file should be shown under Context from response.
4. Close the opened file and click on file name from Context link

**Observed behavior:**
File will not be opened when clicked from Context in the response.

### Expected behavior

File should be opened correctly.

### Additional context

**Video link:**

https://drive.google.com/file/d/1sRxTdWh7PKrC9he3zvanURYc91n47BZ3/view?usp=drive_link

**Comment by pkukielka** [comment]
Fixed in https://plugins.jetbrains.com/plugin/9682-sourcegraph-cody--code-search/versions/nightly/499547
