### ISSUE TITLE
bug: Code is formatted incorrectly after code completion

### ISSUE THREAD

**Issue by pkukielka** [sourcegraph/jetbrains#987]
### Installation Information

Standard installation, all versions

### Describe the bug

![image](https://github.com/sourcegraph/jetbrains/assets/1519649/ef43aaaa-256c-40f2-b9ca-e0f07ad31adf)
https://twitter.com/danaketh/status/1765117259234603500

### Expected behavior

Could should always be formatted correctly

### Additional context

IntelliJ formatting have separate action which we could just call after the completion is done.
We try to make sure we insert completion at the right position regarding surrounding text, but I guess it might not be 100% robust. Also it won't help for adjusting e.g. whole completion block to the project coding standard, and using IJ formatter would help there.

**Comment by taylorsperry** [comment]
Similar report here https://github.com/sourcegraph/sourcegraph/issues/60590

(And thank you for beating me to creating this issue, @pkukielka !)
