### ISSUE TITLE
Add Claude 3 to Pro chat dropdown

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#993]
TLDR: Add support for Claude 3 Sonnet to the LLM chat dropdown for Pro users and "hide" Claude 2.1. Threads [here](https://sourcegraph.slack.com/archives/C05AGQYD528/p1709565196918819) and [here](https://sourcegraph.slack.com/archives/C05AGQYD528/p1709638080344719).

**Comment by kalanchan** [comment]
related: https://github.com/sourcegraph/cody/pull/3301

**Comment by mkondratek** [comment]
https://sourcegraph.com/-/editor?remote_url=github.com%2Fsourcegraph%2Fcody&branch=main&file=lib%2Fshared%2Fsrc%2Fmodels%2Fdotcom.ts&start_row=4&start_col=0&end_row=55&end_col=0&editor=JetBrains&version=v5.3.2999-nightly

It looks like we will need to update `codyCommit` once the changes to the agent are in place.

**Comment by pkukielka** [comment]
@mkondratek can we close this one?
