### ISSUE TITLE
JetBrains: Remote repo names are showing two times in Context window.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#998]
### Installation Information

Plugin version: `5.3.3914-nightly`
IDE version: `IC-233.14475.28`

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains IntelliJ IDEA editor
2. User is already logged in to Cody with Enterprise account
3. Add few Remote repo and check the full name of added repo

### Observed behavior: 
Remote repo names are showing two times.

### Expected behavior

Remote repo name should be shown correctly. This is confusing.

### Additional context

**Screenshot:**

![RepoNamesTwoTimes](https://github.com/sourcegraph/jetbrains/assets/158482423/99f0ef47-8bf4-4175-9d18-f8fcb1b1a0b1)

**Comment by mkondratek** [comment]
It has been fixed by https://github.com/sourcegraph/jetbrains/pull/996 and https://github.com/sourcegraph/jetbrains/pull/989.
